### ISSUE TITLE
Rename Queuable.getResponse for improving readability

### ISSUE THREAD

**Issue by HeartSaVioR** [redis/jedis#1013]
It's from #292 but seems like we should upmerge.
#292 suggests method's name to 'enqueueResponse'.

**Comment by tgrall** [comment]
@gkorland @sazzad16: I think this issue could be closed as the suggestion has been implemented with #292 fix

See https://github.com/xetorthio/jedis/pull/292/files

**Comment by sazzad16** [comment]
@tgrall #292 was NOT merged.
And, actually this idea was generated from that PR.

**Comment by sazzad16** [comment]
Resolved by https://github.com/redis/jedis/commit/858c8051301854e8343eef66aa68c6b9dab1c328
