### ISSUE TITLE
JedisSentinelPool requires port whereas the JedisPool does not. Should default to Protocol.DEFAULT_SENTINEL_PORT

### ISSUE THREAD

**Issue by joetennant** [redis/jedis#1089]
JedisSentinelPool parses the set of sentinel addresses (as string) and converts them to HostAndPort instances. However, it always attempts to parse the port value and fails when no port is provided.

Instead this should act like JedisPool and use the default sentinel port as defined by Protocol when no port is provided.

**Comment by samklr** [comment]
+1

**Comment by marcosnils** [comment]
Seems right to implement. Anyone willing to craft a PR?

**Comment by Sufiyan1997** [comment]
Is this issue still accepting PRs?
