### ISSUE TITLE
Incorrect lua script execution in slave cluster node

### ISSUE THREAD

**Issue by fggarcia** [redis/jedis#1175]
Trying execute a lua script in a redis cluster version (3.0.5) with Jedis version (2.8.0).
Script tries to delete keys, so it must be executed only in redis master.

Generates the following error.

ERR Error running script (call to f_5760b0a4ffee43ea6c73312fc8215383de7fccfd): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.

--------------------SCRIPT---------------
local keys_to_delete = redis.call('KEYS', '*')

--http://stackoverflow.com/questions/21707021/lua-script-for-redis-which-sums-the-values-of-keys

for _,key in ipairs(keys_to_delete) do
    redis.call('DEL', key)
end
return 0
-----------------SCRIPT---------------
PD: redis.call('KEYS', '*') -> \* is hash tags value.

**Comment by marcosnils** [comment]
@fggarcia if you execute the lua script directly from the redis-cli. Do you get the same error?. At I first glance seems to me it has nothing to do with Jedis but I might be wrong.

**Comment by HeartSaVioR** [comment]
@fggarcia Could you please share your code snippet?

**Comment by fggarcia** [comment]
@HeartSaVioR 

cachePricesDestination.exec(LuaCreatorScript.deleteKeysWithRegex(prefixCacheKey + "*"), prefixHashCacheKey)

object LuaCreatorScript {
  def deleteKeysWithRegex(regex: String): String =
    s"local keys_to_delete = redis.call('keys', '$regex') " +
      "for _,key in ipairs(keys_to_delete) do " +
        " redis.call('DEL', key) " +
      "end " +
  "return 0"
}

try{
      jedisCluster.eval(script.getBytes, keyTag.getBytes)
    } catch {
      case e: TimeoutException =>
        logger.warn("REDIS TIMEOUT - EXEC FOR " + script, e)
      case e: Throwable =>
        logger.warn("UNKNOWN REDIS ERROR- EXEC FOR " + script, e)
    }

**Comment by abhishekaj** [comment]
Hi All,

**Comment by abhishekaj** [comment]
Hi @fggarcia ,
I am facing the same issue in redis cluster. I am using redlock gem for distributed locking in ruby which executes lua script.

Command which I am executing - 
$redis_lock_manager = Redlock::Client.new(["redis://#{Settings.redis_cluster.host}:#{Settings.redis_cluster.port}"])
$redis_lock_manager.lock('test_1', 30*1000)

It is trying to write in slave and I am getting the following error -
Redis::CommandError: ERR Error running script (call to f_a90bf4be8a6e440e3cc24540eb2f9ff1e16fbcc3): @user_script:2: @user_script: 2: -READONLY You can't write against a read only replica.

Furthur logs -

1556186552.801137 [0 10.0.1.126:52720] "evalsha" "a90bf4be8a6e440e3cc24540eb2f9ff1e16fbcc3" "1" "test_1" "68393f08-38b2-4788-b42c-1786cbbfb81b" "50000" "yes"
1556186552.801167 [0 lua] "exists" "test_1"
1556186552.801174 [0 lua] "get" "test_1"

Can you please help with this?
