### ISSUE TITLE
Poposal - lua script helper

### ISSUE THREAD

**Issue by dvirsky** [redis/jedis#1232]
Hi. I've written a little wrapper for running lua scripts with Jedis. I wrote it as an external library because I needed it immediately, but if this direction suits you, I'd be glad to adapt it to Jedis itself and make a proper PR of it. 

See https://github.com/RedisLabs/luascript

If it gets integrated inside Jedis, the API could  be even nicer than what I did. Let me know if you want this. 

Thanks.

**Comment by marcosnils** [comment]
@dvirsky I really like this approach and I believe it would be something super valuable to Jedis. I'm in favor of evaluating the alternative to include it. 

@HeartSaVioR @xetorthio? WDYT

**Comment by dvirsky** [comment]
@marcosnils thanks! I'm thinking that if you add this to jedis, the API will be, instead of LuaScript s = LuaScript.fromResource("lua/simple.lua", "redis://localhost:6379");` - just `LuaScript s = myJedis.loadScript("lua/simple.lua);`

**Comment by marcosnils** [comment]
@dvirsky even better. We'd have to think about how we plug it to other Jedis strategies like ShardedJedis and JedisCluster.

**Comment by marcosnils** [comment]
@HeartSaVioR ping?

**Comment by HeartSaVioR** [comment]
@dvirsky @marcosnils 
Sorry to late participating. It would be nice to have it.
I found some places to comment, but it can be addressed while reviewing pull request.
@dvirsky Could you craft a pull request? Thanks!

**Comment by dvirsky** [comment]
Sure thing! thanks

**Comment by dvirsky** [comment]
Just updating - I've been busy preparing for RedisConf. I'll probably get back to this after I return from the conference. Will any of you attend BTW?

**Comment by marcosnils** [comment]
@dvirsky np, we're waiting wait for your PR anxiously. 

Regarding RedisConf we'd really like to attend but @xetorthio and me are in Argentina and @HeartSaVioR in South Korea which makes it really hard for us to be there :cry:

**Comment by dvirsky** [comment]
too bad :) do keep an eye out for the announcements, cool things coming!
