### ISSUE TITLE
Support issuing Latency commands

### ISSUE THREAD

**Issue by CodingFabian** [redis/jedis#1246]
Currently it is not possible to issue latency commands using jedis. You need to write your own client to issue custom commands.
There are a couple of latency commands (latency history, latency latest) that could be executed. ideally automatically guarded against the redis version (2.8.13 +)

**Comment by marcosnils** [comment]
@CodingFabian good catch. As you seem to need these commands, what do you think about crafting a PR so Jedis can include this functionality?

**Comment by CodingFabian** [comment]
Sure, I am just a bit lost where this should go:
JedisCommands, MultiKeyCommands, AdvancedJedisCommands, ScriptingCommands, BasicCommands, ClusterCommands, SentinelCommands ?

**Comment by marcosnils** [comment]
@CodingFabian I'd start adding it in the BasicCommands interface and move from there.

**Comment by sheinbergon** [comment]
@marcosnils  what's the status of this feature request ? Has this been implemented yet ?

**Comment by marcosnils** [comment]
@sheinbergon there's no open PR, so no. @CodingFabian ping?

**Comment by CodingFabian** [comment]
Nope, havent done anything so far.

**Comment by sheinbergon** [comment]
@marcosnils feel free to assign this to me . I will work on it in the upcoming weeks :+1:

**Comment by marcosnils** [comment]
@sheinbergon no need to assign, maybe @CodingFabian wanted/needed to implement it?. @CodingFabian ?

**Comment by sheinbergon** [comment]
@CodingFabian  I'm guessing you'd like to support LATENCY LATEST , LATENCY HISTORY and LATENCY RESET , right ? Is there anything I missed ? 

@CodingFabian

**Comment by sheinbergon** [comment]
@CodingFabian @marcosnils  ?

**Comment by marcosnils** [comment]
@sheinbergon go ahead and implement it @CodingFabian timed out.

**Comment by CodingFabian** [comment]
I actually had a weekend.
yes. LATENCY LATEST and LATENCY HISTORY is what we wanted.

**Comment by Lcarrot** [comment]
Hello, can i try to solve this issue?
