### ISSUE TITLE
clientName should be support for ShardedJedisPool

### ISSUE THREAD

**Issue by jiafu1115** [redis/jedis#1381]
### Expected behavior

clientName should be support for ShardedJedisPool to keep pace with other pools. What's more, clientName is very usefull for trouble shooting.
### Actual behavior

clientName isn't support for ShardedJedisPool
### Steps to reproduce:

other jedis pool support clientName setting except this.  **So is it one issue? and  can I create one PR to fix this issue?**

**Comment by marcosnils** [comment]
@jiafu1115 I guess we can. Can you explain a bit more about how you use the clientName to troubleshoot?

@HeartSaVioR WDYT?

**Comment by jiafu1115** [comment]
@marcosnils @HeartSaVioR 
How I can do trouble shooting with client name?

I can use 'client list' to check which client had connect with my redis server:

id=2 addr=10.224.38.23:33652 fd=5 name=my-app-name age=1350882
idle=1 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0
omem=0 events=r cmd=ping

if there is no name it will be empty, So I can't judge which app is executing which command.

in other hand, JedisPool and JedisSentinelPool both support ClientName setting, Why we not support it for ShardedJedisPool

So if you agree it is worth to do this, I will create one PR for this issue?

Thanks

**Comment by jiafu1115** [comment]
@marcosnils @HeartSaVioR  WDYT?

**Comment by HeartSaVioR** [comment]
Makes sense to me. Please go ahead. Thanks!

**Comment by jiafu1115** [comment]
@marcosnils @HeartSaVioR  OK, if no problem, I will create one PR for this. 3ks. Wait my update. 3ks.

**Comment by marcosnils** [comment]
@jiafu1115 perfect!

**Comment by jiafu1115** [comment]
@marcosnils  @HeartSaVioR  I have complete the draft  https://github.com/xetorthio/jedis/pull/1383, can you help to review it? Thanks.
