### ISSUE TITLE
The BinaryJedisPubSub should also support PING/PONG

### ISSUE THREAD

**Issue by xbwen** [redis/jedis#1446]
The JedisPubSub already has this feature, but BinaryJedisPubSub hasn't. 

See: https://github.com/xetorthio/jedis/pull/1281

**Comment by marcosnils** [comment]
@xbwen if JedisPubSub is a subclass of BinaryJedisPubSub, what's the necessity to inlcude it in BinaryJedisPubSub as well?

**Comment by xbwen** [comment]
@marcosnils JedisPubSub is not a subclass of BinaryJedisPubSub. The two class have no relationship right now. They are independent.

**Comment by marcosnils** [comment]
@xbwen you're right. We should implement it. Mind submitting a PR?

**Comment by cpeeyush** [comment]
@marcosnils  @xbwen  I have added Ping Pong Support to BinaryJedisPubSub and a test also.

Raised a pull request see #1448

**Comment by marcosnils** [comment]
@cpeeyush thx!.

**Comment by sazzad16** [comment]
Resolved by #2254
