### ISSUE TITLE
API changes report for Jedis

### ISSUE THREAD

**Issue by lvc** [redis/jedis#1644]
Hi,

I'd like to share report on API changes and backward compatibility for the Jedis library: https://abi-laboratory.pro/java/tracker/timeline/jedis/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://central.maven.org/maven2/redis/clients/jedis/ (according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2).

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jedis-1](https://user-images.githubusercontent.com/1517837/32090834-1909e6d0-bafa-11e7-8c0e-5a40cd676e18.png)

![jedis-2](https://user-images.githubusercontent.com/1517837/32090833-18efb814-bafa-11e7-9aab-885c34252a7d.png)

**Comment by sazzad16** [comment]
There is no update after Jedis 3.3.0. Closing.
