### ISSUE TITLE
Implement builder pattern of JedisPool and JedisCluster

### ISSUE THREAD

**Issue by warrenzhu25** [redis/jedis#1780]
### Expected behavior

Currently, the `JedisCluster` constructor has at most 7 parameter.
Now
```java
  public JedisCluster(HostAndPort node, int connectionTimeout, int soTimeout,
          int maxAttempts, String password, String clientName, final GenericObjectPoolConfig poolConfig) {
  }
```

After adding support SSL in `JedisCluster` #1550, the number become 12

```java
  public JedisCluster(Set<HostAndPort> jedisClusterNode, int connectionTimeout, int soTimeout,
                      int maxAttempts, String password, String clientName, final GenericObjectPoolConfig poolConfig,
                      boolean ssl, SSLSocketFactory sslSocketFactory, SSLParameters sslParameters, 
                      HostnameVerifier hostnameVerifier, JedisClusterHostAndPortMap hostAndPortMap) {
  }
```

We should implement builder pattern to make it easy to build.

Same as `JedisPool`

**Comment by sazzad16** [comment]
Yes, we should implement a design pattern in this project. It can be builder pattern or any other pattern. But same pattern should be used in all possible classes not only limited to `JedisCluster` and `JedisPool`.

@warrenzhu25 Would you like to craft a PR?

**Comment by warrenzhu25** [comment]
Ok, I'll do this. Could you help merge #1550 before?

**Comment by sazzad16** [comment]
@warrenzhu25 I've already LGTMed it. Waiting for review from other collaboartor(s).

**Comment by Oziomajnr** [comment]
great
