### ISSUE TITLE
Intermittent "Connection reset by peer" when using JedisCluster with Redis

### ISSUE THREAD

**Issue by yanghuirong** [redis/jedis#1793]
### Expected behavior

No "Connection reset by peer" error in Redis side.

### Actual behavior

I saw "Connection reset by peer" error intermittently in the Redis log. Sometimes it happened once during several hours, sometimes it happened several times during one hour. Sometimes it only have one error at one time, but sometimes it has 30-100 errors at one time. 
I didn't close the JedisCluster when using it. I used JedisCluster on both single-threaded and multi-threaded cases. But I want to focus on the single-threaded use case now.

```
28062:M 20 Mar 08:33:37.238 - Reading from client: Connection reset by peer
28062:M 20 Mar 08:38:07.355 - Reading from client: Connection reset by peer
28062:M 20 Mar 08:38:07.355 - Reading from client: Connection reset by peer
28062:M 20 Mar 08:38:42.265 - Reading from client: Connection reset by peer
28062:M 20 Mar 08:38:42.265 - Reading from client: Connection reset by peer
28062:M 20 Mar 08:42:48.255 - Reading from client: Connection reset by peer
28062:M 20 Mar 08:42:48.255 - Reading from client: Connection reset by peer
28062:M 20 Mar 20:26:55.349 . I/O error reading from node link: Connection reset by peer
28062:M 20 Mar 20:29:15.735 . I/O error reading from node link: Connection reset by peer
28071:S 20 Mar 20:36:15.938 - Error writing to client: Connection reset by peer
28071:S 20 Mar 20:36:22.723 - Error writing to client: Connection reset by peer
28071:M 20 Mar 20:39:01.218 . I/O error reading from node link: Connection reset by peer
28071:M 20 Mar 21:57:03.803 - Reading from client: Connection reset by peer
28071:M 20 Mar 20:39:01.218 . I/O error reading from node link: Connection reset by peer
28071:M 20 Mar 21:57:03.803 - Reading from client: Connection reset by peer
28071:M 21 Mar 01:16:22.471 - Reading from client: Connection reset by peer
28071:M 21 Mar 01:16:22.471 - Reading from client: Connection reset by peer
28071:M 21 Mar 01:16:22.471 - Reading from client: Connection reset by peer
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. I have a Redis cluster with 3 masters and 3 slaves.
2. I have a program which uses JedisCluster to query data from my Redis cluster. I created a singleton JedisCluster with below setting. I tried to tune the soTimeout to 2000, 1000, 300 and 30. I tested load from 5 TPS to 50 TPS. 
3. I saw there are some spikes in the latency side no matter how heavy is the load and I looked at my redis log. The timestamps for "Connection rest by peer error" matched the service latency spike. This problem happened intermittently and I don't know why. No exception found in the client side. Should I continue tuning the config for jedispool? Do you have any clue? or should I ask in Redis github? 

### Redis / Jedis Configuration
Redis - 3 master and 3 slaves
Jedis:
```
    @Singleton
    JedisCluster jedisCluster(){
            Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
            jedisClusterNodes.add(new HostAndPort("10.xx.xx.xx", 6379));
            ........
            jedisClusterNodes.add(new HostAndPort("10.xx.xx.xx", 6379));
            GenericObjectPoolConfig jedisPoolConfig = new GenericObjectPoolConfig();
            jedisPoolConfig.setMaxTotal(16);
            jedisPoolConfig.setMaxIdle(16);
            return new JedisCluster(jedisClusterNodes, 2000, 1000, 5, jedisPoolConfig);
   }
   //When using cluster
    jedisCluster.set("foo", "bar");
```

#### Jedis version:
2.9.x
#### Redis version:
3.2.8
#### Java version:
Java 8

**Comment by marcosnils** [comment]
Can you try if this happens when you spin a redis cluster locally?. Otherwise I guess it's related to network connectivity between your app and the redis cluster
