### ISSUE TITLE
jedis not support rename-command

### ISSUE THREAD

**Issue by fuyuanpai** [redis/jedis#1817]
For safety reason, we have rename some dangerous command like flushdb, eval in case any malicious client call this command.
But jedis can not call the rename command, will jedis add support for rename command?

**Comment by sazzad16** [comment]
@fuyuanpai You are very much welcome to craft PR.

**Comment by gkorland** [comment]
@sazzad16 please review my PR

**Comment by sazzad16** [comment]
@gkorland Which PR? If you mean #1822 , I am actually waiting for opinions from someone else.

@fuyuanpai Does #1822 fulfills your requirement?

**Comment by fuyuanpai** [comment]
Thanks for @gkorland 
@sazzad16  #1822 meets my requirements

**Comment by sazzad16** [comment]
@gkorland Please see my review comments.

**Comment by sazzad16** [comment]
Rename command is now deprecated https://github.com/redis/redis/commit/7604ab7118d1154e9120ea41a88d9c214f2202c3 and #1822 is closed.
