### ISSUE TITLE
Useless retry when jedicluster configured password and try to connect to a node without password

### ISSUE THREAD

**Issue by StillerRen** [redis/jedis#1876]
### Expected behavior
do special handling of JedisDataException: "ERR Client sent AUTH, but no password is set"，do not retry to connect to the node with <attemps> times.
This exception means that no normal connection can be established no matter how many times you try again.

### Actual behavior
when I create a instance of JedisCluster **with password**, and try to connect to a node **without password**, it would report the exception JedisDataException: "ERR Client sent AUTH, but no password is set",  and then the exception is packaged as JedisConnectionException: "Could not get a resource from the pool", JedisClusterCommand would catch this exception and retry <attempts> times.

      // release current connection before recursion
      releaseConnection(connection);
      connection = null;
      if (attempts <= 1) {
        //We need this because if node is not reachable anymore - we need to finally initiate slots renewing,
        //or we can stuck with cluster state without one node in opposite case.
        //But now if maxAttempts = 1 or 2 we will do it too often. For each time-outed request.
        //TODO make tracking of successful/unsuccessful operations for node - do renewing only
        //if there were no successful responses from this node last few seconds
        this.connectionHandler.renewSlotCache();

        //no more redirections left, throw original exception, not JedisClusterMaxRedirectionsException, because it's not MOVED situation
        throw jce;
      }

      return runWithRetries(key, attempts - 1, tryRandomNode, asking);
    }

   at the last time, it would call **renewSlotCache()** to renew the slot message.

Default retries is 5 times, and it would call "Cluster" command, all of these would spend a lot of time.

when some nodes in cluster have password and the other don't, when I use the JedisCluster configured password to send a request to the node without password, it would cause client latency increasing sharply.

I think we need to do special handling of JedisDataException: "ERR Client sent AUTH, but no password is set", and report the exception directly.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. create a cluster that some nodes in cluster have password and the other don't
2. create a JedisCluster instance with password
3. send request to the cluster

#### Jedis version:
2.9.0
#### Redis version:
4.0.11
#### Java version:
java8

**Comment by gkorland** [comment]
@StillerRen sounds like a nice improvement, do you care to submit a PR?

**Comment by sazzad16** [comment]
@StillerRen Could you provide an actual stacktrace? From the code, all I can see that retries are limited to `JedisConnectionException` and `JedisRedirectionException`, none of which are `JedisDataException`. So `JedisDataException`s are supposed to be thrown right away.

**Comment by StillerRen** [comment]
@sazzad16 I think we need to do some special handling in this place: **redis.clients.util.Pool**
![image](https://user-images.githubusercontent.com/35724820/48812986-c2ca7100-ed6f-11e8-8bfc-ab227581410a.png)

when the instance of JedisCluster which has password tries to create a connection with a node without password, the exception JedisDataException: "ERR Client sent AUTH, but no password is set" would be reported.
but in the code, any exception would packaged into JedisConnectionException, then the class **redis.clients.jedis.JedisClusterCommand** would catch the JedisConnectionException and retry 5 times by default in the method "runWithRetries()". 

but the retry is useless, it must be failed that every time the instance of JedisCluster want to create the connection in this situation because of the error: "ERR Client sent AUTH, but no password is set" reported by redis.

**Comment by sazzad16** [comment]
@StillerRen Got it. Thanks!

**Comment by marcosnils** [comment]
@sazzad16 @StillerRen upon initialization JedisCluster doesn't use pools to authenticate to the cluster. Si if the node has an unset or incorrect password, it throws a JedisDataException as expected. 
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java#L37-L59

I wasn't able to reproduce this with a test. How are you trying this?

```java
  @Test(expected = JedisDataException.class)
  public void testDontRetryWithInvalidPassword() {
    Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
    jedisClusterNode.add(new HostAndPort("127.0.0.1", 7379));
    String clientName = "myAppName";
    JedisCluster jc = new JedisCluster(jedisClusterNode, DEFAULT_TIMEOUT, DEFAULT_TIMEOUT,
            DEFAULT_REDIRECTIONS, "invalid-ass", clientName, DEFAULT_CONFIG);
  }
```

The above test passes as expected.

**Comment by StillerRen** [comment]
@marcosnils create a instance of JedisCluster with password and try to connect to a cluster which some masters have password and the other not, the useless retry would happen when the command send to the node without password. 
it is okay that If the node has an unset or incorrect password, it throws a JedisDataException as expected. but in the first situation(unset password) the exception would be packaged into JedisConnectionException in the code I showed, it would case the useless retry.
