### ISSUE TITLE
SSLJedisTest

### ISSUE THREAD

**Issue by msaidireddy** [redis/jedis#1964]
### Expected behavior

I'm trying to build sample client code for Redis secured connection via SSL.
I'm using the test case file for the project - SSLJedisTest.java

### Actual behavior
I'm getting SSL errors:
redis.clients.jedis.exceptions.JedisConnectionException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at redis.clients.jedis.Connection.flush(Connection.java:308)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:235)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:103)
for all the methods

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Run SSLJedisTest java client after loading the client jks keystore cert
2. Redis DB should be enabled via SSL for all communications
3. Add the client cert - pem (base 64 code) on the DB cert key and save
I've the jks keystore with client certificate and enabled SSL on the redis db - enterprise redis cluster

### Redis / Jedis Configuration
Redis Secure SSL Client Connection - Java Jedis

#### Jedis version:
Latest - from git pull
#### Redis version:
Enterprise Redis Cluster - 5.2.2
#### Java version:
Java 1.8.x

**Comment by sazzad16** [comment]
@msaidireddy Did you have `stunnel` installed?

**Comment by sazzad16** [comment]
Closed due to inactivity.
