### ISSUE TITLE
Jedis connection in  block state

### ISSUE THREAD

**Issue by sagarsitap596** [redis/jedis#1974]
I have JedisCluster with 3 shards and 1 repilica each with below pool 

final JedisPoolConfig poolConfig = new JedisPoolConfig();
        poolConfig.setMaxTotal(200);
        poolConfig.setMaxIdle(200);
        poolConfig.setMinIdle(16);
        return poolConfig;

My application is making around 5-7 lacs of request per minute to redis (insert/update/delete key) over multiple threads (15-20). 

After some time one of jedis connection thread doesn't respond. When I trace down the thread trace I found :

java.util.concurrent.locks.abstractqueuedsynchronizer$conditionobject.await()

Is it because jedis connection pool is exausted?
Do I need to increase connection pool size ?

**Comment by sazzad16** [comment]
It seems to be related to:
- either #1920 which can be resolved by upgrading Jedis version
- or #1620 which can be resolved by a positive number in `setMaxWaitMillis` of pool config
