### ISSUE TITLE
Enhancement: JedisCluster should save the seed nodes

### ISSUE THREAD

**Issue by stillerrr** [redis/jedis#1985]
### Expected behavior

JedisCluster save the seed nodes and use the seed nodes to init or refresh the slot first.

### Actual behavior

JedisCluster don't save the seed nodes, if the cluster is not  available when JedisCluster init slots cache, the JedisClusterInfoCache's nodes map would be empty, and the JedisCluster object can not handle any request.

this function in JedisClusterConnectionHandler just use the seed nodes to create a temporary jedis object and get cluster nodes and slots information, but do not save the seed nodes
![image](https://user-images.githubusercontent.com/35724820/58534050-c4905800-821c-11e9-8629-0db1ad83b4c7.png)
if the cluster is not available, the initialization would be failed, the nodes map and the slots map would be empty in JedisClusterInfoCache 
![image](https://user-images.githubusercontent.com/35724820/58534326-8c3d4980-821d-11e9-88b8-0293bd13294c.png)
then all the requests would report the exception : JedisNoReachableClusterNodeException("No reachable node in cluster")
Even if the cluster returns to normal, it will always report the exception unless we recreate the JedisCluster object

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

1. create a JedisCluster object that the redis cluster is not available.
2. make the cluster normal and send requests.

**Comment by marcosnils** [comment]
Would you like to send a PR about how this would work?

**Comment by sazzad16** [comment]
Resolved by #2643
