### ISSUE TITLE
Support TLS connections in Sentinel mode

### ISSUE THREAD

**Issue by ae6rt** [redis/jedis#1987]
## Feature Request

Redis open source will [support TLS](https://github.com/antirez/redis/pull/4855) in the not distant future.  TLS support in the Sentinel will likely follow soon thereafter.

Please implement TLS support in Jedis to support Sentinel mode.  This would include not only connecting to the Sentinel over TLS, but also connecting to the sentinel-reported master over TLS.

#### Is your feature request related to a problem? Please describe

Financial services and enterprise users of Jedis, including those using Jedis by way of Spring Data Redis, are increasingly being asked to ensure all service traffic is encrypted via TLS.  

#### Describe alternatives you've considered

* removing calls to the Sentinel API in our code, migrating to the lower level Redis API for Redis Cluster (when it supports TLS - see link above) or Redis Enterprise.  This would be painful for the number of applications we have that program to the Sentinel API.
* stunnel and spiped, neither of which work well for how our services are deployed and maintained
* exotic IPSec solutions to encrypt traffic on the wire in lieu of first class TLS support in Sentinel mode

**Comment by gkorland** [comment]
@ae6rt I think the way to support it, without adding new dependencies to Jedis is by adding AddressResolver API

**Comment by gkorland** [comment]
@ae6rt is #2024 is that what you need?

**Comment by ae6rt** [comment]
@gkorland Yes, this seems to be the same feature request.

**Comment by gkorland** [comment]
@ae6rt so does that PR good enough? can you verify it's working on your environment?

**Comment by ae6rt** [comment]
@gkorland I need a few days to study my code and whether the code in #2024 slots into the way I build the connection factory.

**Comment by ae6rt** [comment]
I don't have a definitive answer for whether #2024 will work for me.  However, I can say that this is the nexus of how we define our sentinel-based connection factory:

```
JedisConnectionFactory factory = new JedisConnectionFactory(new RedisSentinelConfiguration(sentinel.master, sentinel.nodes), poolConfig);
```

I don't see obvious support in the #2024 PR for me sticking with this idiom.

```
