### ISSUE TITLE
Create an interface for 3rd party commands

### ISSUE THREAD

**Issue by DvirDukhan** [redis/jedis#2029]
create additional interfaces for 3ed party commands and general commands. this is a discussion following PR #2025

**Comment by maksymkovalenko** [comment]
PR #2025 is now merged in, please close this issue.

**Comment by sazzad16** [comment]
@maksymkovalenko This idea was generated after mentioned PR.

**Comment by sazzad16** [comment]
Issue details:

We may need interface(s) for the 3rd party commands. Here are reference methods:

1. https://github.com/xetorthio/jedis/blob/c581682bda779f6cfe7e9f1270705e4e1844cb01/src/main/java/redis/clients/jedis/BinaryJedis.java#L4054

1. https://github.com/xetorthio/jedis/blob/c581682bda779f6cfe7e9f1270705e4e1844cb01/src/main/java/redis/clients/jedis/BinaryJedis.java#L4049

1. https://github.com/xetorthio/jedis/blob/c581682bda779f6cfe7e9f1270705e4e1844cb01/src/main/java/redis/clients/jedis/Jedis.java#L3833

**Comment by gkorland** [comment]
@sazzad16 can we close this issue?

**Comment by sazzad16** [comment]
@gkorland I don't think so. Don't you think we should have such separate interface(s)?
