### ISSUE TITLE
Unable to connect to Redis cache when running behind a proxy server

### ISSUE THREAD

**Issue by kanistha** [redis/jedis#2037]
### Expected behavior

I would like to connect to Azure Redis cache through a proxy server. When I try to connect directly without any proxy it works. But when the jedis client is behind a proxy server it fails to connect to redis server. I am using Redis without ssl enable as of now. I would like to know how I can enable the proxy setting?

### Actual behavior

Currently I am getting java.net.SocketTimeoutException: Read timed out issue.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
 @Autowired
    private JedisConnectionFactory jedisConnectionFactory;

    @Bean
    RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(jedisConnectionFactory);
        template.setDefaultSerializer(new StringRedisSerializer());
        template.getConnectionFactory().getConnection().setConfig();
        return template;
    }
#### Jedis version:
   <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>2.9.3</version>
    </dependency>
#### Redis version:
spring-data-redis-1.8.9.RELEASE.jar
#### Java version:
1.8

**Comment by sureshkandimalla** [comment]
@kanistha - have you find any solution for this? we have the same issue

**Comment by sazzad16** [comment]
A new interface `HostAndPortMapper` is introduced which is available since Jedis 3.6.0-RC1. Hopefully it will be helpful in such cases.

**Comment by sazzad16** [comment]
Closed due to inactivity.
