### ISSUE TITLE
Jedis connection exhausted

### ISSUE THREAD

**Issue by cssutaria** [redis/jedis#2041]
hi 
i am using the Jedis Pool with the following configurations:
GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
poolConfig.setMaxTotal(120);
poolConfig.setMaxIdle(60);
poolConfig.setMinIdle(20);
poolConfig.setMinEvictableIdleTimeMillis(60*1000);
poolConfig.setTimeBetweenEvictionRunsMillis(5000);
poolConfig.setMaxWaitMillis(1000);

pool = new JedisSentinelPool("myMaster", config.getHostAddress(),poolConfig);

After around 4-5 hours we  start seeing the following message "Could not get a resource since the pool is exhausted" when doing a pool.getResource();

the jedis version we are using is 3.0.1.

**Comment by nagasai-praveen** [comment]
I am also facing same issue recently
