### ISSUE TITLE
JedisPubSub PING doesn't support (optional) message

### ISSUE THREAD

**Issue by lionello** [redis/jedis#2049]
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPubSub.java#L94

According to the Redis docs at https://redis.io/commands/ping PING takes an optional message, and indeed the Jedis client does have both overloads with and without the message parameter. The overload with message is missing from `JedisPubSub` and `BinaryJedisPubSub` however.

Also see #1279 and the original PR at #1255

**Comment by sazzad16** [comment]
Resolved by #2254
