### ISSUE TITLE
Getting JedisConnectionException: Could not get a resource from the pool When connecting to remote server

### ISSUE THREAD

**Issue by sohailzahid** [redis/jedis#2052]
I am trying to connect from a Java App running on Windows 10 using Jedis client to a remote Redis instance. My program fails with exception JedisConnectionException.

### Environment
- Redis version 5.x running on Ubuntu 19.04 in a VM
- Redis is configured to listen on a specific IP with a password and with protected mode set to on/yes.
- I am running my dev environment on a Windows 10 Pro machine.
- Jedis version is 3.1.0
- JDK is OpenJDK 11.0.4 on both Windows & Linux.

### What I have tried

- I have tested connecting to the remote (running on VM) Redis server using local redis-cli and was successful, confirming that I am able to access, connect and use the redis-server.
- I ran my test program from Netbeans 11.1 IDE running on another Linux VM on the same host with different IP and that was also a success.
- I ran my test program (100% same code) from Netbeans 11.1 IDE running on the host Windows 10 machine and the program failed to connect and threw the exception.

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Code Snippet 

pool = new JedisPool( config, "192.168.199.130", 6379, Protocol.DEFAULT_TIMEOUT,"foobar", Protocol.DEFAULT_DATABASE); 
Jedis jedis = pool.getResource(); // this statement throws the exception 
jedis.close();

JedisPool.getResource() works on Linux while same code fails from Windows.
Did anyone else run into this?
Any and all help appreciated. :-)

**Comment by josearaujo** [comment]
Do you find some solution for your problem?

**Comment by sohailzahid** [comment]
> Do you find some solution for your problem?

I did.  Thank you.

The issue was my environment configuration.  I maybe have made changes to the code but I do not recall for sure.

Appreciate you checking.  Thanks.

**Comment by josearaujo** [comment]
I was able to find a solution changing this
- REDIS_MASTER_HOST=127.0.0.1
      

thanks :)

**Comment by sazzad16** [comment]
Resolved
