### ISSUE TITLE
Sharding connection eviction

### ISSUE THREAD

**Issue by kalthas** [redis/jedis#2055]
### Expected behavior

Shard should be evicted when any of its containing connection (Jedis) is idle for the configured time, or eviction should based on connection level instead of Shard level

### Actual behavior

Shard is evicted only when the entire shard is idle for the configured time.

### Justification

Why the expected behavior? Consider a redis cluster comprised of 2 redis instances (R0, R1), and the server timeout is configured to 300s; client shard pool is configured the same, object idled for 300s will be evicted.

At t0 a new shard got created and R0 is connected, At t0 + 200s the shard is used again but this time R1 is connected. 
So at t0 + 200s, the shard's idle time is reset from 200s to 0, but R0 connection's idle time remains 200s, whereas R1's idle time is 0 since it's just got created.
At t0 + 400s, the shard's used again and this time R0 is needed. At the point of time, the shard's idle time is just 200s it's considered non idle by the pool. But actually connection for R0 is already 400s which is closed by server. 
Try to access this connection yields "Unexpected end of stream" Error.

**Comment by kalthas** [comment]
any update?

**Comment by sazzad16** [comment]
Sharding feature will be removed.
