### ISSUE TITLE
SlowLog miss client information with redis version 5.0.5.

### ISSUE THREAD

**Issue by AlbertYou** [redis/jedis#2076]
### Expected behavior

Output client information 

### Actual behavior

Output client information 

### Steps to reproduce:

1. SlowLog miss client information with redis version 5.0.5.

**Comment by sazzad16** [comment]
@AlbertYou Could you please elaborate the issue?

**Comment by AlbertYou** [comment]
redis 127.0.0.1:6379> slowlog get 2
1) 1) (integer) 14
   2) (integer) 1309448221
   3) (integer) 15
   4) 1) "ping"
2) 1) (integer) 13
   2) (integer) 1309448128
   3) (integer) 30
   4) 1) "slowlog"
      2) "get"
      3) "100"

**There are also optional fields emitted only by Redis 4.0 or greater:**

**5) "127.0.0.1:58217"
6) "worker-123"**

Every entry is composed of four (or six starting with Redis 4.0) fields:

    A unique progressive identifier for every slow log entry.
    The unix timestamp at which the logged command was processed.
    The amount of time needed for its execution, in microseconds.
    The array composing the arguments of the command.
    **Client IP address and port (4.0 only).
    Client name if set via the CLIENT SETNAME command (4.0 only).**

**Comment by AlbertYou** [comment]
Thanks!
