### ISSUE TITLE
has bug ?? xread  method block param is ：Long.MAX_VALUE no block !  use Integer.MAX_VALUE is block !

### ISSUE THREAD

**Issue by startjava** [redis/jedis#2080]
has bug ?? xread  method block param is ：Long.MAX_VALUE no block !  use Integer.MAX_VALUE is block !

**Comment by sazzad16** [comment]
According to [this comment](https://github.com/redis/jedis/issues/2277#issuecomment-735709282), block works even with Long.MAX_VALUE.
