### ISSUE TITLE
jedisCluster不支持批量读写有解决方案么

### ISSUE THREAD

**Issue by chenbinglong** [redis/jedis#2091]
### Expected behavior

jediscluster支持批量读写

### Actual behavior

jediscluster目前不支持批量读写 mget满足不了

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by startjava** [comment]
i know it ..not support!

**Comment by mekingshow** [comment]
+1

**Comment by sazzad16** [comment]
Resolved by https://github.com/redis/jedis/commit/858c8051301854e8343eef66aa68c6b9dab1c328 

Introduced ClusterPipeline
