### ISSUE TITLE
JedisClusterCommands doesn't implement objectEncoding ?

### ISSUE THREAD

**Issue by mjmanav4** [redis/jedis#2099]
There is no support for objectEncoding in JedisCluster  ... can u please add one

**Comment by startjava** [comment]
i know ...

There are other apis that are not implemented in Jedis.

**Comment by startjava** [comment]
Jedis developers should collaborate to add incomplete APIs

**Comment by gkorland** [comment]
> i know ...
> 
> There are other apis that are not implemented in Jedis.

which APIs are you missing?

**Comment by gkorland** [comment]
> Jedis developers should collaborate to add incomplete APIs

You're more than welcome to send a PR for missing APIs

**Comment by MichalCho** [comment]
I can have a look at it

**Comment by sazzad16** [comment]
Resolved by https://github.com/redis/jedis/commit/858c8051301854e8343eef66aa68c6b9dab1c328
