### ISSUE TITLE
Add support for RESP3

### ISSUE THREAD

**Issue by gkorland** [redis/jedis#2103]
https://gist.github.com/antirez/2bc68a9e9e45395e297d288453d5d54c

**Comment by startjava** [comment]
@sazzad16  what time release has hello method version???  this 2022 year!! thank you !

**Comment by sazzad16** [comment]
@startjava yes, this 2022 year!! we still waiting for your PR!!! thank you!

**Comment by chayim** [comment]
https://github.com/redis/jedis/issues/2103

**Comment by chayim** [comment]
Remember to consider https://github.com/redis/redis-specifications/pull/12

**Comment by sazzad16** [comment]
- [ ] UnifiedJedis - Add an option to set the protocol 
- [ ] URI - protocol version in uri 
- [ ] Unix Socket - check if unix socket works with RESP3 
- [ ] HELLO command 
- [ ] HELLO command extension with optional arguments 
- [ ] RESP3 protocol parser 
- [ ] README update with RESP3 config 
- [ ] Investigate where to make the changes 
- [ ] Make the changes

**Comment by sazzad16** [comment]
Available since version [5.0.0](https://github.com/redis/jedis/releases/tag/v5.0.0).
