### ISSUE TITLE
Add support for localcache (Client-side caching)

### ISSUE THREAD

**Issue by gkorland** [redis/jedis#2104]
https://redis.io/topics/client-side-caching
depends on #2103

**Comment by MichalCho** [comment]
That looks like interesting feature to work on. I think I could be interested in crafting a PR. Are you going to work on #2103 @gkorland?

**Comment by gkorland** [comment]
You are more than welcome to work on this feature @MichalCho, I didn't plan to work on this till April.

**Comment by MichalCho** [comment]
> You are more than welcome to work on this feature @MichalCho, I didn't plan to work on this till April.

Sorry @gkorland, just to double check - you meant that you are not going to work on #2103 or #2104? :)

**Comment by gkorland** [comment]
@MichalCho not in the near future

**Comment by gkorland** [comment]
duplicate #2220

**Comment by bebers22** [comment]
Are we there yet?
