### ISSUE TITLE
please implements ZAddParams.incr() method!

### ISSUE THREAD

**Issue by startjava** [redis/jedis#2114]
please implements ZAddParams.incr() method!

**Comment by dengliming** [comment]
You should use ZIncrByParams.

**Comment by dengliming** [comment]
@sazzad16 Seems we can close this one. : )

**Comment by sazzad16** [comment]
@dengliming I'm not sure. Redis has INCR option in ZADD command. So we should keep it under consideration.

And it is not possible to pass ZIncrByParams in zadd(...) method. So I may not close this issue without resolution :|

**Comment by dengliming** [comment]
Thanks. you were totally right. Redis doesn't have multi parameters for ZINCRBY.

**Comment by dengliming** [comment]
@sazzad16 But notice this mention about `INCR`.

_INCR: When this option is specified ZADD acts like ZINCRBY. `Only one score-element pair can be specified in this mode.`_

So  I suggest using `zincrby` can resolve this issue. WDYT?

**Comment by sazzad16** [comment]
@dengliming 

> I suggest using `zincrby` can resolve this issue.

This logic applies to Redis as much as it applies to Jedis. There must be reasons that Redis have that option. And as long as Redis has it we shouldn't completely disregard it.
