### ISSUE TITLE
please rewrite convertHost method

### ISSUE THREAD

**Issue by magic5650** [redis/jedis#2129]
### Expected behavior
we have a redis cluster in aws elasticache.it has multi endpoint. our service should be connect different endpoint when service restart.

### Actual behavior
in our service node A, it alway connected redis cluster endpoint B. always.

### Steps to reproduce:
we found jedis getaddress use InetAddress.getByName(hostname),it always return same ip(if dns server return ip list).it happend in ipv6 environment.if we close ipv6,it's not problem.
we found the result.
https://xhao.io/2018/09/getaddrinfo/
```
import java.net.InetAddress;
import java.util.Random;
public class JavaInetAddressGetByAddressExample1_1 {
  public static void main(String[] args) {
    try {
      InetAddress[] ia = InetAddress.getAllByName("buss-subsribe-main.l5pqk4.clustercfg.apse1.cache.amazonaws.com");
      for(int i = 0; i< ia.length; i++){
          System.out.println(ia[i].getHostAddress());
      }
      System.out.println("-------------------------------------------");
      int a = new Random().nextInt(ia.length);
      InetAddress randomip = ia[a];
      System.out.println(randomip.getHostAddress());
      System.out.println("-------------------------------------------");
      InetAddress ip1=InetAddress.getByName("buss-subsribe-main.l5pqk4.clustercfg.apse1.cache.amazonaws.com");
      System.out.println(ip1.getHostAddress());
    } catch (Exception ex) {
      System.err.println(ex);
    }
  }
}
```
so we can use Random() to get ipadddr as above.
run in:
https://compiler.javatpoint.com/opr/test.jsp?filename=JavaInetAddressGetByAddressExample1_1
#### Java version:
JDK 8

**Comment by gkorland** [comment]
@magic5650 can you please submit a PR so can review it?

**Comment by sazzad16** [comment]
@gkorland FYI #1773
