### ISSUE TITLE
Active connections will not be released

### ISSUE THREAD

**Issue by asdxiaoqex** [redis/jedis#2136]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.jedisPool.getNumActive()
The number of connections that will increase by dozens every day will not be released. I checked the use of all connection pools and confirmed that the close method was used. Yesterday, when the database was special card, the number of connections was increased by 300+. What would cause the connection to fail to be recovered
![image](https://user-images.githubusercontent.com/50010140/74340910-cf5a3f80-4de1-11ea-9885-3d86e575cf8e.png)
![image](https://user-images.githubusercontent.com/50010140/74340924-d5502080-4de1-11ea-88da-bee8e7410c39.png)
![image](https://user-images.githubusercontent.com/50010140/74340990-f31d8580-4de1-11ea-9902-d380f5e75727.png)
why？

**Comment by gkorland** [comment]
@asdxiaoqex can you please try with newer version? couple of leaks were fixed in the last year.
BTW, Jedis implements Closeable so you can just user try-with-resources block

**Comment by asdxiaoqex** [comment]
What is the most stable version so far?

**Comment by sazzad16** [comment]
@asdxiaoqex Do you have any update?
