### ISSUE TITLE
Jedispool is always opening new connections

### ISSUE THREAD

**Issue by trebonius0** [redis/jedis#2142]
Hey there, 

I've been investigating an issue where Jedis is always opening tons of new connections to Redis (5k/s). I've not been able to understand it. I'm not sure if I'm doing something wrong or if this is a bug. 

So, I create at the very beginning of my program a JedisPool with a very simple jedisPoolConfig: 
```
JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
jedisPoolConfig.setMaxTotal(500);
JedisPool jedisPool = new JedisPool(jedisPoolConfig, redisUrl, redisPort, 86400 * 1000, null, databaseId);
```

This jedispool is then used everywhere in the program. It's only created once during the whole process lifetime. And there is only one process like this at any single time

Then, every single time I use Jedis, I do
```
try(Jedis jedis = this.jedisPool.getResource()){
// Do something
}
```

I'm sending around 30k requests per second to my redis server. 

### Expected behavior
When monitoring the server, I would expected so see a number of clients up to 500 and a number of connections per second close to 0 (total_connections_received almost constant) , as the connections are from the pool. 

### Actual behavior
I have ~100 connections (ok), but I also have **5000+ connections per second**. Also, I did a `MONITOR `on redis and I didn't find any `QUIT `command. 

#### Jedis version:
Jedis 3.0.1

#### Redis version:
1 redis server. Redis 5.0.7 - maxclients set up to 10k

#### Java version:
Java 8

Thanksf for your help guys

**Comment by atealxt** [comment]
@trebonius0  
`MONITOR` not log for `QUIT`
https://redis.io/commands/monitor#commands-not-logged-by-monitor

**Comment by trebonius0** [comment]
Ok
But I'm pretty sure i never stop a connection. I'm always using the pattern highlighted before. is there anything wrong with this pattern ?

**Comment by gkorland** [comment]
@trebonius0 any chance you can add here a full recreation or add a test?
BTW, did you try with a newer version of jedis?

**Comment by yangbodong22011** [comment]
> try(Jedis jedis = this.jedisPool.getResource()){
> // Do something
> }

@trebonius0 Have you ever called `jedis.close()`?

**Comment by sazzad16** [comment]
Closed due to inactivity.
