### ISSUE TITLE
Redis-cluster failures 

### ISSUE THREAD

**Issue by chandresh-pancholi** [redis/jedis#2147]
### Expected behavior

Expecting it to work as stand-alone redis was working for us. 

### Actual behavior
We moved Redis setup to redis-cluster and we started observing failures in below orders
```
1. redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

2. redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

3. Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Too many open files
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
```
JedisCluster jc = new JedisCluster(hostAndPorts(), 5000, 5000, 3, new JedisPoolConfig());
```
#### Jedis version:
```
compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-redis', version: '2.0.4.RELEASE'
compile group: 'redis.clients', name: 'jedis', version: '2.9.0'
```

**Comment by yangbodong22011** [comment]
@chandresh-pancholi Can you provide your full exception stack?

**Comment by sazzad16** [comment]
Closed due to inactivity.
