### ISSUE TITLE
can use default user ??

### ISSUE THREAD

**Issue by startjava** [redis/jedis#2168]
JedisPool pool = new JedisPool(new JedisPoolConfig(), "192.168.1.108", 6379, 5000, "accp");

Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

can use default user ??
Keep code compatible

**Comment by startjava** [comment]
version is redis6.0 rc2 
jedis-3.3.0-SNAPSHOT.jar new version

**Comment by startjava** [comment]
class JedisFactory implements PooledObjectFactory<Jedis> {
  private final AtomicReference<HostAndPort> hostAndPort = new AtomicReference<HostAndPort>();
  private final int connectionTimeout;
  private final int soTimeout;
  private final String user="default";           //this ???

**Comment by sazzad16** [comment]
@startjava You are sending password from Jedis (JedisPool) but there is no password set for default user in your Redis instance.
