### ISSUE TITLE
Unexpected end of stream after connectivity to Redis lost

### ISSUE THREAD

**Issue by aalaran** [redis/jedis#2176]
### Expected behavior

When connectivity is lost to a Redis database, it is expected that connections recover after the database comes back up.

This is while using RedisTemplate.setEnableTransactionSupport.  While this is Spring, we are exploring to see if there's something on the Jedis side as well.

### Actual behavior

Some connections do not recover

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

1. git clone https://gitlab.com/deji.alaran/redis-java-clients.git
2. docker-compose up -d --build
3. Go to http://localhost/?folder=/home/coder/project to open VSCode
4. Open a terminal (3 bars on top left > Terminal > New Terminal)
5. Type "mvn spring-boot:run"
6. Wait for ".... INFO ... --- [  restartedMain] c.r.e.redis.RedisClientsApplication      : Started RedisClientsApplication in ...)"
7. Go to http://localhost/locust
8. Input in a reasonable number (maybe 10 for users to simulate and 2 for hatch rate)
9. Click "Start swarming"
10. In your VSCode terminal window, you should see something like:
...
Retrieving key using template from org.springframework.data.redis.connection.jedis.JedisConnectionFactory@6f4daf14
getting key
Retrieving key using template from org.springframework.data.redis.connection.jedis.JedisConnectionFactory@6f4daf14
getting key
...
11. Stop Redis (docker stop redis-java-clients_redis_1)
In your VSCode window, you should see something like the below repeating continuously:
...
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199) ~[jedis-2.9.3.jar:na]
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.9.3.jar:na]
        at redis.clients.jedis.Protocol.process(Protocol.java:153) ~[jedis-2.9.3.jar:na]    
...
12. Start Redis back up (docker start redis-java-clients_redis_1)
In your VSCode window, you should see something like:
...
Retrieving key using template from org.springframework.data.redis.connection.jedis.JedisConnectionFactory@6f4daf14
getting key
Retrieving key using template from org.springframework.data.redis.connection.jedis.JedisConnectionFactory@6f4daf14
getting key
...
13. This shows the connections recover
14. Now go to com.redislabs.examples.redis.RedisDataConfig in VSCode
15. In the createTemplate method, add
template.setEnableTransactionSupport(true);
before returning the template.
16. Stop spring-boot
17. Repeat from step 5 to step 12.
18. You'll notice the messages being shown after step 12 are still the exceptions, showing the connections don't recover

### Redis / Jedis Configuration
app.redis.cache-expiration-minutes=15
app.jedis.pool.max-total=100 
app.jedis.pool.max-wait-millis=15000
app.jedis.pool.max-idle=25
app.jedis.pool.min-idle=0
app.jedis.pool.time-between-eviction-runs-millis=30000

#### Jedis version:
2.9.3

#### Redis version:
5.0.8

#### Java version:
11

**Comment by gkorland** [comment]
It seems related to the way the spring-data-redis works, it binds the connection to the specific transaction. Which means you won't get a new connection even when the server is back.
```Java
			if (enableTransactionSupport) {
				// only bind resources in case of potential transaction synchronization
				conn = RedisConnectionUtils.bindConnection(factory, enableTransactionSupport);
			} else {
				conn = RedisConnectionUtils.getConnection(factory);
			}
```

**Comment by sazzad16** [comment]
Closed due to inactivity.
