### ISSUE TITLE
No way to apply AbandonedConfig in JedisPool

### ISSUE THREAD

**Issue by pankajydv** [redis/jedis#2197]
### Expected behavior
Jedis Pool is built over GenericObjectPool from apache commons-pool2. The GenericObjectPool can be configured to detect and remove "abandoned" objects, i.e. objects that have been checked out of the pool but neither used nor returned before the configured removeAbandonedTimeout.

### Actual behavior

There is no way in JedisPool or JedisPoolConfig to configure org.apache.commons.pool2.impl.AbandonedConfig in the underlying jedis pool.

### Steps to reproduce:
We have observed under high load the abandoned connections cause JedisExhaustedPoolException exception and we highly doubt that these are the abandoned connections, as we are releasing all the connections back to pool in a finally block using **jedis.close()** call, evertime we are using it. We get this exception once every 10-12 days in production environment, we are performing around 0.2m operations every minute on a redis setup consisting of 3 servers.

#### Jedis version:
3.1.0

#### Redis version:
redis_version:5.0.2

#### Java version:
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mod

**Comment by pankajydv** [comment]
Any comments on this would be appreciated.

**Comment by venukbh** [comment]
@pankajydv  THis was already reported here https://github.com/redis/jedis/issues/2050 and also a PR was raised https://github.com/redis/jedis/pull/2054 .. but did not make it to merge...
