### ISSUE TITLE
How do I change Test run env?

### ISSUE THREAD

**Issue by gudufengE** [redis/jedis#2211]
### Expected behavior

I edited the HostAndPortUtil.class,and replaceall localhost to myip.
I hope run Test method at once.

### Actual behavior

Failed connecting to host localhost:6379

### Steps to reproduce:

1. I edited the HostAndPortUtil.class,and replaceall localhost to myip.
2. Run test method

### Redis / Jedis Configuration
all default

#### Jedis version:
In jedis resource
All default

#### Redis version:
redis version 5.05
#### Java version:
java 1.8

**Comment by yangbodong22011** [comment]
@gudufengE try this:
```
cd /tmp
git clone https://github.com/redis/redis.git
cd redis; make -j;
cd src; REDIS_PATH=`pwd`

cd /tmp
git clone https://github.com/redis/jedis.git
cd jedis
export PATH=$PATH:$REDIS_PATH
make deploy
make stop
```

**Comment by sazzad16** [comment]
Closed due to inactivity.
