### ISSUE TITLE
Instantite JedisPool in a more concise way

### ISSUE THREAD

**Issue by 17hao** [redis/jedis#2212]
### Expected behavior
Create `JedisPool` instance in a more concise way:
`JedisPool redisCli = new JedisPool(host, port, password);`

### Actual behavior

`JedisPool redisCli = new JedisPool(GenericObjectPoolConfig, host, port, timeout, password);`

### Steps to reproduce:

Creating a `JedisPool` instance.

### Redis / Jedis Configuration
default configuration
#### Jedis version:
2.9.0
#### Redis version:
6.0.4
#### Java version:
1.8.0_201

**Comment by gkorland** [comment]
@17hao I'm not sure I get the issue do you want another constructor with less arguments?

**Comment by 17hao** [comment]
@gkorland  yes I want another constructor with less arguments. 
Do you think it is necessary to add a constructor to JedisPool？ Can I create a PR if necessary？

**Comment by gkorland** [comment]
You are welcome to create a PR

**Comment by sazzad16** [comment]
@17hao Since jedis-3.4.1, there is a new constructor:

    JedisPool(final String host, int port, String user, final String password)

After introduction of ACL in Redis, we are trying to avoid methods/constructors with only password (without user).

**Comment by sazzad16** [comment]
Closing this issue in favor of following constructors:
- `JedisPool(final String host, int port, String user, final String password)` https://github.com/redis/jedis/blob/1a9de794847c6f7bfda51249225ead066f9f4387/src/main/java/redis/clients/jedis/JedisPool.java#L79-L81
- `JedisPool(final GenericObjectPoolConfig poolConfig, final String host, int port, String user, final String password)` https://github.com/redis/jedis/blob/1a9de794847c6f7bfda51249225ead066f9f4387/src/main/java/redis/clients/jedis/JedisPool.java#L83-L86
