### ISSUE TITLE
Monitor the pool

### ISSUE THREAD

**Issue by CoderLan0668** [redis/jedis#2218]
Some DataSource,  for example HikariCP, they provide metrics and can be watched well.

Is there any way to acheive this goal in Jedis?

**Comment by dengliming** [comment]
Something like `activeNum`、`IdleNum ` in JedisPool?

**Comment by abhisheksurve45** [comment]
Is there anything in `JedisPoolConfig` , basically want to monitor sentinel configuration

**Comment by sazzad16** [comment]
Could be related to #2521 which is available since Jedis 4.0.0

**Comment by sazzad16** [comment]
Closed due to inactivity.
