### ISSUE TITLE
Redis streams implementations will indefinitely block if Redis server doesn't send a response

### ISSUE THREAD

**Issue by johnrengelman** [redis/jedis#2219]
### Expected behavior

The Redis stream commands such as `xread` return an error if the Redis server doesn't send a response of any kind. This can happen due to network or server errors (such as if the return path of a network connection is broken).

### Actual behavior

Command blocks indefinitely.
This is a result of setting the client socket SOTimeout to infinite in this PR - https://github.com/xetorthio/jedis/pull/2059
### Steps to reproduce:

Start a listening socket for Redis (eg `nc -l 6379`). 
Connect and send a `xread` command.

Regardless of the `block` value, the command with hang indefinitely trying to read data from the socket.

#### Jedis version:
3.3.0

#### Redis version:
5.0.9

#### Java version:
11

**Comment by sazzad16** [comment]
Hi @johnrengelman, could you please check if this issue resolved in Jedis 3.4.0 by setting infiniteSocketTimeout?
