### ISSUE TITLE
open jkd13 redis subscribe error, java.lang.NoClassDefFoundError: jdk/nashorn/internal/ir/debug/ObjectSizeCalculator

### ISSUE THREAD

**Issue by kivn2014** [redis/jedis#2224]
open jdk13 
redis subscribe error, java.lang.NoClassDefFoundError: jdk/nashorn/internal/ir/debug/ObjectSizeCalculator

#### redis version:
redis 5.0.9
#### Jedis version:
jedis2.9
#### Java version:
openjdk13

**Comment by sazzad16** [comment]
Jedis 2.9.x is unlikely to get an update.

Sorry for being late.
