### ISSUE TITLE
in cluster if kill a master redis,then use jediscluster connect cluster while get a MaxAttemptsException

### ISSUE THREAD

**Issue by vince2000** [redis/jedis#2226]
Expected behavior
In redis cluster, if master was down ,jediscluster can get slave connection 

Actual behavior
get a MaxAttemptsException

Steps to reproduce:
use jediscluster connect rediscluster,  shutdown a master node, then still use the jediscluster to connect  rediscluster

**Comment by madalion** [comment]
hi, I also have this problem， have you resolved it?

**Comment by sazzad16** [comment]
@vince2000 This is how it is. It takes some time to renew the cluster configuration. Feel free to suggest any better approach for cluster renewal. Thanks!
