### ISSUE TITLE
JedisClusterMaxRedirectionsException: Too many Cluster redirections?

### ISSUE THREAD

**Issue by david6522** [redis/jedis#2235]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Java version:
![image](https://user-images.githubusercontent.com/33677926/91253168-d222ed80-e791-11ea-87db-bc8b62f0a41c.png)

our application always meet this problem, but i can not solve it ,can you help me , redis config file bind  0.0.0.0

**Comment by sazzad16** [comment]
@david6522 The way this issue is written is really not helpful to find out the problem, if there is any. Please add stacktrace specific to Jedis in textual format.
