### ISSUE TITLE
[QUESTION] JedisConnectionException: java.net.SocketException: Broken pipe

### ISSUE THREAD

**Issue by bjj520719** [redis/jedis#2250]
Hi,

We had an issue about Jedis 2.8.2 API writing。The size of the write data is 100k。

**redis_version**:2.8.19
**redis config**
timeout 0

**jedis config**:
timeout: 30000
pool:
      max-idle: 1000
      min-idle: 200
      max-total: 1000
      max-wait-millis: 30000
      time-between-eviction-runs-millis: 30000
      soft-min-evictable-idle-time-millis: 30000
      test-on-borrow: false

**Error msg：**
org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Broken pipe; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe

Is the server actively disconnected or the connection from the connection pool invalid?

**Comment by yangbodong22011** [comment]
@bjj520719 Hello, Can you describe the background of the problem, or provide the code to reproduce it?

**Comment by bjj520719** [comment]
> @bjj520719 Hello, Can you describe the background of the problem, or provide the code to reproduce it?

Hello，We have a scene like this Kafka bulk consumption writes data to redis，Due to the frequent reading and writing of redis by 100000 active users every day, this problem has not recurred in the test environment，We're still looking for ways to reproduce it。
