### ISSUE TITLE
Jedis should close the connection to redis friendly

### ISSUE THREAD

**Issue by chimney-lee** [redis/jedis#2252]
### Expected behavior

With the config set socket.setSoLinger(true, 0)；The jedis will close the connection by send RST message but not FIN-ACK FIN-ACK , which is an ungraceful  way to release the connection; 

### Actual behavior

we should close the connection  friendly by send FIN-ACK,FIN-ACK

### Steps to reproduce:

tcpdump would catch the RST message

#### Java version:

https://github.com/xetorthio/jedis/pull/2251

**Comment by chimney-lee** [comment]
@sazzad16  Look forward some comments on this issue

**Comment by sazzad16** [comment]
Closed due to https://github.com/redis/jedis/pull/2251#issuecomment-801750894 
 > Config setSoLinger(true) for fast connection recycle, i am afraid, if not config this will cause too many connection stay in time_wait state, finally, will cause port exhausted.
