### ISSUE TITLE
BUGS when using eval or evalsha in pipeline

### ISSUE THREAD

**Issue by minisancy** [redis/jedis#2256]
### Expected behavior

MultiKeyPipelineBase.java

 @Override
  public Response<Object> eval(String script, int keyCount, String... params) {
    getClient(script).eval(script, keyCount, params);
    return getResponse(BuilderFactory.EVAL_RESULT);
  }

i suggest using get(parasm[0]) when keyCount>0 instead getClient(script)
for getClient(script) would not get a corrent client

**Comment by sazzad16** [comment]
@minisancy Would you like to submit a PR, resolving not only this but preferably including all other similar issues?

**Comment by minisancy** [comment]
> @minisancy Would you like to submit a PR, resolving not only this but preferably including all other similar issues?

I hava submited, please check it

**Comment by minisancy** [comment]
> @minisancy Would you like to submit a PR, resolving not only this but preferably including all other similar issues?

check failed，but i have just modified eval and evalsha..... seems strange...

**Comment by sazzad16** [comment]
Resolved by #2693

**Comment by minisancy** [comment]
您好，来信已收到！谢谢！
