### ISSUE TITLE
xadd skip maxlen for binary api

### ISSUE THREAD

**Issue by SevereOverfl0w** [redis/jedis#2262]
### Expected behavior

xadd is available without requiring maxlen and approximate.

### Actual behavior

https://github.com/xetorthio/jedis/blob/ab36b3638181d20eb9ad971109ffcc9aeef8efb3/src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java only contains a single arity for xadd, which requires the maxlen to be provided.  Higher level wrapper works around this by hardcoding Long/MAX_VALUE which works but is a bit of a cheat (Maybe some workloads could even exceed this?).

The pipeline wrapper does provide both arities of xadd though: https://github.com/xetorthio/jedis/blob/813573898a95e1360632f9ba4f3968b9de8e6acb/src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java

**Comment by dengliming** [comment]
I think it is resolved by [https://github.com/redis/jedis/pull/2466](https://github.com/redis/jedis/pull/2466) @sazzad16
