### ISSUE TITLE
Document: Version Compatibility Table

### ISSUE THREAD

**Issue by rkimsb2** [redis/jedis#2267]
Is there any plans to supply version compatibility table between jedis and redis on document or wiki?

**Comment by yangbodong22011** [comment]
Maybe we need to add `@since` tag on java doc? @sazzad16

**Comment by sazzad16** [comment]
@yangbodong22011 The OP is asking about compatibilities between Redis versions and Jedis versions. `@since` tag won't do.

**Comment by yangbodong22011** [comment]
@sazzad16 ohh, thanks for your clarification.

**Comment by compensator** [comment]
I'm upgrading the libs of an out of date prototype Spring application and upon seeking a compatibility matrix for Jedis and Redis Server, I arrived here. I guess I'll have to go into a config-test cycle. Such is life.
