### ISSUE TITLE
Jedis#eval with the specified timeout

### ISSUE THREAD

**Issue by Huan9** [redis/jedis#2270]
We observe the same issue as described in a closed thread: https://github.com/redis/jedis/issues/1147

seem like `at redis.clients.jedis.Jedis.getEvalResult(Jedis.java:2642) ` never return after more than 5 mins sometimes(pretty rare, but when it happen cause bad issue). Our redis server had the default `lua-time-limit` set to 5 seconds and our Lua script is pretty light weight and should not take more than 1 second.

Is that possible to bring in the fix for that issue: https://github.com/redis/jedis/pull/1148 ?

**Comment by sazzad16** [comment]
Dupe of #1147 

#1147 is reopened

**Comment by sazzad16** [comment]
Resolved by #2408
