### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [redis/jedis#2276]
Hi all,
our bug scanner has reported a NPE bug.

The variable [result](https://github.com/redis/jedis/blob/d7aba13a8b65e66dedc01c51b73e3794cbe68a62/src/main/java/redis/clients/jedis/Jedis.java#L3802) may be null since the method [getBulkReply()](https://github.com/redis/jedis/blob/d7aba13a8b65e66dedc01c51b73e3794cbe68a62/src/main/java/redis/clients/jedis/Connection.java#L209) may return null. When the `result` is passed to the method [StreamEntryID()](https://github.com/redis/jedis/blob/d7aba13a8b65e66dedc01c51b73e3794cbe68a62/src/main/java/redis/clients/jedis/Jedis.java#L3803) as a parameter, a NPE bug may take place in [StreamEntryID()](https://github.com/redis/jedis/blob/d7aba13a8b65e66dedc01c51b73e3794cbe68a62/src/main/java/redis/clients/jedis/StreamEntryID.java#L69).

Thanks.

**Comment by sazzad16** [comment]
@JulyChen728 Thank you for your interest in Jedis. Please be informed that a general bug tracking algorithm will not be applicable in this project. It is a Redis client and it strongly depends on how Redis (commands) works. I.e. for your specific case you can check Redis XADD command.
