### ISSUE TITLE
xread with block=0 doesn't block

### ISSUE THREAD

**Issue by awaizman1** [redis/jedis#2277]
### Expected behavior

According to [redis documentation](https://redis.io/topics/streams-intro) when passing block=0 to xread command, the operation should block forever (until has data to read).

From the documentation:
> "... I specified the new BLOCK option with a timeout of 0 milliseconds (that means to never timeout)"

In Jedis, when I pass block=0 it seems like the BLOCK param is omitted at all from the sent command thus the xread command won't block at all.

**BinaryClient.java:**
```java
public void xread(final int count, final long block, final Map<byte[], byte[]> streams) {
    ...
    if(block > 0) {
        params[streamsIndex++] = Keyword.BLOCK.raw;
        params[streamsIndex++] = toByteArray(block);
    }
    ...
```

I also validate this behavior with the python client and redis-cli and indeed block=0 means block forever.

I guess the block argument to Jedis.xread should be optional, when provided it should be passed to redis for any value >= 0 (negative value are not allowed)

#### Java version: 11

Thanks.

**Comment by sazzad16** [comment]
@awaizman1 Thank you for reporting. Actually when it was implemented, block=0 wasn't supported. So the developer took the chance and used block=0 to represent the absence of block param.

@gkorland PING!

**Comment by UglyBarnacle** [comment]
yeah, we are "suffering" from the same behaviour. after going back to use jedis (we used an own implementation of the streams when it was not available) - we noticed a spike in CPU usage when using xread, only to find this exact piece of code.
as workaround, we did set the value to Long.MAX_VALUE.

**Comment by sazzad16** [comment]
@awaizman1 @UglyBarnacle Please use `block=Long.MAX_VALUE` for the time being.
