### ISSUE TITLE
About the performance of the transaction after jedis 3.0.0

### ISSUE THREAD

**Issue by yyxjcc** [redis/jedis#2291]
Hello, I found that since jedis version 3.0.0 (precisely from PR #511), the way transactions are handled has changed.

From the perspective of command interaction:

before:

> jedis multi command_1 comand_2 ... command_n ---> redis
> redis +OK +QUEUED +QUEUED ... +QUEUED ---> jedis
> jedis exec ---> redis
> redis +OK ---> jedis

now:

> jedis multi ---> redis
> redis +OK ---> jedis
> jedis comand_1 comand_2 ... command_n ---> redis
> redis +QUEUED +QUEUED ... +QUEUED ----> jedis
> jedis exec ----> redis
> redis +OK ----> jedis

After preliminary testing, the performance comparison is as follows:

> Total number of transactions executed: 100000
> Number of commands in the transaction: 2
> redis version: 4.0.6
> Total time required (ms):
>   Previous version: **3701**
>   Current version: **8779**

Test code:

```

public void test() {

    Jedis jedis = new Jedis("127.0.0.1", 6379);

    String key = "k1";

    Map<String, String> map = new HashMap<>();

    map.put("f1", "v1");

    map.put("f2", "v2");

    map.put("f3", "v3");

    long startTime = System.nanoTime();

    for (int i = 0; i < 100000; i++) {

      Transaction multi = jedis.multi();

      multi.hmset(key, map);

      multi.pexpire(key, 10000);

      multi.exec();

    }

    System.out.println("total time: " + TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startTime));

 }

```

In summary, the revised jedis is more worrying in terms of transaction execution performance (especially when the number of commands to be executed in a transaction is small). I wonder if you have any good way to solve it? Or if you already have an optimization method in this area, please tell me how to use it, thank you very much. :)

**Comment by sazzad16** [comment]
@yyxjcc #511 was included to bring more stability. What you're trying to achieve is still achievable through `Pipeline`.

**Comment by sazzad16** [comment]
Resolved by https://github.com/redis/jedis/commit/858c8051301854e8343eef66aa68c6b9dab1c328
