### ISSUE TITLE
Attempting to read from a broken connection

### ISSUE THREAD

**Issue by suryavtkt** [redis/jedis#2298]
### Expected behavior

Data should read properly without any exception

### Actual behavior

org.springframework.data.redis.RedisConnectionFailureException: Attempting to read from a broken connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:65)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:42)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:135)
	at org.springframework.data.redis.connection.jedis.JedisKeyCommands.expire(JedisKeyCommands.java:341)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.expire(DefaultedRedisConnection.java:139)
	at org.springframework.data.redis.core.RedisTemplate.lambda$expire$8(RedisTemplate.java:804)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.RedisTemplate.expire(RedisTemplate.java:799)
	at org.springframework.data.redis.core.DefaultBoundKeyOperations.expire(DefaultBoundKeyOperations.java:53)

### Steps to reproduce:

We are facing this error while upgrading the jedis/redis versions 

### Redis / Jedis Configuration
efi.redis.host=localhost
efi.redis.port=6379
efi.redis.connectionPoolSize=12

#### Jedis version:
3.2.0
#### Redis version:
6.0.8
#### Java version:
1.8

**Comment by sazzad16** [comment]
@suryavtkt 
Just `redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection` is really not helpful to solve an apparent issue, if there is any.

Nevertheless, in general, if you have a connection somehow broken, you should start using a new one. If you don't this by yourself, JedisPool does that automatically.

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by shawfifty** [comment]
> @suryavtkt Just `redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection` is really not helpful to solve an apparent issue, if there is any.
> 
> Nevertheless, in general, if you have a connection somehow broken, you should start using a new one. If you don't this by yourself, JedisPool does that automatically.

Do you mean that a new jedis should be created when the original one is broken for some exception, like read timeout?

**Comment by sazzad16** [comment]
@shawfifty Ideally, yes. Because anything could be pending in buffers which could cause uncontrolled behavior. It's just safer to create a new Jedis object.

**Comment by shawfifty** [comment]
> 

That's what I recommended to my leader. But he tends to reset  the flag `broken` to `false` when use `jedis.close()` in resource code for the reason that when using `jedis.connect()`,it will create a new socket and connect to redis . Can buffers affect the use of the new one ? Or you point is caution is the parent of safety.

**Comment by shawfifty** [comment]
> 

That's what I recommended to my leader. But he tends to reset  the flag `broken` to `false` when use `jedis.close()` in resource code for the reason that when using `jedis.connect()`,it will create a new socket and connect to redis . Can buffers affect the use of the new one ? Or you point is caution is the parent of safety.

**Comment by shawfifty** [comment]
> @shawfifty Ideally, yes. Because anything could be pending in buffers which could cause uncontrolled behavior. It's just safer to create a new Jedis object.
That's what I recommended to my leader. But he tends to reset the flag broken to false when use jedis.close() in resource code for the reason that when using jedis.connect(),it will create a new socket and connect to redis . Can buffers affect the use of the new one ? Or you point is caution is the parent of safety

**Comment by shawfifty** [comment]
> @shawfifty Ideally, yes. Because anything could be pending in buffers which could cause uncontrolled behavior. It's just safer to create a new Jedis object.

That's what I recommended to my leader. But he tends to reset the flag broken to false when use jedis.close() in resource code for the reason that when using jedis.connect(),it will create a new socket and connect to redis . Can buffers affect the use of the new one ? Or you point is caution is the parent of safety

**Comment by shawfifty** [comment]
> @shawfifty Ideally, yes. Because anything could be pending in buffers which could cause uncontrolled behavior. It's just safer to create a new Jedis object.
@suryavtkt That's what I recommended to my leader. But he tends to reset the flag broken to false when use jedis.close() in resource code for the reason that when using jedis.connect(),it will create a new socket and connect to redis . Can buffers affect the use of the new one ? Or you point is caution is the parent of safety

**Comment by shawfifty** [comment]
> @shawfifty Ideally, yes. Because anything could be pending in buffers which could cause uncontrolled behavior. It's just safer to create a new Jedis object.

@sazzad16 That's what I recommended to my leader. But he tends to reset the flag broken to false when use jedis.close() in resource code for the reason that when using jedis.connect(),it will create a new socket and connect to redis . Can buffers affect the use of the new one ? Or you point is caution is the parent of safety
