### ISSUE TITLE
Use Keywords in Param classes

### ISSUE THREAD

**Issue by sazzad16** [redis/jedis#2303]
> I would have set these (STORE &STOREDIST) as Keywords so you won't have to re-serialize them on each call

_Originally posted by @gkorland in https://github.com/redis/jedis/pull/2157#discussion_r392667981_

> None of the Params classes use Keyword yet. May be we can create a separate issue to improve this?

_Originally posted by @sazzad16 in https://github.com/redis/jedis/pull/2157#discussion_r396091103_

**Comment by MrFrydae** [comment]
As I am unfamiliar with this codebase, could you please give me an example of how you would want this to be implemented?

Instead of ``addParam(STORE, key);`` with ``STORE`` being a String, would you want it to be converted to a Keyword?

**Comment by sazzad16** [comment]
@MrFrydae Yes.

**Comment by dengliming** [comment]
Currently, All fields of `Params` were put into a `HashMap`. e.g.

```
public class ZIncrByParams extends Params {

  private static final String XX = "xx";
  private static final String NX = "nx";
  private static final String INCR = "incr";
  ....
  public byte[][] getByteParams(byte[] key, byte[]... args) {
    ArrayList<byte[]> byteParams = new ArrayList<>();
    byteParams.add(key);

    if (contains(NX)) {
      byteParams.add(SafeEncoder.encode(NX));
    }
    if (contains(XX)) {
      byteParams.add(SafeEncoder.encode(XX));
    }

    byteParams.add(SafeEncoder.encode(INCR));

    Collections.addAll(byteParams, args);
    return byteParams.toArray(new byte[byteParams.size()][]);
  }
}

```
Wouldn't it be better if we changed it to the following? no need to call `contains(XX)` and `get(xxx)` from a `Map` and something like `INCR` will be place in `Keyword`.

```
public class ZIncrByParams extends Params {

  private boolean xx = false;
  private boolean nx = false;
  private boolean incr = false;

  public ZIncrByParams nx() {
    this.nx = true;
    return this;
  }
  .....

  public byte[][] getByteParams(byte[] key, byte[]... args) {
    ArrayList<byte[]> byteParams = new ArrayList<>();
    byteParams.add(key);

    if (nx) {
      byteParams.add(SafeEncoder.encode(NX));
    }
    if (xx) {
      byteParams.add(SafeEncoder.encode(XX));
    }
    if (incr) {
      byteParams.add(SafeEncoder.encode(INCR));
    }

    Collections.addAll(byteParams, args);
    return byteParams.toArray(new byte[byteParams.size()][]);
  }

}
```

@sazzad16 @gkorland Can you comment on that? Thanks.

**Comment by sazzad16** [comment]
@dengliming For the particular Params class that you mentioned, yes, your approach is better. But keeping in a Map allowed all Params class to have a _base_ class.

However, many of the Params classes have their own format of `getByteParams` method. So day-by-day significance of base class is deceasing.

**Comment by Razi007** [comment]
interested to work here.Guidance needed.

**Comment by sazzad16** [comment]
@Razi007 as a new contributor, I think you can start with [Redis 7 commands to implement](https://github.com/redis/jedis/discussions/2807).

**Comment by Razi007** [comment]
@sazzad16 thanks for the suggestion.I will start with it.

**Comment by sazzad16** [comment]
@Razi007 To get some ideas, you can check PRs that are already merged. E.g. about implementing _regular_ commands, you can check #2843 which is pretty straightforward. #2771 is a bit more complex one.

**Comment by sazzad16** [comment]
@Razi007 Sure.
