### ISSUE TITLE
JedisDataException when trying to connect with ACL user: null user is mistakenly used

### ISSUE THREAD

**Issue by oridool** [redis/jedis#2318]
### Expected behavior

Connection success and Redis command is working

### Actual behavior

I get the following exception:
redis.clients.jedis.exceptions.JedisDataException: 
ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Configure the ConnectionFactory (SpringBoot) with user and password
```
    @Bean
    public JedisConnectionFactory redisConnectionFactory() {

        RedisStandaloneConfiguration config = new RedisStandaloneConfiguration("10.10.xxx.yyy", 6379);
        config.setPassword(RedisPassword.of("pass"));
        config.setUsername("user");
        return new JedisConnectionFactory(config);
    }

```

2. Perform any call to Redis
3. Exception occurs.
4. Just to make sure - I switched the configuration from Jedis to Lettuce and it worked ok.

I believe the issue is with mistakenly omitting the 'user' parameter when initializing `JedisFactory` class.
Here is my partial call stack:

<init>:72, JedisFactory (redis.clients.jedis)
<init>:61, JedisFactory (redis.clients.jedis)
**<init>:54, JedisFactory (redis.clients.jedis)**
<init>:224, JedisPool (redis.clients.jedis)
<init>:215, JedisPool (redis.clients.jedis)
createRedisPool:398, JedisConnectionFactory (org.springframework.data.redis.connection.jedis)
createPool:365, JedisConnectionFactory (org.springframework.data.redis.connection.jedis)
afterPropertiesSet:347, JedisConnectionFactory (org.springframework.data.redis.connection.jedis)

in line 224, I can still see the user in the debugger.
But on the next call in line 54, the user is omitted and therefore initialized to `null`.

### Redis / Jedis Configuration
I'm using Springboot 2.4.1 and spring-data-redis:2.4.2

#### Jedis version:
redis.clients:jedis:3.4.0

#### Redis version:
6.0.9
#### Java version:
11.06

**Comment by sazzad16** [comment]
@oridool Acknowledged the issue. Thanks for reporting.
