### ISSUE TITLE
Why return null while 'nil' in doc ?

### ISSUE THREAD

**Issue by jackie88558** [redis/jedis#2332]
When I call rpoplpush from an empty list, Jedis return null.
While doc tells it should be 'nil' ?
![image](https://user-images.githubusercontent.com/17266285/103284664-c896e400-4a16-11eb-8157-c4eb14f53eba.png)
Is it a doc typo?

**Comment by sazzad16** [comment]
@jackie88558 The command documentation are mostly brought from [Redis documentations](https://redis.io/commands). So the `nil` that you are pointing towards is actually Redis `nil`, equivalent of which is `null` in Java (as in null Object, not `"null"` String).

**Comment by jackie88558** [comment]
> @jackie88558 The command documentation are mostly brought from [Redis documentations](https://redis.io/commands). So the `nil` that you are pointing towards is actually Redis `nil`, equivalent of which is `null` in Java (as in null Object, not `"null"` String).

Thanks for ur explanation. But I think it would be better to add these words to the doc.

**Comment by sazzad16** [comment]
@jackie88558 Jedis is a community driven project and you are very much welcome to craft a PR regarding this. Thanks
