### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by yeahCaesar** [redis/jedis#2345]
### Expected behavior

Jedis works normally

### Actual behavior

Throw exception: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.create a redis cluster with two servers , 3 master nodes on one server, 3 slave nodes on another
2.kill 3 slave nodes
3.jedis client throws exception , but not all jedis connections 

#### Java version: 1.8.0

![reidscluster04](https://user-images.githubusercontent.com/19277364/105329880-9e4ad780-5c0c-11eb-84d7-b4f544649a01.png)

**Comment by walles** [comment]
This could potentially be fixed by #2358.

**Comment by sazzad16** [comment]
@yeahCaesar I could not regenerate such issue.

> jedis client throws exception , but not all jedis connections

I don't think I clearly understand. Could you please elaborate?

Also, did you try later with more updated version of Jedis?
