### ISSUE TITLE
Feature Request: Provide String-keyed analogues for Binary API commands with byte[] values

### ISSUE THREAD

**Issue by nanreh** [redis/jedis#2365]
A common use case for Redis is to store binary values. I regularly deal with Redis values that are BLOBs generated by Thrift, Kryo, or some other serialization scheme.

The Jedis API acknowledges this common case with its Binary API, which is a collection of commands that take `byte[]` keys and values.

Unfortunately, there's some friction when combining the Binary API with other core Jedis features. For example, I like to use `ShardedJedis`, `ShardedJedisPipeline`, and Jedis `keytags` in my keys to make sure values I commonly fetch together live on the same shard. Here's a bit of code that illustrates this friction:
```
@Test
public void brokenShardedPipeline() {
  ShardedJedisPipeline p = jedis.pipelined();
  Response<Map<String, String> messagesMap = p.hgetAll("{playerId}.messages");
  Response<byte[]> inventoryBytes = p.get(SafeEncoder.encode("{guildId}.inventory")); // Binary API call to fetch a serialized value
  p.sync();
}
```
Of course, the issue is that the Binary API ignores `keytags` and so there is no way to safely dispatch a read like this one in a Pipeline.

As pointed out [way back in 2011](https://groups.google.com/g/jedis_redis/c/nIcJYzHH1ts/m/Ji4v-xkEGjUJ) the workaround is to "do it outside of Jedis, on your app side. By calling shardedJedis.getShard("somekey") and operate on regular Jedis class", which looks something like this:
```
@Test
public void noPipeline() {
  Map<String, String> messagesMap = jedis.hgetAll("{playerId}.messages");
  Jedis jedis = jedis.getShard("{guildId}.inventory");
  byte[] inventoryBytes = jedis.get(SafeEncoder.encode("{guildId}.inventory"))
}
```
This approach works but it means I don't get to use the `Pipeline` abstraction at all, which is unfortunate for performance and because `Pipeline` goes a long way towards keeping code concise and readable, like when we loop to queue up Redis `Response`s and follow up with a `.sync()` call.

So I propose that we address this issue by extending the Jedis Binary API to include a few commands that take `String` keys and `byte[]` values. These new commands would of course honor any `keytags` contained within them.

The new commands are:
```
String set(String key, byte[] value);
String set(String key, byte[] value, SetParams params);
byte[] get(String key);
byte[] getSet(String key, byte[] value);
Long setnx(String key, byte[] value);
String setex(String key, int seconds, byte[] value);
String psetex(String key, long milliseconds, byte[] value);
```
Unfortunately, `byte[] get(String key)` collides with the existing `String get(String key)`, so the new method will need a different name (`getB`? `getS`?).

I'm happy to do this work, I already have it working locally. I could put a PR together after adding a few test cases.

Feedback welcome, please let me know if this is a change there would be interest in for Jedis.

**Comment by sazzad16** [comment]
@nanreh I think there are ways to bypass this.

1. Do a custom implementation of `Hashing` and pass it in `ShardedJedis` constructor.
2. Override `getShard` of binary version to use string version.
```
    new BinaryShardedJedis(shards) {
      @Override
      public Jedis getShard(byte[] key) {
        return getShard(SafeEncoder.encode(key));
      }
    };
```

---

> please let me know if this is a change there would be interest in for Jedis.

No. This would just worsen the current codebase. Thank you for your interest though. We encourage you to craft PRs on other issues.

**Comment by nanreh** [comment]
Clever, thanks for those suggestions. Overriding `getShard()` does indeed work around the main issue for me. Closing this issue.
