### ISSUE TITLE
HA configurations between JedisShardedInfo vs Jedis Cluster

### ISSUE THREAD

**Issue by BingjieGao** [redis/jedis#2366]
### Expected behavior

While I'm looking into the architecture on Redis cluster it seems like it allows multi-masters and must have multi-masters to take the advantages of HA. However I found really hard to use JedisCluster to set up two different cluster nodes with two different passwords and other configs.

### Actual behavior

Presumably, event without the sentinel setup Redis cluster should support the auto-failover strategy. Attaching with the sentinel mode it keeps monitoring within clusters to promote SLAVE to MASTER. While when I want to connect JedisCluster as client to multiple different instances(clusters, each instance has 3 slave nodes), it does give the option to connect to master node binding with its' own password on authentication.

**Comment by sazzad16** [comment]
@BingjieGao You should submit the feature request to **Redis** project https://github.com/redis/redis/issues . Thanks
