### ISSUE TITLE
XAUTOCLAIM command (#7973)

### ISSUE THREAD

**Issue by gkorland** [redis/jedis#2387]

**Comment by s-sathish** [comment]
Hi @gkorland @dengliming I was exploring the redis streams commands using redis-cli and then from an application (using Jedis).
And in pursuit of that, I noted that the 'XAUTOCLAIM' command is not yet supported by Jedis. So I took a fork of latest master and worked on the implementation. It's done now.

If this is not yet picked, I'm happy to submit a PR for the same. Please let me know.

Thanks.

**Comment by dengliming** [comment]
@s-sathish Thanks for picking this issue. Fell free to submit a PR : )

**Comment by s-sathish** [comment]
Hi @dengliming I submitted the PR - https://github.com/redis/jedis/pull/2498
Please have a look.

**Comment by mriehl** [comment]
Hi @gkorland @sazzad16 there doesn't seem to be a 3.6 backport for this feature, is that intentional?
Is it something you'd accept a PR for, or is 3.7 "very close"? Is running one of the 3.7 snapshots in production something you'd recommend if interested in the xautoclaim feature?

**Comment by sazzad16** [comment]
> there doesn't seem to be a 3.6 backport for this feature, is that intentional?

Yes.

> Is it something you'd accept a PR for

No.

Jedis follows `major.minor.patch` semantic versioning and a new feature (e.g. xautoclaim) can't be included in a patch version (e.g. 3.6.2).

---

> Is running one of the 3.7 snapshots in production something you'd recommend if interested in the xautoclaim feature?

It's completely up to you. Make a decision on how much you want/need this feature and how much you trust Jedis snapshots.

**Comment by sazzad16** [comment]
@mriehl 

> there doesn't seem to be a 3.6 backport for this feature, is that intentional?

Yes.

> Is it something you'd accept a PR for

No.

Jedis follows `major.minor.patch` semantic versioning and a new feature (e.g. xautoclaim) can't be included in a patch version (e.g. 3.6.2).

---

> Is running one of the 3.7 snapshots in production something you'd recommend if interested in the xautoclaim feature?

It's completely up to you. Make a decision on how much you want/need this feature and how much you trust Jedis snapshots.

**Comment by mriehl** [comment]
> It's completely up to you. Make a decision on how much you want/need this feature and how much you trust Jedis snapshots.

I see, makes sense. Thanks a lot for your quick reply @sazzad16 !
