### ISSUE TITLE
Should we keep the parameter types of BinaryJedis PipelineBase stay the same?

### ISSUE THREAD

**Issue by dengliming** [redis/jedis#2394]
e.g. 

`BinaryJedis`
public  List<byte[]> xclaim(byte[] key, byte[] groupname, byte[] consumername, long minIdleTime, long newIdleTime, int retries, boolean force, `byte[][] ids`)

`PipelineBase:`
public Response<List<byte[]>> xclaim(byte[] key, byte[] group, byte[] consumername, long minIdleTime, long newIdleTime, int retries, boolean force, `byte[]... ids`)

`BinaryJedis`
public List<byte[]> xrange(byte[] key, byte[] start, byte[] end, `long count`)

`Jedis`
public List<StreamEntry> xrange(final String key, final StreamEntryID start, final StreamEntryID end, `final int count`)

and BTW
should we return `Response<List<byte[]>>` ？
`redis.clients.jedis.PipelineBase#Response<List<StreamPendingEntry>> xpending(byte[] key, byte[] groupname, byte[] start, byte[] end, int count, byte[] consumername)`

**Comment by sazzad16** [comment]
@dengliming acknowledged
