### ISSUE TITLE
Should we reformat code using hbase-formatter.xml?

### ISSUE THREAD

**Issue by dengliming** [redis/jedis#2397]
As stated in the [Contribution Guide](https://github.com/redis/jedis/blob/master/.github/CONTRIBUTING.md). we should follow the same code style(`hbase-formatter`). but currently lots of files don't follow this style. Every time I commit, I change a lot of unnecessary line breaks and Spaces. Please consider If that make senses. Thanks.

**Comment by sazzad16** [comment]
I agree that we should reformat our codebase. But the problem is that it could invalidate most of the pending PRs. If we could reduce the number of open PRs, we sure would reformat.

**Comment by dengliming** [comment]
Thanks. Seems already reformat most of codes.
