### ISSUE TITLE
BinaryShardedJedis#method:disconnect

### ISSUE THREAD

**Issue by dlsscly** [redis/jedis#2423]
public void disconnect() {
    for (Jedis jedis : getAllShards()) {
      if (jedis.isConnected()) {
        try {
          jedis.quit();
        } catch (JedisConnectionException e) {
          // ignore the exception node, so that all other normal nodes can release all connections.
        }
        try {
          jedis.disconnect();
        } catch (JedisConnectionException e) {
          // ignore the exception node, so that all other normal nodes can release all connections.
        }
      }
    }
  }

why not catch Exception replace JedisConnectionException?

**Comment by sazzad16** [comment]
@dlsscly Please let us know what issue you're facing for not catching Exception instead of JedisConnectionException?

**Comment by sazzad16** [comment]
Closed due to inactivity.
