### ISSUE TITLE
Commands added into a stale transaction (by mistake) causing ClassCastException

### ISSUE THREAD

**Issue by ganeshkumarganesan** [redis/jedis#2496]
### Expected behavior

Restricting commands addition into a stale transaction or Clearing the RedisOutputStream while returning jedis connection to the pool. Will prevent such issues.

### Actual behavior

When the same jedis connection obtained from the pool, the previously added command(s) from the RedisOutputStream also got executed and which caused the ClassCastException. 

**java.lang.ClassCastException: java.lang.Long cannot be cast to [B**

### Steps to reproduce:

```
try(JedisPool pool = new JedisPool(new JedisPoolConfig(), "localhost", 6379, 2000, 2000, null, 0, null,false,null,null,null)) 
{
	try(Jedis jedis = pool.getResource()) 
	{
		Transaction redisTrans = jedis.multi();
		redisTrans.hgetAll("Test");
		redisTrans.exec();
				
		redisTrans.hdel("Test","Test");  //This hdel command is just added into the RedisOutputStream.
	} 
			
	try(Jedis jedis = pool.getResource()) 
	{
		//Now, both hdel & select command is getting executed, this led to the java.lang.ClassCastException: java.lang.Long cannot be cast to [B
		jedis.select(15); 
	}
}
```

**Comment by sazzad16** [comment]
@ganeshkumarganesan Trying to resolve this in Jedis means we would have to sacrifice the performance of at least either `getResource()` or `returnResource()`.
Instead of that, I would suggest you to try setting `setTestOnReturn(true);` and/or `setTestOnBorrow(true);` in GenericObjectPoolConfig.
