### ISSUE TITLE
java.lang.ClassCastException: [B cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by Siva732** [redis/jedis#2511]
JedisLock jedisLock=abstractRedisDAO.createJedisLockFromKey("lock2");
jedisLock.acquire();  throwing exception in this line

java.lang.ClassCastException: [B cannot be cast to java.lang.Long
        at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
        at redis.clients.jedis.Jedis.setnx(Jedis.java:422)
        at com.github.jedis.lock.JedisLock.acquire(JedisLock.java:142)
        at com.github.jedis.lock.JedisLock.acquire(JedisLock.java:125)

 public JedisLock createJedisLockFromKey(String key) throws BadRequestException {
        if (StringUtils.isEmpty(key)) {
            throw new BadRequestException(ErrorCode.BAD_REQUEST_ERROR, "Key is null");
        }
        Long result = null;
        Jedis jedisClient = null;
        JedisLock jedisLock=null;
        try {
            jedisClient = getRedisClient();
            jedisLock=new JedisLock(jedisClient,key,1000,3000);
            return jedisLock;
        } catch (Exception ex) {
            logger.error("Error in removing element from );
        } finally {
            closeRedisClient(jedisClient);
        }
        return jedisLock;
    }

**Comment by sazzad16** [comment]
@Siva732 This sorts of issues generally happen when Jedis is used improperly in multi-threaded environment.

You've provided `JedisLock` codes which is neither part of this repo nor have common maintainers. There is only single piece of Jedis related code `getRedisClient()` and we don't even know what's happening there. It'd be better helpful for you if you could provide Jedis specific codes. You could also consider consulting JedisLock developers.

I'm closing this issue for now. Thank you.
