### ISSUE TITLE
What is the fastest way to hset miliions of keys

### ISSUE THREAD

**Issue by quantrpeter** [redis/jedis#2513]
Hi
   What is the fastest way to hset miliions of keys. I can use jdbc+mysql to insert 100,000 in less then 1 min, but jedis much slower. Any tips?
thanks
Peter

**Comment by sazzad16** [comment]
Pipelining.
```
Pipeline p = jedis.pipelined();
p.hset(...);
p.hset(...);
...
...
...
p.hset(...);
p.sync();
```
[sent from mobile]

**Comment by quantrpeter** [comment]
thanks @sazzad16
