### ISSUE TITLE
3 billions records

### ISSUE THREAD

**Issue by quantrpeter** [redis/jedis#2517]
hi, i need to insert 3 billions records, but i got "redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer" after inserted 48,700,000 records. please help. Thanks

```
		GenericObjectPoolConfig jedisPoolConfig = new GenericObjectPoolConfig();
		jedisPoolConfig.setMaxTotal(32);
		jedisPoolConfig.setMaxWaitMillis(-1);

		JedisPool jedisPool = new JedisPool(jedisPoolConfig, "192.168.0.239", 6379, Integer.MAX_VALUE);

		Jedis jedis = jedisPool.getResource();
		jedis.select(1);
		Pipeline p = jedis.pipelined();

outer:
			while (true) {
				int y = 0;
				values = new LinkedHashMap<>();
				do {
					line = reader.readLine();
					if (line == null) {
						break outer;
					}
					String words[] = line.trim().split(" +");
					for (int x = 0; x < words.length; x += 2) {
						words[x] = words[x].replaceAll("/", "_");
//				registers.add(words[x]);
						values.put(words[x], words[x + 1].startsWith("0x") ? words[x + 1] : "0x" + words[x + 1]);
					}
					y++;
				} while (y < 18);

				p.hset("r:" + sequence, values);
				sequence++;
				if (sequence % 100000 == 0) {
					p.sync();

					jedis.close();
					jedis = jedisPool.getResource();
					jedis.select(1);
					p = jedis.pipelined();
					System.out.printf("%s : %,d\n", sdf.format(new Date()), sequence);
				}
				if (sequence % 1000000 == 0) {
					p.save();
				}
			}

			jedis.close();
```

**Comment by sazzad16** [comment]
@quantrpeter What's the value of `timeout` in Redis instance?

**Comment by quantrpeter** [comment]
@sazzad16 thanks first, here i set the timeout:

JedisPool jedisPool = new JedisPool(jedisPoolConfig, "192.168.0.174", 6379, Integer.MAX_VALUE);

i also tried

JedisPool jedisPool = new JedisPool(jedisPoolConfig, "192.168.0.174", 6379, 100000);

Both failed.

**Comment by quantrpeter** [comment]
after inserted 48,000,000, the memory consumption suddenly keep rising and eat all ram of my 64GB ram linux, then timeout from java side.

**Comment by yangbodong22011** [comment]
@quantrpeter So, does Redis normal when `JedisConnectionException` occurs? (e.g. did OOM occur?)

**Comment by quantrpeter** [comment]
@yangbodong22011 i forgot redis is in memory, i run out ram
