### ISSUE TITLE
Get "Attempting to read from a broken connection" exception, but key2 was successfully set

### ISSUE THREAD

**Issue by yangbodong22011** [redis/jedis#2527]
### Steps to reproduce:
code: 
```
public class JedisTest {
    public static void main(String[] args) throws Exception {
        Jedis jedis = new Jedis("127.0.0.1", 6379, 10000);

        // step1: debug sleep 20  (Redis will sleep 20s)

        // step2: call set, will timeout, and set broken
        try {
            System.out.println(jedis.set("key1", "value"));
        } catch (Exception e) {
            e.printStackTrace();
        }

        // step3: sleep 10s
        Thread.sleep(10000);

        // step4: call set again, will get "Attempting to read from a broken connection"
        // but data will set success
        try {
            System.out.println(jedis.set("key2", "value"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

terminal log: 
> redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
	at redis.clients.jedis.Protocol.process(Protocol.java:158)
	at redis.clients.jedis.Protocol.read(Protocol.java:223)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)
	at redis.clients.jedis.Jedis.set(Jedis.java:222)
	at redis.clients.jedis.tests.fanche.JedisTest.main(JedisTest.java:17)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:126)
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	... 7 more
redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:348)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)
	at redis.clients.jedis.Jedis.set(Jedis.java:222)
	at redis.clients.jedis.tests.fanche.JedisTest.main(JedisTest.java:28)

key2 was successfully set:
```
127.0.0.1:6379> debug sleep 20
OK
(20.00s)
127.0.0.1:6379> keys *
1) "key2"
2) "key1"
127.0.0.1:6379> 
```

#### Jedis version:
master branch

I'm not sure if this behavior is correct, but it will obviously cause confusion to the user. The user has obtained the exception, but the key has been successfully written.

**Comment by sazzad16** [comment]
@yangbodong22011 "Inconsistent behavior", isn't it what's expected while operating with a broken connection?

**Comment by yangbodong22011** [comment]
> @yangbodong22011 "Inconsistent behavior", isn't it what's expected while operating with a broken connection?

@sazzad16 Many users use `Jedis` instead of `JedisPool`, such as [YCSB](https://github.com/brianfrankcooper/YCSB/blob/master/redis/src/main/java/site/ycsb/db/RedisClient.java#L89). When `Jedis` times out, it may still be used (This is a wrong way to use it). However, at this time, the wrong `Jedis` can still write data. I think we can throw an exception or directly choose to reconnect by judging the `broken` condition at `sendCommand`, for example, the following two methods:

```
   public void sendCommand(final ProtocolCommand cmd, final byte[]... args) {
     try {
+      if (broken) {
+        throw new JedisConnectionException("Attempting to write from a broken connection");
+      }
       connect();
```
or 
```
   public boolean isConnected() {
     return socket != null && socket.isBound() && !socket.isClosed() && socket.isConnected()
-        && !socket.isInputShutdown() && !socket.isOutputShutdown();
+        && !socket.isInputShutdown() && !socket.isOutputShutdown() && !isBroken();
   }
```

we can throw exception, but the request should not be excute.

**Comment by sazzad16** [comment]
@yangbodong22011 got it.

**Comment by yangbodong22011** [comment]
I tend to let Jedis `reconnect` and execute user requests correctly. I think the `connect()` in the current `sendCommand` is the original author's purpose.

```
diff --git a/src/main/java/redis/clients/jedis/Connection.java b/src/main/java/redis/clients/jedis/Connection.java
index 5bc7702b..055e5ebe 100644
--- a/src/main/java/redis/clients/jedis/Connection.java
+++ b/src/main/java/redis/clients/jedis/Connection.java
@@ -227,6 +227,7 @@ public class Connection implements Closeable {
 
         outputStream = new RedisOutputStream(socket.getOutputStream());
         inputStream = new RedisInputStream(socket.getInputStream());
+        broken = false;
       } catch (IOException ioe) {
         broken = true;
         throw new JedisConnectionException("Failed to create input/output stream", ioe);
@@ -262,7 +263,7 @@ public class Connection implements Closeable {
 
   public boolean isConnected() {
     return socket != null && socket.isBound() && !socket.isClosed() && socket.isConnected()
-        && !socket.isInputShutdown() && !socket.isOutputShutdown();
+        && !socket.isInputShutdown() && !socket.isOutputShutdown() && !isBroken();
   }

```

@sazzad16 WDYT?

**Comment by sazzad16** [comment]
@yangbodong22011 I take `connect()` as a way of creating connections lazily; so that actual socket won't be created in constructor but while executing the first command.

**Comment by yangbodong22011** [comment]
> @yangbodong22011 I take `connect()` as a way of creating connections lazily; so that actual socket won't be created in constructor but while executing the first command.

Make sense.

But you actively called `connect()` in the latest code `initializeFromClientConfig` (of course I think it’s okay)

Going back to this question, Which approach do you prefer?

**Comment by sazzad16** [comment]
@yangbodong22011 I'm sorry, I don't get your question. Preference on what?

**Comment by yangbodong22011** [comment]
> @yangbodong22011 I'm sorry, I don't get your question. Preference on what?

about this: https://github.com/redis/jedis/issues/2527#issuecomment-828572784, which of the two pieces of code would you choose?

**Comment by sazzad16** [comment]
@yangbodong22011 not sure about liking either of those two. (Frankly, I'd try to avoid both.) Still, if I have to, I'd **avoid** the second one more.

**Comment by janckin** [comment]
so is this problem optimized in a certain version？I have met the same problem. Must I use a Pool or create a new connection?

**Comment by janckin** [comment]
so is this problem optimized in a certain version？I have met the same problem. Must I use a Pool or create a new connection?

**Comment by sazzad16** [comment]
@janckin Generally, it's better to use Pool or create a new connection.
