### ISSUE TITLE
The jedis connection has been closed, and why can I still operate it?

### ISSUE THREAD

**Issue by wangzhihan-scut** [redis/jedis#2542]
### Expected behavior
I have closed the jedis connection by “jedis.close()”, and why it can be used to do some operations without any mistake?

### Actual behavior
![image](https://user-images.githubusercontent.com/43195744/118124846-be570e80-b428-11eb-8508-05b68ad883dc.png)
![image](https://user-images.githubusercontent.com/43195744/118124808-b1d2b600-b428-11eb-959c-b80bbd93de69.png)

### Redis / Jedis Configuration
localhost:6379
#### Jedis version:
3.2.0
#### Redis version:
3.2.100
#### Java version:
1.8

**Comment by sazzad16** [comment]
@wangzhihan-scut It's there by design.

**Comment by wangzhihan-scut** [comment]
> @wangzhihan-scut It's there by design.
So what exactly did this operation do, I don’t understand the meaning of this design.

**Comment by wangzhihan-scut** [comment]
> @wangzhihan-scut It's there by design.
Does it encourage using connection pool instead of a single connection?

**Comment by sazzad16** [comment]
@wangzhihan-scut The design is that if there any Redis command being executed by a closed Jedis object, it would reinitialize and reconnect with Redis and execute the command.

> Does it encourage using connection pool instead of a single connection?

I'm sorry, I don't understand how you're reaching to that summary.

However, you should use connection pool in multi-thread.
