### ISSUE TITLE
JedisClusterInfoCache: refresh the nodes map

### ISSUE THREAD

**Issue by stillerrr** [redis/jedis#2550]
### Expected behavior

Jedis would refresh the elements of nodes map  when the cluster nodes changed

![image](https://user-images.githubusercontent.com/35724820/118773816-be875c00-b8b7-11eb-85fc-c8bc237fa56a.png)

### Actual behavior

this nodes parameter just add nodes if not exist in map, but not delete nodes when cluster nodes are deleted
![image](https://user-images.githubusercontent.com/35724820/118774842-d6131480-b8b8-11eb-89a7-e49f00721ea3.png)

### Steps to reproduce:

it would cause a problem in this situation:
1. create a redis cluster A with 10 master nodes  and delete 9 nodes from cluster;
2. use the 9 nodes create a new cluster B
2. delete some slots from the cluster or give a large latency between client and the cluster A， make sure jedis throw JedisConnectionException;

JedisConnectionException would cause a slot refresh in JedisClusterCommand: 

![image](https://user-images.githubusercontent.com/35724820/118774358-52592800-b8b8-11eb-8968-2fe89e37c78e.png)

this method would use JedisClusterInfoCache paramter: nodes map values to refresh slot in JedisClusterInfoCache.renewClusterSlots():
![image](https://user-images.githubusercontent.com/35724820/118773931-d9f26700-b8b7-11eb-901a-5f7cf5a3fd02.png)

![image](https://user-images.githubusercontent.com/35724820/118774608-9c420e00-b8b8-11eb-9e62-e0865685317f.png)

There is a high probability(90%) that the jedis client will connect to cluster B because jedis use the cluster B nodes to refresh slot

#### Jedis version:
3.6.0

**Comment by sazzad16** [comment]
@StillerRen In such massive reconfiguration of Redis Cluster, you should recreate JedisCluster with proper nodes.

**Comment by StillerRen** [comment]
Node adding and deleting is normal operation for cluster and client don't perceive the change.
I think jedis should determine cluster nodes based on the cluster nodes/slots command.

**Comment by sazzad16** [comment]
Jedis is supporting node adding and deleting well enough.
Only issue it doesn't handle (in JedisCluster A) yet is when a node is moved from Redis Cluster A to Redis Cluster B.

**Comment by StillerRen** [comment]
This is a common operation, especially when resources are reused.
but this would cause the client connect to a wrong cluster and hard to find out reason

**Comment by brunogbv** [comment]
Bumping this old issue, sorry in advance.

We just had an incident in production related with this issue where, during Elasticache maintenance window, AWS reused some IP's from a node in cluster A to another one in cluster B. 

It was tricky to understand what was going on since it was a silent error - data inconsistency and unexpected behaviour without clear indication of where the problem was. We're still exploring our possible solutions, but without fixing this issue I don't think Jedis is safe for production IMHO. Especially in cloud environments where the IP's are not on your control.

Let me know your thoughts and thanks in advance.

Also huge thanks to @ivkalita for finding this tricky issue

**Comment by yangbodong22011** [comment]
> Bumping this old issue, sorry in advance.
> 
> We just had an incident in production related with this issue where, during Elasticache maintenance window, AWS reused some IP's from a node in cluster A to another one in cluster B.
> 
> It was tricky to understand what was going on since it was a silent error - data inconsistency and unexpected behaviour without clear indication of where the problem was. We're still exploring our possible solutions, but without fixing this issue I don't think Jedis is safe for production IMHO. Especially in cloud environments where the IP's are not on your control.
> 
> Let me know your thoughts and thanks in advance.
> 
> Also huge thanks to @ivkalita for finding this tricky issue

Your issue may be similar to this: https://github.com/redis/jedis/issues/3595

**Comment by MingJunDuan** [comment]
So, Jedis support refresh topology  or not?

**Comment by yangbodong22011** [comment]
> So, Jedis support refresh topology or not?

sure, Jedis has released this feature in version [5.1.0](https://github.com/redis/jedis/releases/tag/v5.1.0), which supports periodically refreshing the routing table. You can turn it on by setting `topologyRefreshPeriod`.

**Comment by MingJunDuan** [comment]
> > So, Jedis support refresh topology or not?
> 
> sure, Jedis has released this feature in version [5.1.0](https://github.com/redis/jedis/releases/tag/v5.1.0), which supports periodically refreshing the routing table. You can turn it on by setting `topologyRefreshPeriod`.

Nice work!
