### ISSUE TITLE
Jedis connection leak

### ISSUE THREAD

**Issue by Zavierazo** [redis/jedis#2558]
### Expected behavior

During progressive activation we expect connections to be stable

### Actual behavior

Connection leak during progressive activation

### Steps to reproduce:

We are only able to reproduce this scenario in our production environment. We are activating node by node with the new functionality that basically a lazy cache functionality.  For each request we do an MGET to obtain data if they already exist. If it does not exist, we process and at the end of all we save that data in redis with an EVAL.

Everything works fine during rollout until we reach aprox 20k commands per second. 
![image](https://user-images.githubusercontent.com/6851912/119543922-796c9980-bd91-11eb-9c88-7679a76aacd9.png)

The specific problem is at some point memory and connected clients for a specific redis node starts to grow until node reach maxmemory and flush all data
![image](https://user-images.githubusercontent.com/6851912/119544139-b9cc1780-bd91-11eb-97c9-1bd5edd0dda8.png)

We do not believe that it is because of the data that is inserted since it always happens when we reach a certain level of concurrency in redis. In addition, the traffic we receive during gradual activation is the same constantly and we only activate this functionality node by node. 

Each node is handling about 150 requests per second which translates to about 300 commands + the pings thrown by the testOnBorrow. When we reach 50 nodes of 80 we start seeing this problem

In the logs we only see a lot of this errors

ERROR\|2021-05-20T12:50:58,493\|LazyCacheByHotelRepositoryImpl\|Fallback errorredis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left. 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86) 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) 	at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:69) 	at redis.clients.jedis.BinaryJedisCluster.mget(BinaryJedisCluster.java:1529) 	at com.xxxxxxx.repository.lazy.LazyCacheRepositoryImpl.multiGetJedis(LazyCacheRepositoryImpl.java:176)

### Redis / Jedis Configuration

maxIdle: 50
maxTotal: 200
maxWaitMillis: 1000
testOnBorrow: true
lifo: Tested with true and false, same problem. We think that lifo false does a better connection management in terms of connection duration(with lifo true connections are renewed more often)

````
@Bean
    public JedisConnectionFactory redisConnectionFactory() {
        RedisClusterConfiguration serverConfig = new RedisClusterConfiguration();
        HashSet<RedisNode> nodes = new HashSet<>();
        RedisNode redisNode = new RedisNode(host, port);
        nodes.add(redisNode);
        serverConfig.setClusterNodes(nodes);
        if (StringUtils.isNotEmpty(password)) {
            serverConfig.setPassword(password);
        }
        return getJedisConnectionFactory(serverConfig);
    }

    public JedisConnectionFactory getJedisConnectionFactory(RedisClusterConfiguration configuration) {
        JedisPoolConfig poolConfig = new JedisPoolConfig();
        poolConfig.setMaxIdle(maxIdle);
        poolConfig.setMaxTotal(maxTotal);
        poolConfig.setMaxWaitMillis(maxWaitMillis);
        poolConfig.setTestOnBorrow(testOnBorrow);
        poolConfig.setLifo(lifo);
        return new JedisConnectionFactory(configuration, poolConfig);
    }

   @Bean("apiRedisTemplate")
    public RedisTemplate<String, Cacheable> redisTemplate() {
        final RedisTemplate<String, Cacheable> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory());
        template.setValueSerializer(new RedisSerializer<Object>() {

            @SneakyThrows
            @Override
            public byte[] serialize(Object value) {
                return cacheHelper.compressValue(value);
            }

            @SneakyThrows
            @Override
            public Object deserialize(byte[] value) {
                return cacheHelper.uncompressedValue(value);
            }
        });
        return template;
    }
````

Redis config

````
  - name: activerehashing
    value: "yes"
  - name: appendonly
    value: "no"
  - name: hash-max-ziplist-entries
    value: "512"
  - name: hash-max-ziplist-value
    value: "64"
  - name: hll-sparse-max-bytes
    value: "3000"
  - name: list-compress-depth
    value: "0"
  - name: maxmemory-policy
    value: "volatile-lru"
  - name: maxmemory
    value: "12000mb"
  - name: maxmemory-samples
    value: "5"
  - name: no-appendfsync-on-rewrite
    value: "no"
  - name: notify-keyspace-events
    value: ""
  - name: set-max-intset-entries
    value: "512"
  - name: slowlog-log-slower-than
    value: "10000"
  - name: slowlog-max-len
    value: "128"
  - name: stop-writes-on-bgsave-error
    value: "yes"
  - name: tcp-keepalive
    value: "0"
  - name: timeout
    value: "300"
````

#### Jedis version:

Jedis 3.3.0 (managed by spring-data-redis 2.2.3.RELEASE

#### Redis version:

redis:5.0.6-alpine

#### Java version:

OpenJDK_11.0.2u9

**Comment by sazzad16** [comment]
@Zavierazo Thank you for posting.

There could be several scenarios for `JedisClusterMaxAttemptsException`. One of those could be that all the connections in the pool are busy; causing the respective operation to fail all its attempts due to lack of a free connection to operate on.
