### ISSUE TITLE
Wrong default values for maxTotalRetriesDuration

### ISSUE THREAD

**Issue by akurth** [redis/jedis#2559]
### Expected behavior

Default maxTotalRetriesDuration should be soTimeout * maxAttempts.

### Actual behavior

Default maxTotalRetriesDuration is soTimeout.

After updating from 3.5.2 to 3.6.0 in our production environment (which is under heavy load; timeout is 300) we almost immediately encountered lots of "JedisClusterOperationException: Cluster retry deadline exceeded." errors.

Looking at the code I found that some of the BinaryJedisCluster constructors set maxTotalRetriesDuration to soTimeout. This should be at least soTimeout * maxAttempts, unless I'm missing something here.

#### Jedis version:

3.6.0

**Comment by akurth** [comment]
Sorry to nit-pick, but the Javadoc still says:
"Defaults to {@link #DEFAULT_TIMEOUT} if unset, or {@code soTimeout} if available."

**Comment by sazzad16** [comment]
@akurth done!
