### ISSUE TITLE
Update version of Javadocs?

### ISSUE THREAD

**Issue by SebastienPi** [redis/jedis#2562]
Hi,

On the Readme, we can read: “Master branch javadocs can be found here: http://redis.github.io/jedis/”. But this link is for 3.0.0. It does not seem updated.

**Comment by sazzad16** [comment]
@gkorland Should we remove the line? It is not being updated for a very long time. I could easily trace that it is not working since Feb 11, 2018. It may not be working way before than that.

**Comment by SebastienPi** [comment]
Maybe I have a better idea: https://www.javadoc.io/doc/redis.clients/jedis/latest/index.html
This link is up to date.

**Comment by sazzad16** [comment]
@SebastienPi great!
