### ISSUE TITLE
How to make authentication data validation before running an app?

### ISSUE THREAD

**Issue by Feniksovich** [redis/jedis#2566]
Hello,
I'm a newbie in Jedis and Java, so I have a simple question:
**How to make authentication credentials validation before running an app** and stop app loading if they're not valid?

Thanks in advance.

**Comment by sazzad16** [comment]
@Feniksovich It seems to be well beyond the scope of Jedis.

**Comment by Feniksovich** [comment]
> @Feniksovich It seems to be well beyond the scope of Jedis.

So, I just tried provide invalid credentails and got exception:
```
redis.clients.jedis.exceptions.JedisAccessControlException: WRONGPASS invalid username-password pair
```

Can I catch this exception with `try-catch` block, for example?
For some reason, I thought that the method does not throw any exceptions, since this information was missing in the description of the method in the IDE (also, I did not check the Javadoc at all).

**Comment by sazzad16** [comment]
> Can I catch this exception with try-catch block, for example?

Yes.

**Comment by Feniksovich** [comment]
@sazzad16 Thanks for your prompt response, this solves my issue.
Have a nice day!

**Comment by sazzad16** [comment]
@Feniksovich Glad to help.
