### ISSUE TITLE
Transaction exec sometimes returns null response

### ISSUE THREAD

**Issue by Jeremymia** [redis/jedis#2575]
### Expected behavior

When running the following code:
```
            jedis.watch(key);
            Transaction t = jedis.multi();
            t.incr(key);
            List<Object> response = t.exec();
            jedis.unwatch();
            if (response != null && response.size() == 1) {
                jedis.expire(key, expiry);
                return (Long)response.get(0);
            } else {
                LOGGER.error(String.format("Unexpected response size. The response was %s for key %s and expiry %d",
                response, key, expiry));

                return null;
            }
```

That logger statement should never occur, because if there was no exception until that point then there should always be exactly one item in the list of responses.

### Actual behavior

On rare occasion, the response object is null.

This logging statement is available:
"Unexpected response size. The response was null for key my_key and expiry 31536000"

### Steps to reproduce:

Unknown. Cannot reproduce consistency.

**Comment by sazzad16** [comment]
@Jeremymia As this issue not reproducible, it is hard to debug.

However, some tips for you:
- The version that you're using, 2.8.0, is very old being release on `Nov 24, 2015`. Try to use a more recent version.
- If you're using Jedis in a multi-threaded environment, check if you're using it properly https://github.com/redis/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment
- You won't have to UNWATCH after EXEC.
- Transaction is used for atomicity. If that's what you want, following approach may be better. Please put `if`s and logging at your convenience.
```
jedis.watch(key);
Transaction t = jedis.multi();
t.incr(key);
t.expire(key, expiry);
List<Object> response = t.exec();
return (Long) response.get(0);
```

**Comment by spmason** [comment]
Isn't a `null` response from `exec` part of the [check-and-set protocol](https://redis.io/topics/transactions#optimistic-locking-using-check-and-set)?

> WATCHed keys are monitored in order to detect changes against them. If at least one watched key is modified before the EXEC command, the whole transaction aborts, and EXEC returns a Null reply to notify that the transaction failed.

I'm now trying to figure out if Jedis supports this properly, does a [Null reply](https://redis.io/topics/protocol#nil-reply) result in `multi.exec` returning `null` or an empty list?

**Comment by sazzad16** [comment]
@spmason Yes, Jedis returns null in the case you're asking. You can check [TransactionCommandsTest.watch()](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/TransactionCommandsTest.java#L102-L103) test in this repo for reference.

**Comment by spmason** [comment]
Thanks. It's good to have confirmation.

So then this issue could be explained by an overlapping transaction on the watched key?

**Comment by sazzad16** [comment]
@spmason In short, _could be_.
