### ISSUE TITLE
Consistent return among commands

### ISSUE THREAD

**Issue by sazzad16** [redis/jedis#2579]
There are commands that are (can be considered) similar. But there are inconsistencies among the return types of those commands. We may/should make those similar.

Some such methods are:
- `Set<String> zrandmember`, `List<String> hrandfield`

**Comment by yangbodong22011** [comment]
I have not seen the benefit of using Set (wrapping List) instead of using List directly. If so, please point out.

**Comment by sazzad16** [comment]
@yangbodong22011 IMO, your comment is more aligned with #2278

**Comment by yangbodong22011** [comment]
update in https://github.com/redis/jedis/issues/2278#issuecomment-878946050

**Comment by sazzad16** [comment]
Resolved by https://github.com/redis/jedis/commit/858c8051301854e8343eef66aa68c6b9dab1c328
