### ISSUE TITLE
please implement hello method!

### ISSUE THREAD

**Issue by startjava** [redis/jedis#2581]
please implement hello method!

**Comment by sazzad16** [comment]
@startjava feel free to craft a PR!

**Comment by sazzad16** [comment]
Duplicate of #2103

**Comment by startjava** [comment]
@sazzad16   2103  this issue on 24 Nov 2019   ,,now  2021 year  ,,,,but but what time the api release?

i use 
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>4.0.0-SNAPSHOT</version>
        </dependency>

no hello api !

**Comment by sazzad16** [comment]
@startjava until we get a good enough PR. Why don't you craft a PR? It'd be a great help.
