### ISSUE TITLE
Wrong version published

### ISSUE THREAD

**Issue by iNikem** [redis/jedis#2593]
Recently released 3.6.2 version seems to be published under wrong version:

From https://github.com/redis/jedis/runs/3075421615?check_suite_focus=true you can see:

`Installing /home/runner/work/jedis/jedis/target/jedis-jedis-3.6.2.jar to /home/runner/.m2/repository/redis/clients/jedis/jedis-3.6.2/jedis-jedis-3.6.2.jar`

Seems like `version=jedis-3.6.2` instead of `version=3.6.2`

**Comment by sazzad16** [comment]
@iNikem It is fixed now. Please check and let us know.

**Comment by iNikem** [comment]
@sazzad16 There is now a correct version, thank you :)

But can you try to remove the wrong version from Maven Central and its metadata as well? In our case we pull a list of all available versions from the repo to randomly test https://github.com/open-telemetry/opentelemetry-java-instrumentation with them. And this non-standard version number breaks our build and forces to have a workaround. Not a big deal, but it would be cleaner to remove wrong version.

**Comment by sazzad16** [comment]
@iNikem Let me see.

**Comment by iNikem** [comment]
Any luck with this, @sazzad16 ?

**Comment by sazzad16** [comment]
@iNikem No. After all other options, I asked to send an email. Hopefully an email was sent to Nexus yesterday. So there's that.

Do you know a "proper" way?

**Comment by iNikem** [comment]
I think that the "proper" way is to open an issue in https://issues.sonatype.org/projects/MVNCENTRAL/issues

**Comment by gkorland** [comment]
https://issues.sonatype.org/browse/OSSRH-71868

**Comment by gkorland** [comment]
```
 Sonatype policy prohibits the removal or any other modification of artifacts after they've been released. For details behind this long-standing policy, have a look at this section of our docs
```

**Comment by iNikem** [comment]
I see. Pity :( Thank you anyway, @sazzad16  and @gkorland for trying to solve this.
