### ISSUE TITLE
Excuse me, do you support redisbloom 

### ISSUE THREAD

**Issue by a364176773** [redis/jedis#2621]
### Expected behavior

I don’t seem to see any APIs that support redisbloom. 

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by dengliming** [comment]
You can use https://github.com/RedisBloom/JRedisBloom (base on jedis)

**Comment by a364176773** [comment]
> You can use https://github.com/RedisBloom/JRedisBloom (base on jedis)

thank you very much
