### ISSUE TITLE
ZRANGE support [BYSCORE|BYLEX] [REV] [LIMIT offset count] [WITHSCORES] option

### ISSUE THREAD

**Issue by startjava** [redis/jedis#2625]
ZRANGE key min max [BYSCORE|BYLEX] [REV] [LIMIT offset count] [WITHSCORES]

or use old api ,replace new that option?

thank you !

**Comment by yangbodong22011** [comment]
@startjava refer : 
```
Set<String> zrangeByScore(String key, String min, String max); // byscore
Set<String> zrangeByLex(String key, String min, String max); // bylex
Set<String> zrangeByScore(String key, double min, double max, int offset, int count); // limit offset count
Set<Tuple> zrangeByScoreWithScores(String key, double min, double max);  // withscores
```

**Comment by startjava** [comment]
杨哥 感谢 &nbsp;还是用原来的api &nbsp;我以为只用一个方法实现呢 &nbsp;这样也好 分散了 &nbsp;减少单一方法的复杂性



发自我的iPhone


------------------ Original ------------------
From: Yang Bodong ***@***.***&gt;
Date: Wed,Sep 15,2021 10:12 AM
To: redis/jedis ***@***.***&gt;
Cc: startjava ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [redis/jedis] has ZAddParam support [BYSCORE|BYLEX] [REV] [LIMIT offset count] [WITHSCORES] option plan?? (#2625)





 
@startjava refer :
 Set<String&gt; zrangeByScore(String key, String min, String max); // byscore Set<String&gt; zrangeByLex(String key, String min, String max); // bylex Set<String&gt; zrangeByScore(String key, double min, double max, int offset, int count); // limit offset count Set<Tuple&gt; zrangeByScoreWithScores(String key, double min, double max);  // withscores  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sazzad16** [comment]
@yangbodong22011 Redis has this [ZRANGE](https://redis.io/commands/zrange) command and arguments, so it would be great to include in Jedis as well. Reopening this issue, in case someone wants to give it a shot and create a PR.
