### ISSUE TITLE
Please add special stream IDs '-' (min) and '+' (max) in StreamEntryID

### ISSUE THREAD

**Issue by mcekovic** [redis/jedis#2648]
### Expected behavior

Please add special stream IDs '-' (min) and '+' (max) in Jedis StreamEntryID used in XRANGE, XREVRANGE and XPENDING.

### Actual behavior

Currently there are only 3 special sub-classes in redis.clients.jedis.StreamEntryID:

NEW_ENTRY: '*'    (used in XADD)
LAST_ENTRY: '$'    (used in XREAD)
UNRECEIVED_ENTRY: '>'   (used in XREADGROUP)

What is lacking:
MIN_ENTRY: '-'   (used in XRANGE, XREVRANGE and XPENDING)
MAX_ENTRY: '+'   (used in XRANGE, XREVRANGE and XPENDING)

### From Redis original documentation

> ### Querying by range: XRANGE and XREVRANGE
> 
> To query the stream by range we are only required to specify two IDs, start and end. The range returned will include the elements having start or end as ID, so the range is inclusive. The two special IDs - and + respectively mean the smallest and the greatest ID possible.

...

> ### Special IDs in the streams API

...

> The first two special IDs are - and +, and are used in range queries with the XRANGE command. Those two IDs respectively mean the smallest ID possible (that is basically 0-1) and the greatest ID possible (that is 18446744073709551615-18446744073709551615). As you can see it is a lot cleaner to write - and + instead of those numbers.

**Comment by sazzad16** [comment]
1. null is equivalent to '-' for min
2. null is equivalent to '+' for max

**Comment by mcekovic** [comment]
Thanks, this is nice to know, but maybe better would be to have explicit constants, to be more aligned to native Redis APIs.
