### ISSUE TITLE
SetParams should implement equals and hashcode

### ISSUE THREAD

**Issue by JeffAtDeere** [redis/jedis#2687]
### Expected behavior

SetParams should implement equals and hashcode. Without those, verifying mock interactions is harder. For example,
```
    @Test
    void test() {
        Jedis jedis = Mockito.mock(Jedis.class);
        jedis.set("key", "value", new SetParams().ex(3600L));
        Mockito.verify(jedis).set("key", "value", new SetParams().ex(3600L));
    }
```
fails with
```
Argument(s) are different! Wanted:
jedis.set("key", "value", [ex, 3600]);
-> at x.test(x.java:89)
Actual invocations have different arguments:
jedis.set("key", "value", [ex, 3600]);
-> at x.test(x.java:88)
```
because of a lack of equals and hashcode on SetParams.

To write a passing test, one has to:
```
    @Test
    void test() {
        Jedis jedis = Mockito.mock(Jedis.class);
        jedis.set("key", "value", new SetParams().ex(3600L));
        Mockito.verify(jedis).set(eq("key"), eq("value"), argThat((SetParams p) -> p.getParam("ex").equals(3600L)));
    }
```
and know that the internal structure of SetParams is a map, that the private key is "ex", and that getParam's returned &lt;T&gt; is actually a Long.

#### Jedis version:
3.7.0

#### Redis version:
N/A

#### Java version:
11

#### Mockito version:
3.3.3

**Comment by Lcarrot** [comment]
Hello, can i try to solve this issue?
