### ISSUE TITLE
ambiguous reference to overloaded definition for .setex

### ISSUE THREAD

**Issue by raokrutarth** [redis/jedis#2708]
### Expected behavior

Should be able to use .setex without compilation error

### Steps to reproduce:

```scala
def set(key: String, value: String, exSec: Int = 0) = Try {
    val r: Jedis = redisPool.getResource()
    if (exSec > 0) {
      r.setex(keyspace + key, exSec, value)
    } else {
      r.set(keyspace + key, value)
    }
  }
```

Gives the following compilation error:

```text
[error] /home/dev/work/webapp/app/shared/Cache.scala:31:9: ambiguous reference to overloaded definition,
[error] both method setex in class Jedis of type (x$1: String, x$2: Long, x$3: String)String
[error] and  method setex in trait JedisCommands of type (x$1: String, x$2: Int, x$3: String)String
[error] match argument types (String,Int,String)
[error]       r.setex(keyspace + key, exSec, value)
[error]         ^
```

### Redis / Jedis Configuration

` val redisPool = new JedisPool(AppConfig.settings.redis.url)`
URL points to a single EC2 instance hosting redis.

#### Jedis version:
`"redis.clients" % "jedis" % "3.7.0"`

#### scala version:
`scalaVersion := "2.12.10"`

**Comment by sazzad16** [comment]
@raokrutarth check this https://stackoverflow.com/questions/27336753/how-to-solve-ambiguous-reference-to-overloaded-definition

**Comment by raokrutarth** [comment]
That worked. Thank you @sazzad16
