### ISSUE TITLE
After updating Jedis to the latest in git, EOF issues when parsing pubsub messages.

### ISSUE THREAD

**Issue by momomo** [redis/jedis#2732]
There is no easy way to explain it. 

It appears as if the bytes are not there in their entirety when onPMessage is called. 

A string is no longer identifiable due to missing bits? 

Anyhow, same code works when I reverse.

**Comment by sazzad16** [comment]
@momomo Could you please provide a piece of code that isn't working in latest master but works you reverse?

**Comment by sazzad16** [comment]
Closed due to inactivity.
