### ISSUE TITLE
Transaction can't get result in jedis 4.0.0

### ISSUE THREAD

**Issue by leonchen83** [redis/jedis#2764]
### Expected behavior

get result normally like jedis 3.7.1

### Actual behavior

can't get result in jedis 4.0.0

### Steps to reproduce:

redis version : 6.2
```
127.0.0.1:6379> zadd test 1 a 2 b 3 c 4 d
```

in jedis 3.7.1 code like following
```
Jedis jedis = new Jedis("127.0.0.1", 6379);
Transaction transaction = jedis.multi();
Response<Set<byte[]>> r = transaction.zrevrangeByScore("test".getBytes(), "4".getBytes(), "-inf".getBytes(), 0, 2);
transaction.exec();
r.get().forEach(e -> System.out.println(new String(e)));
```
console log like following
```
d
c
```

in jedis 4.0.0 code like following
```
Jedis jedis = new Jedis("127.0.0.1", 6379);
Transaction transaction = jedis.multi();
Response<List<byte[]>> r = transaction.zrevrangeByScore("test".getBytes(), "4".getBytes(), "-inf".getBytes(), 0, 2);
transaction.exec();
r.get().forEach(e -> System.out.println(new String(e)));
```

console log print nothing!

#### Jedis version:

4.0.0

#### Redis version:

6.2.0

#### Java version:

java 11

**Comment by yangbodong22011** [comment]
@leonchen83 Hi, thanks for your report, it's a bug, I will fix it ASAP.

**Comment by startjava** [comment]
zrevrangeByScore is a deprecated command
