### ISSUE TITLE
add project for redis 7

### ISSUE THREAD

**Issue by zeekling** [redis/jedis#2790]
i found redis support some commands for redis7 on branch unstable,can we add project for redis 7 like this:

![image](https://user-images.githubusercontent.com/17929800/147843262-04d919c9-c5e8-43fd-8151-f3e2b7454129.png)

**Comment by zeekling** [comment]
https://github.com/redis/jedis/issues/2795

**Comment by sazzad16** [comment]
@zeekling As you see, _project_ feature is hardly managed here. At this moment, I don't see any value of creating another one for Redis 7.

**Comment by zeekling** [comment]
> @zeekling As you see, _project_ feature is hardly managed here. At this moment, I don't see any value of creating another one for Redis 7.

OK, I see.
