### ISSUE TITLE
support LMPOP numkeys key

### ISSUE THREAD

**Issue by zeekling** [redis/jedis#2791]
https://redis.io/commands/lmpop

**Comment by zeekling** [comment]
supported in https://github.com/redis/jedis/pull/2796

**Comment by Razi007** [comment]
@zeekling   @sazzad16  interested to work here.Please suggest if i need to refer any code.

**Comment by Razi007** [comment]
@zeekling @sazzad16 Please assign it to me.Will raise a PR in a while code is completed almost.Working fine just writing test cases.

**Comment by sazzad16** [comment]
> Please assign it to me.

@Razi007 Not necessary. You can work on your own without assignment.

**Comment by Akaame** [comment]
@Razi007 have you started working on this?

**Comment by Razi007** [comment]
@Akaame Yes i am working on it.Will raise asap.

**Comment by Razi007** [comment]
@sazzad16 raise a PR https://github.com/redis/jedis/pull/2796/files. Please review once and let me know  is approach  correct.Please suggest if any improvement needed.Currently Working on test cases and checking if we should add lmpop in other interfaces as well.
