### ISSUE TITLE
How can I flush db when using JedisPooled in jedis 4.0

### ISSUE THREAD

**Issue by leonchen83** [redis/jedis#2798]
### Expected behavior

can flushdb in JedisPooled class

### Actual behavior

no such method in JedisPooled

### Steps to reproduce:

```
		try(JedisPooled jedis = new JedisPooled("127.0.0.1", 6379)) {
			// jedis.flushAll(); ? no such method 
		}
		
		try(Jedis jedis = new Jedis("127.0.0.1", 6379)) {
			jedis.flushAll();
		}
```

### Redis / Jedis Configuration

default configuration

#### Jedis version:

4.0.1

#### Redis version:

6.2.0

#### Java version:

java 11

**Comment by sazzad16** [comment]
@leonchen83 There several (but not direct) ways. BE CAREFUL WHAT YOU'RE DOING.

```
		try(JedisPooled jedis = new JedisPooled("127.0.0.1", 6379)) {
			new Jedis(jedis).flushAll();
		}
		try(JedisPooled jedis = new JedisPooled("127.0.0.1", 6379)) {
			jedis.sendCommand(Protocol.Command.FLUSHALL);
		}
```
