### ISSUE TITLE
Support for dynamically reload  SSL certificate and key?

### ISSUE THREAD

**Issue by ExploreNcrack** [redis/jedis#2804]
Is it possible to dynamically reload the SSL certificate and key for the existing connection so that we can avoid making new connection when certificate and key files have changed?

**Comment by sazzad16** [comment]
@ExploreNcrack No.

**Comment by ExploreNcrack** [comment]
> @ExploreNcrack No.

So when certificate and key files have changed, all I can do is just to replace the reference of the existing connection with a new connection?

**Comment by sazzad16** [comment]
@ExploreNcrack Yes.

**Comment by ExploreNcrack** [comment]
Alright thank you!

**Comment by Hakky54** [comment]
I think it might be possible. I just analysed the client and it looks like the JedisPool has an option to set the SSLSocketFactory. See here for the code snippet:

```java
SSLFactory sslFactory = SSLFactory.builder()
    .withSwappableIdentityMaterial()
    .withIdentityMaterial("identity.jks", "password".toCharArray())
    .withSwappableTrustMaterial()
    .withTrustMaterial("truststore.jks", "password".toCharArray())
    .build();

JedisPooled jedisPooled = new JedisPooled(url, sslFactory.getSslSocketFactory(), sslFactory.getSslParameters(), sslfactory.getHostnameVerifier());
```

After some time when you have the new keystore/truststore either from an endpoint, or changes on the file system or from somewhere else, you can execute the following snippet to update the server ssl without the need of restarting it:

```java
// swap identity and trust materials and reuse existing server
KeyManagerUtils.swapKeyManager(sslFactory.getKeyManager().get(), anotherKeyManager);
TrustManagerUtils.swapTrustManager(sslFactory.getTrustManager().get(), anotherTrustManager);

// Cleanup old ssl sessions by invalidating them all. Forces to use new ssl sessions which will be created by the swapped KeyManager/TrustManager
SSLSessionUtils.invalidateCaches(sslFactory.getSslContext());
```

In the above code example you need to replace the second parameter of the swapKeyManager and swapTrustManager method with the newly created KeyManager and TrustManager when you have new certificates either in pem, jks, p12 or binary certificates.

See here for the documentation of this option: [Swapping KeyManager and TrustManager at runtime](https://github.com/Hakky54/sslcontext-kickstart#support-for-swapping-keymanager-and-trustmanager-at-runtime)

This option is available within the following library here: [GitHub - SSLContext Kickstart](https://github.com/Hakky54/sslcontext-kickstart) which I made, hopefully you guys will like it and hopefully it will make it easier for you all to set it up.
