### ISSUE TITLE
Log sentinel +odown/+sdown messages for alerts

### ISSUE THREAD

**Issue by abhisheksurve45** [redis/jedis#2809]
### Question

Hi, I'm using spring data redis along with jedis to connect to a sentinel redis configuration. Was wondering if there's any way we from the Java code can listen to the sentinel messages of master failuers (+odown/+sdown) so that we can call appropriate alerts.

#### Jedis version:
3.8.0

#### Redis version:
6.x

#### Java version:
JDK 8

#### Spring data redis version:
2.5.x

**Comment by abhisheksurve45** [comment]
@sazzad16  Can you please help here. Thanks.

**Comment by sazzad16** [comment]
@abhisheksurve45 Sorry, I'm not aware of such solution.
