### ISSUE TITLE
Sentinel Support in Jedis 4.x

### ISSUE THREAD

**Issue by shannonantony** [redis/jedis#2847]
Hi,

Will you have Sentinel support in Jedis 4.x soon?. If not, what is the work around for now to connect via Sentinels?

Please advise.

Appreciate your help

thanks

Jay

**Comment by sazzad16** [comment]
@shannonantony Jedis 4.x has Sentinel support just as 3.x/older versions.

**Comment by shannonantony** [comment]
Hi,

I am trying to use UnifiedJedis class to create a prototype for indexing and searching JSON documents. But I am kind of lost on how do I get a Connection object from JedisSentinelPool and pass it to UnifiedJedis class.

I am testing with the sample test program from github.

thanks for your help

Jay

public void doIt1() {
		Gson gson = new Gson();
		UnifiedJedis client = new JedisPooled(new HostAndPort("IP", 6379));

		// JedisCluster client = new JedisCluster(sentinels);

		Student maya = new Student("Maya", "Jayavant");
		// client.jsonSet("student:111", maya);
		//client.jsonSet("student:111", gson.toJson(maya));
		client.jsonSetWithEscape("student:111", maya);
		System.out.println(client.jsonGet("student:111"));

		// Student oliwia = new Student("Oliwia", "Jagoda");
		// client.jsonSet("student:112", oliwia);

		client.ftDropIndex("student-index");
		Schema schema = new Schema().addTextField("$.firstName", 1.0).addTextField("$" + ".lastName", 1.0);
		IndexDefinition rule = new IndexDefinition(IndexDefinition.Type.JSON).setPrefixes(new String[] { "student:" });
		client.ftCreate("student-index", IndexOptions.defaultOptions().setDefinition(rule), schema);

		Query q = new Query("@\\$\\" + ".firstName:Maya*");
		// Query q = new Query();
		SearchResult mayaSearch = client.ftSearch("student-index", q);

		System.out.println("result size" + mayaSearch.getTotalResults());

	}

**Comment by sazzad16** [comment]
@shannonantony This has been discussed here #2754

**Comment by sazzad16** [comment]
Dupe #2754
