### ISSUE TITLE
Jedis class doesn't implement RedisJSON commands

### ISSUE THREAD

**Issue by njibhu** [redis/jedis#2856]
# Description of the issue

With the release of Jedis 4.0.0, RedisJSON commands have been added to many Jedis subclasses, such as `TransactionBase`, `UnifiedJedis` or `Pipeline`.

It would be nice to also be able to access these commands from the base `Jedis` class.

**Comment by sazzad16** [comment]
@njibhu There's no such plan ATM. Consider using UnifiedJedis.
