### ISSUE TITLE
Strange issue with UnifiedJedis.jsonMGet

### ISSUE THREAD

**Issue by shannonantony** [redis/jedis#2910]
For a sample application, I am loading redisjson docs using Jedis 4 api.

while reading json docs using the code below, I get the json documents as an array.

List<JSONArray> jsonArray = client.jsonMGet("id:385855639", "id:387889161");

But when I create a String concat as below and pass it to jsonMGet, it does not work.

String idString = id:385855639" + "," + "id:387889161";

List<JSONArray> jsonArray = client.jsonMGet(idString);

I get jsonArray as NULL

I really need your help to figure this out. This does not make any sense to me.

Appreciate your help

thanks

Jay

#### Jedis version:
Jedis 4.1.1
#### Redis version:
redis-6.2.4
#### Java version:

JDK11

**Comment by yangbodong22011** [comment]
@shannonantony The jsonMget signature is as follows
```
jsonMGet(String... keys)
```
you need pass key one by one, just like：
```
List jsonArray = client.jsonMGet("id:385855639", "id:387889161");
```
while
```
String idString = “id:385855639" + "," + "id:387889161";
List jsonArray = client.jsonMGet(idString);
```
This is equivalent to getting a key with the name: "id:385855639,id:387889161", but obviously, the key with this name does not exist in your database, so NULL is returned.

**Comment by shannonantony** [comment]
Thanks a lot for the clarification. I am good. code is working now.

**Comment by yangbodong22011** [comment]
@shannonantony You're welcome, if you have no other questions about this, please close the issue.
