### ISSUE TITLE
Question: Connection pool only refreshed when `+switch-master` is received

### ISSUE THREAD

**Issue by barbasa** [redis/jedis#2911]
### Expected behavior

When using Sentinels, if a new master is elected, normally the Sentinel broadcast a `+switch-master` message which is used by the `JedisSentinelPool` to refresh the connection pool. This works perfectly fine, however, in some cases the Sentinels don't emit a `+switch-master` message when promoting a new master.

This is the case of, for example, (re)provisioning Redis using [this](https://github.com/spotahome/redis-operator) Redis operator.

In this case a `+reset-master` message is sent to set the new master when starting up the cluster.

I have raised [an issue](https://github.com/spotahome/redis-operator/issues/373) for the operator itself, however I was trying to understand:
1. Is the client listening to the `+switch-master` only by design?
2. Why would it be wrong listening to any other message, for example `+reset-master`?
3. Is there any way to recover from the situation described in [here](https://github.com/spotahome/redis-operator/issues/373) without restarting the server? i.e.: the master is changed but the client didn't update the connection pool, hence it needs to be restarted.

**Comment by sazzad16** [comment]
1. As far as I understand, yes.
2. May be not wrong. Did you try asking [Redis devs](https://github.com/redis/redis/)?
3. I don't see any other way ATM. BTW, why/how this is happening should also be checked.
