### ISSUE TITLE
About hGetAll return result inconsistent problem.

### ISSUE THREAD

**Issue by HelleWorld1** [redis/jedis#2933]
### Expected behavior
when me use **redis.clients.jedis.PipelineBase#hgetAll(byte[])** loop n times，return result is inconsistent。

if my hash have values: a->b，c->d，e->f
return result for example:
frist:
a->b
e->f
c->d

second:
e->f
c->d
a->b

**so,3 times return result is different. I am very suspicious.**

### Actual behavior
According to the above,3 times return result is different.

### Steps to reproduce:
I download the jedis source.
I think lead to the result reason is `redis.clients.jedis.util.JedisByteHashMap.JedisByteEntry` not override hashCode() and equals().

When we need result, we will invoke `redis.clients.jedis.util.JedisByteHashMap#entrySet`,  `hashSet.add(new JedisByteEntry(entry.getKey().data, entry.getValue()));` will let the result is inconsistent.
**When I override JedisByteEntry hashCode()**
```java
  private static final class JedisByteEntry implements Entry<byte[], byte[]> {
    private byte[] value;
    private byte[] key;

    public JedisByteEntry(byte[] key, byte[] value) {
      this.key = key;
      this.value = value;
    }

    @Override
    public byte[] getKey() {
      return this.key;
    }

    @Override
    public byte[] getValue() {
      return this.value;
    }

    @Override
    public byte[] setValue(byte[] value) {
      this.value = value;
      return value;
    }

    @Override
    public int hashCode() {
      return Arrays.hashCode(key);
    }
  }
```
**the result is consistent.**

### Here is my test program
```java
package redis.clients.jedis.hashtest;

import redis.clients.jedis.util.JedisByteHashMap;

import java.util.*;

public class HashHGetAllTest {

    public static void main(String[] args) {
        List<byte[]> lists = new ArrayList<>();
        lists.add(new byte[]{1, 3, 4});
        lists.add(null);
        lists.add(new byte[]{14, 5, 1});
        lists.add(null);
        lists.add(new byte[]{7, 8, 5});
        lists.add(null);
        lists.add(new byte[]{1, 0, 4});
        lists.add(null);
        for (int i = 0; i < 10; i++) {
            final Map<byte[], byte[]> build = build(lists);
            build.forEach((k, v) -> {
                System.out.println(Arrays.toString(k));
            });
            System.out.println("----");
        }
    }

    //redis.clients.jedis.Builder#build
    public static Map<byte[], byte[]> build(List<byte[]> data) {
        final List<byte[]> flatHash = (List<byte[]>) data;
        final Map<byte[], byte[]> hash = new JedisByteHashMap();
        final Iterator<byte[]> iterator = flatHash.iterator();
        while (iterator.hasNext()) {
            hash.put(iterator.next(), iterator.next());
        }

        return hash;
    }
}
```
**result is:**
[14, 5, 1]
[1, 0, 4]
[7, 8, 5]
[1, 3, 4]
----
[1, 3, 4]
[14, 5, 1]
[1, 0, 4]
[7, 8, 5]
----
[14, 5, 1]
[7, 8, 5]
[1, 3, 4]
[1, 0, 4]
----
[14, 5, 1]
[1, 0, 4]
[7, 8, 5]
[1, 3, 4]
----
[7, 8, 5]
[1, 0, 4]
[14, 5, 1]
[1, 3, 4]
----
[1, 3, 4]
[7, 8, 5]
[14, 5, 1]
[1, 0, 4]
----
[7, 8, 5]
[1, 0, 4]
[14, 5, 1]
[1, 3, 4]
----
[1, 3, 4]
[1, 0, 4]
[7, 8, 5]
[14, 5, 1]
----
[1, 3, 4]
[1, 0, 4]
[14, 5, 1]
[7, 8, 5]
----
[1, 3, 4]
[1, 0, 4]
[7, 8, 5]
[14, 5, 1]
----

**Comment by HelleWorld1** [comment]
When I invoke initial redis command `HGETALL xxxKey` n times, result is consistent.

**Comment by sazzad16** [comment]
@HelleWorld1 Please notice that it returns a `Map`, not a `SortedMap`. 

You're always getting the same contents according to the contract of `Map`. Yes, in different orders, but this is not the contract of `Map` (but `SortedMap`). There is nothing inconsistent/suspicious is happening in your example.
