### ISSUE TITLE
Method name is not standardized (clientSetname->clientSetName)

### ISSUE THREAD

**Issue by shenningfly** [redis/jedis#2939]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Method name in connection class is not standardized ,

**Comment by sazzad16** [comment]
@shenningfly Yeah, there are some discrepancies. Wanna help out by crafting a PR?

**Comment by shenningfly** [comment]
ok。

**Comment by sazzad16** [comment]
If anyone is interested in working on this, please don't delete existing methods. Create new methods and add `@Deprecated` tag to existing ones (preferably with JavaDoc indicating the new method).
