### ISSUE TITLE
Unified return types for Search and JSON

### ISSUE THREAD

**Issue by dmaier-redislabs** [redis/jedis#2942]
Hi again,

this is again more a question about a potential usability enhancement and not about a functional defect:

* client.jsonGet returns a JsonObject (I believe that Gson is the current default)
* client.ftSearch returns a collection of Document

Would it be possible to align the return types? Guess a Document can be represented as a JSONObject.

Regards,
David

**Comment by sazzad16** [comment]
@dmaier-redislabs It is unlikely that Jedis would convert something to JSON that is not a JSON.

**Comment by dmaier-redislabs** [comment]
Can we discuss this please a bit before closing the ticket? I am pretty sure that other Redis libraries return it in a more unified way. I could be wrong, but redis-py, for instance, returns in both cases a Dictionary which feels more seamless for me.

**Comment by sazzad16** [comment]
(We are discussing.)

Does it mean that you prefer to get a Dictionary when it is a JSON object?

**Comment by dmaier-redislabs** [comment]
No, this was just an example. If you use RediSearch with JSON, then it returns the result as JSON string (not a single string, but a string that contains the JSON object), whereby the actual result depends on the RETURN clause of the query. So the question is if it makes usability-wise sense to return a JSON object. We could embed this object also into the Document.

**Comment by sazzad16** [comment]
It makes sense but not possible. A client (Jedis) needs to know the data type from either command or response. As the same command can be applied on both Hash and Json, command is not helpful. The response is not helpful as well because RediSearch doesn't give any hint in response.

**Comment by dmaier-redislabs** [comment]
The only hint that I found was that the response contains the JSON path as the field of the document. This path starts with `$.`.

**Comment by sazzad16** [comment]
The go to use case would be to use entire JSON but in this case it's `$`.

Again, this means that users can't use `$` in their hashes (at least when using with search). This involves strong documentation and training.

Also, if we decide to change that we must not do it in a non-major release.
