### ISSUE TITLE
How to add field with an alias to a RediSearch schema?

### ISSUE THREAD

**Issue by dmaier-redislabs** [redis/jedis#2943]
How can someone use `FT.CREATE ... SCHEMA $.myfield AS myfield TEXT ...` via the search.Schema class?

I tried to use `schema.addTextFiel(myfield)`, but this doesn't have any option to pass an alias. Such field aliases are useful when using RediSearch and RedisJSON together (e.g., less escaping of `$.`)

**Comment by dmaier-redislabs** [comment]
It's possible, but I didn't find the solution intuitive. There are Field wrapper classes like TagField, TextField and so on. Those wrapper classes allow to pass Fieldname instance over. A FieldName instance has the field name and the alias as the arguments.

Here some usability considerations:

* I like the fluent interface for building an instance of a Schema. Each add*Field method returns the Schema which allows to chain the construction. Aligned with this fluent approach would be something like `schema.addTagField(...).as(...).addNumericField(...).as(...)`. 
* The wrapper class NumericField seems to be missing. So if you want to use a numeric field with an alias, you would need to construct a Field instance by passing Schema.FieldType.NUMERIC as a parameter. This is inconsistent.

**Comment by sazzad16** [comment]
@dmaier-redislabs `schema.addTagField(...).as(...).addNumericField(...).as(...)` - Nice. Care to craft a PR?

**Comment by dmaier-redislabs** [comment]
Not sure if I will find the time for a PR. Currently focusing on using the client lib, more than contributing actively to it.
