### ISSUE TITLE
Support RESET command

### ISSUE THREAD

**Issue by sazzad16** [redis/jedis#2952]
RESET command that resets client connection state

Ref: redis/redis#7982

**Comment by ihaohong** [comment]
Hi, I create a pull request for this issue, please help review, thanks.

https://github.com/redis/jedis/pull/3015

**Comment by sazzad16** [comment]
@ihaohong Please remove the link to this issue from your commit.

**Comment by Razi007** [comment]
@sazzad16 is this issue still open, can i raise PR here

**Comment by sazzad16** [comment]
@Razi007 We already have a PR #3015. If you can do better than that, sure. Otherwise it's not necessary.
