### ISSUE TITLE
Jedis.java is too big，We should refactor this class

### ISSUE THREAD

**Issue by zeekling** [redis/jedis#2954]
Jedis.java is too big，We should refactor this class.

![image](https://user-images.githubusercontent.com/17929800/159170179-c5dea5cf-e9ff-4fc2-b2ed-998b68d88c2a.png)

**Comment by startjava** [comment]
So more big line number.oh my god.



发自我的iPhone


------------------ Original ------------------
From: 小令童鞋 ***@***.***&gt;
Date: Sun,Mar 20,2022 11:35 PM
To: redis/jedis ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [redis/jedis] Jedis.java is too big，We should refactor this class (Issue #2954)





 
Jedis.java is too big，We should refactor this class.
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
