### ISSUE TITLE
Json.Get response mismatch the cli

### ISSUE THREAD

**Issue by cjdxhjj** [redis/jedis#2957]
### Expected behavior
jedisPooled.jsonGet(key, new Path2("$")) return an jsonobject

Write here what you're expecting ...
the cli json.get key $ return an jsonobject, but the jedis return an jsonarray
### Actual behavior

Write here what happens instead ...
![image](https://user-images.githubusercontent.com/5616997/160077006-73cd0f8a-3258-48e4-b6f4-ea9a53a70968.png)
![image](https://user-images.githubusercontent.com/5616997/160077344-dc6e4a70-0ce8-4a0f-9ed1-e333f8abc76a.png)
![image](https://user-images.githubusercontent.com/5616997/160077539-944e436a-bc33-4c73-9ac0-86fdbaebf3c3.png)

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.construct an jedis poll object  new JedisPooled(new GenericObjectPoolConfig(), host, port, Protocol.DEFAULT_TIMEOUT, password);
2.use the jsonget with path $ jedisPooled.jsonGet(key, new Path2("$"))

#### Jedis version:
4.2.0
#### Redis version:
![image](https://user-images.githubusercontent.com/5616997/160078422-9633317e-64fe-4a0a-8338-2fb519ee0275.png)
![image](https://user-images.githubusercontent.com/5616997/160078439-6fc11799-6196-4913-813d-0cad54d30873.png)

#### Java version:
jdk 11

**Comment by sazzad16** [comment]
@cjdxhjj Your Jedis method and cli command are not equivalent.

Equivalent cli command for `jsonGet(key, new Path2("$"))` method is `json.get key $`.

Equivalent Jedis method for `json.get key` command is `jsonGet(key)`.

**Comment by cjdxhjj** [comment]
thanks, that was my mistake

**Comment by sazzad16** [comment]
glad to help :)
