### ISSUE TITLE
For redisearch, How to create an index in the cluster？

### ISSUE THREAD

**Issue by wxzhou-gis** [redis/jedis#2965]
I created a redis cluster with three masters and three slaves, using **JedisCluster.ftCreate** reported an exception while creating the index.
   **redis.client.jedis.exceptions.JedisDataException: READONLY You can't write against a read only replica.**
    How should we create indexes for redis clusters?

**Comment by sazzad16** [comment]
@wxzhou-gis Could you please give us more information about your cluster configuration?

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！

**Comment by wxzhou-gis** [comment]
I'm very sorry for the late reply. redis. Conf is configured as follows：
**bind XXX.XXX.XXX.XXX 
protected-mode no
daemonize yes
cluster-enabled yes
cluster-node-timeout 5000
appendonly yes
appendfsync always 
loadmodule /usr/lib/redis/modules/rejson.so
loadmodule /usr/lib/redis/modules/redisearch.so**

**Comment by wxzhou-gis** [comment]
Hi,when can I get the repaired version?

**Comment by wxzhou-gis** [comment]
Thank you very much.
