### ISSUE TITLE
Error register jdbc on Dbeaver

### ISSUE THREAD

**Issue by alecvinent** [redis/jedis#2967]
### Expected behavior

I'm trying to register jedis as a JDBC driver on DBeaver, but I'm getting this error 
`class redis.clients.jedis.Jedis cannot be cast to class java.sql.Driver`

### Actual behavior

I'm getting this error 
`class redis.clients.jedis.Jedis cannot be cast to class java.sql.Driver`

#### Jedis version: 
4.2.1

#### Redis version:
Ubuntu: 5.0.7

**Comment by sazzad16** [comment]
@alecvinent Jedis does not implement `java.sql.Driver`.
