### ISSUE TITLE
How to get the index list in Redisearch?

### ISSUE THREAD

**Issue by wxzhou-gis** [redis/jedis#2974]
**FT._ List** can obtain the existing index list in Redisearch. Which method can obtain similar functions in jedis? Or is there any method to judge whether the index is created?

**Comment by wxzhou-gis** [comment]
Ft.info has a premise，the index must be first created with FT.CREATE. If it is not created, the direct call will report an error.

**Comment by gkorland** [comment]
https://github.com/RediSearch/RediSearch/issues/2700#issuecomment-1091628547

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！
