### ISSUE TITLE
ClusterCommands in JedisCluster

### ISSUE THREAD

**Issue by Btjones711** [redis/jedis#2978]
### Expected behavior

To be able to use ClusterCommands with JedisCluster

### Actual behavior

In previous versions of Jedis we have been using ClusterCommands included in Jedis. After UnifiedJedis was introduced in 4.0.0 I have been updating everything to use this new UnifiedJedis setup with CommandObjects. These commands seem to only still be available with Jedis.

**Comment by sazzad16** [comment]
ClusterCommands are designed for a specific connection which is not guaranteed in UnifiedJedis.

Even if we try to execute ClusterCommands in _any_ node, most of the commands don't make sense in that perspective.

**Comment by Btjones711** [comment]
Makes sense! So would the advice be to continue to use Jedis for those commands?

Thanks!

**Comment by sazzad16** [comment]
> So would the advice be to continue to use Jedis for those commands?

Yes.
