### ISSUE TITLE
Weird latency issues unexpected

### ISSUE THREAD

**Issue by PedroMPagani** [redis/jedis#2980]
### Expected behavior

I'm expecting to not have latency issues on this case, because it just simply does not make any sense to me while running diagnostics on the Redis server and not show any latency issue, while on the application I have a high latency after some amount of messages.

### Actual behavior
Currently I'm running a Minecraft server that reports 1000 messages every 50ms(or a tick), and what happens is after some amount of these messages + some more messages unrelated, the packets start getting delayed, which is an actual very weird behavior to happen,  I am going to release an sample of the code which will contain most functions and I will provide actual debugs:

### Code:
https://github.com/PedroMPagani/Reports/tree/main/src/redisreport
# They also include the logs that I have, they're a small report and I can provide whatever is needed

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

1. When the messages byte size increases the delay starts.

### Redis / Jedis Configuration

Default config with tcp back log and client limit higher, the redis is connected locally to localhost

#### Jedis version:
4.2.1

#### Java version:
jdk 17

**Comment by sazzad16** [comment]
@PedroMPagani Can't say the exact reason but few suggestions:

1. `poolConfig.setMaxTotal(Integer.MAX_VALUE);` - use a sane value, i.e. 10000/100000/etc.
2. `poolConfig.setTestOnReturn(true);` - try `false` and see how it performs.
3. 
```
            try (Jedis jedis = jedisPool.getResource(); Pipeline pipeline = jedis.pipelined()){
                pipeline.publish(channel,message);
            }
```
You can simply do:
```
            try (Jedis jedis = jedisPool.getResource()){
                jedis.publish(channel,message);
            }
```
4.
```
            try (Jedis jedis = jedisPool.getResource()){
                jedis.subscribe(sub, names);
            }
```
Don't subscribe with objects from pool.
```
            try (Jedis jedis = new Jedis(...)){
                jedis.subscribe(sub, names);
            }
```

Let us know the update.

**Comment by PedroMPagani** [comment]
Hey @sazzad16, I did follow all of the suggestions, and yet the delay is still happening, I changed the pool configuration for ->

`
        GenericObjectPoolConfig<Jedis> poolConfig = new GenericObjectPoolConfig<>();
        poolConfig.setMaxTotal(1000000);
        poolConfig.setMaxIdle(80);
        poolConfig.setMinIdle(80);
        poolConfig.setTestOnReturn(false);
        poolConfig.setTestWhileIdle(false);
        poolConfig.setNumTestsPerEvictionRun(-1);
        poolConfig.setTimeBetweenEvictionRuns(Duration.ofMillis(30000));
        poolConfig.setMinEvictableIdleTime(Duration.ofMillis(60000));

`

**Comment by PedroMPagani** [comment]
I've added my redis.conf

https://github.com/PedroMPagani/Reports/blob/main/src/redisreport/redis.conf

**Comment by PedroMPagani** [comment]
I'm closing this issue since I've realized that I was not using a decompress algorithm and also that my network is 1Gib/s max while the amount of messages I was sending are 20k and their byte length was reaching 100k easily and 1kk on my benchmark tests, I just figured my network limit now, thank you for your help sazz! (I was really in doubt about registering the channel in the pool or not..)
