### ISSUE TITLE
where can I find the tutorial of transaction with pipeline?

### ISSUE THREAD

**Issue by polaris6** [redis/jedis#2983]
I searched for such a test case, but pipeline is not actually used: 
https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/commands/jedis/TransactionCommandsTest.java#L242

**Comment by sazzad16** [comment]
@polaris6 The `Transaction` class is backed by Pipelining under the hood. You don't need a separate transaction with pipeline.

The test that you're referring to tests the response of a command in Transaction while within incomplete pipelining [1] cannot be read [2].

[1] `t.exec();` completes the pipelining.
[2] Ends up to an IllegalStateException.

**Comment by polaris6** [comment]
Hi @sazzad16, thank you for the reply, let me try it on.

**Comment by polaris6** [comment]
Hi @sazzad16, I get an error `redis.clients.jedis.exceptions.JedisDataException: ERR EXEC without MULTI` when i execute code as follows: 
```java
  Transaction t = jedis.multi();
  for (String key : keys) {
      t.hgetAll(key);
  }
  List<Object> resp = t.exec();
```

Do you know how to handle it?

**Comment by sazzad16** [comment]
```
  Transaction t = jedis.multi();
  for (String key : keys) {
      t.hgetAll(key);
  }
  List<Object> resp = t.exec();
```

@polaris6 Only this specific code block can't produce that exception.
There can be other occurrences of t.exec(), t.discard(), t.close(), etc. which is causing this behavior.

**Comment by polaris6** [comment]
@sazzad16 Thank you for the reply, I'll look into it again.
