### ISSUE TITLE
Add CLUSTER SHARDS command

### ISSUE THREAD

**Issue by sazzad16** [redis/jedis#2984]
https://redis.io/commands/cluster-shards/

**Comment by yaopen4** [comment]
Hi!
I'd love to take this as my first issue

**Comment by sazzad16** [comment]
@yaopen4 You're welcome to give it a shot 😃

**Comment by wormogig** [comment]
Hello.
I don't really understand the status of the issue and opened PR for it.
If the issue is not relevant - write, I will close it.
