### ISSUE TITLE
jedis.clusterReplicas throw ClassCastException

### ISSUE THREAD

**Issue by buession** [redis/jedis#2989]
### Expected behavior

Return List<String> for Jedis.clusterReplicas。

### Actual behavior

Return String for Jedis.clusterReplicas

The following is an exception thrown when I execute jedis.ClusterReplicas(nodeId)

`Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to [B
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:262)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:252)
	at redis.clients.jedis.Jedis.clusterReplicas(Jedis.java:8588)`

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. jedis.clusterReplicas(nodeId)

**Comment by sazzad16** [comment]
@buession Thank you for finding it out. Redis [documentation](https://redis.io/commands/cluster-replicas/) states that

> The command returns data in the same format as [CLUSTER NODES](https://redis.io/commands/cluster-nodes).

which certainly is not the case here.

Will fix ASAP.
