### ISSUE TITLE
Support for missing RedisJSON commands

### ISSUE THREAD

**Issue by VytskaLT** [redis/jedis#2997]
It would be great if there was support for missing RedisJSON commands like `JSON.NUMINCRBY` or `JSON.NUMMULTBY`

**Comment by sazzad16** [comment]
JSON.NUMMULTBY is deprecated. So it won't be implemented.

**Comment by sazzad16** [comment]
[JSON.NUMMULTBY](https://redis.io/commands/json.nummultby/) is deprecated. It will not be implemented in Jedis.

JSON.NUMINCRBY is resolved by #3004
