### ISSUE TITLE
Extend support to all arguments of FT.AGGREGATE command

### ISSUE THREAD

**Issue by sazzad16** [redis/jedis#3044]
https://redis.io/commands/ft.aggregate/

**Comment by s-sathish** [comment]
Hi @sazzad16 Can this be closed ? I see all the arguments are now supported for FT.AGGREGATE command.
The extended one's are -
```
VERBATIM
TIMEOUT
PARAMS
DIALECT
```

**Comment by sazzad16** [comment]
@s-sathish We will.
