### ISSUE TITLE
Add support for the new RTS 1.8 reducers

### ISSUE THREAD

**Issue by chayim** [redis/jedis#3078]
New reducers outside of MIN, MAX, SUM have been added to RedisTimeSeries for 1.8. Adding support for a general string based reducer, or supporting the named reducers.

**Comment by sazzad16** [comment]
@chayim Are the reducers still limited to MRANGE and MREVRANGE commands? In that case, this is completed as we have String support. https://github.com/redis/jedis/blob/f7156ee76d61e14f3120190067961facf5725d08/src/main/java/redis/clients/jedis/timeseries/TSMRangeParams.java#L117

**Comment by chayim** [comment]
@ofirmos can you help out @sazzad16

**Comment by OfirMos** [comment]
Hi @sazzad16 ,
The reducer types in 1.8 are still only in mrange and mrevrange.
The reducer types are: max, min, sum, avg, count, range, std.p, std.s, var.p, var.s
