### ISSUE TITLE
ZDIFF, ZINTER and ZUNION do not preserve correct ordering of returned members

### ISSUE THREAD

**Issue by DonalEvans** [redis/jedis#3083]
### Expected behavior

The values returned by the `zdiff()`, `zinter()` and `zunion()` methods should preserve the ordering of the returned members.

### Actual behavior

The return type of `zdiff()`, `zinter()` and `zunion()` is a `Set` which does not preserve the ordering of the members.

### Steps to reproduce:

1. Add members with scores to a sorted set.
2. Call `zdiff()`, `zinter()` or `zunion()` on that set.
3. Observe that the members returned are in an arbitrary order rather than the order they are stored on the server.

Executing:
```
    jedis.zadd("key", 3, "a");
    jedis.zadd("key", 2, "b");
    jedis.zadd("key", 1, "c");

    System.out.println("ZDIFF result:" + jedis.zdiff("key"));
    System.out.println("ZINTER result:" + jedis.zinter(new ZParams(), "key"));
    System.out.println("ZUNION result:" + jedis.zunion(new ZParams(), "key"));
    System.out.println("Expected result:" + jedis.zrange("key", 0, -1));
```
Results in:
```
ZDIFF result:[a, b, c]
ZINTER result:[a, b, c]
ZUNION result:[a, b, c]
Expected result:[c, b, a]
```

This issue seems related to https://github.com/redis/jedis/issues/2579, which described some return types that should have been `List`s rather than `Set`s

#### Jedis version:
4.1.1
#### Redis version:
6.2.7
#### Java version:
JDK 8

**Comment by sazzad16** [comment]
A quick fix #3085 is in works. But the issue will be kept open to change respective methods to return `List` targeting next major release.
