### ISSUE TITLE
About the jedis cluster slot command causes the redis cluster load to become high and the application is unavailable

### ISSUE THREAD

**Issue by bozai111** [redis/jedis#3084]
### Expected behavior

In the case of abnormal network connection or reconnection of the jedis client, the execution of many cluster slots may be triggered from the jedis client. Executing the cluster slot command on a redis cluster with hundreds of nodes will further increase the CPU usage.How to control the performance impact of the jedis client executing the cluster slot command?

### Actual behavior

In the case of abnormal network connection or reconnection of the jedis client, the execution of many cluster slots may be triggered from the jedis client. Executing the cluster slot command on a redis cluster with hundreds of nodes will further increase the CPU usage.

#### Jedis version:
2.8.1 and 2.10.2

#### Redis version:
3.0.7

**Comment by sazzad16** [comment]
Github issues should be used to report bugs and for detailed feature requests. 
Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).

Please post general questions to Google Groups or Github discussions. 
These can be closed without response when posted to Github issues.

**Comment by sazzad16** [comment]
Github issues should be used to report bugs and for detailed feature requests. 
Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).

Please post general questions to Google Groups or Github discussions. 
These can be closed without response when posted to Github issues.

**Comment by sazzad16** [comment]
@bozai111 In one Jedis 3.x release, some sleep were added between retries which may slowdown the number of calls. Please use Jedis 4.2.3 or 3.9.0 and see if it improves performance. There is no complete solution for your issue within Jedis library at this moment.
