### ISSUE TITLE
jedisCluster.ftSearch cannot query all the data

### ISSUE THREAD

**Issue by wxzhou-gis** [redis/jedis#3096]
My Redis cluster is three masters and three slaves, first I  inserted ten pieces of data, then indexed, and then used jedisCluster.ftSearch to query, but can only query the data of one slot, can not find all the data that meets the conditions, what is the reason?

**Comment by angelo147** [comment]
@wxzhou-gis are you referring to a Redis OSS or Redis Enterprise installation?
Can you also give a small example of the commands you use to create and index and insert data?

As far as i know and have worked with Redisearch, distributed RediSearch is available as part of the Redis Enterprise.
You can see that is stated here, https://github.com/RediSearch/RediSearch.

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！

**Comment by wxzhou-gis** [comment]
I am not using redis OSS and installing redis enterprise. I am using the open source version of redis to build three masters and three slaves.

**Test Data：**
JSON.SET item:1 $ '{"type":"0001","flag":"01"}'
JSON.SET item:2 $ '{"type":"0001","flag":"02"}'
JSON.SET item:3 $ '{"type":"0001","flag":"03"}'
JSON.SET item:4 $ '{"type":"0001","flag":"04"}'
JSON.SET item:5 $ '{"type":"0001","flag":"05"}'
JSON.SET item:6 $ '{"type":"0001","flag":"06"}'
JSON.SET item:7 $ '{"type":"0001","flag":"07"}'
JSON.SET item:8 $ '{"type":"0001","flag":"08"}'
JSON.SET item:9 $ '{"type":"0001","flag":"09"}'
JSON.SET item:10 $ '{"type":"0001","flag":"10"}'

**Index:**
FT.CREATE itemIdx ON JSON SCHEMA $.type AS type TEXT $.flag as flag TEXT

**Search:**
FT.SEARCH itemIdx '@type:(0001)'

**Result:**
The result only returns the data in one of the nodes, but not all the qualified ones. The results obtained by using the jedis API jediscluster.ftsearch are the same, and not all the data.

Is there any other way to help me realize this query function? Return the qualified data of all nodes.

**Comment by wxzhou-gis** [comment]
@angelo147

**Comment by wxzhou-gis** [comment]
I compiled an OSS version using the redisearch source code. Now I can find all the data. Thank you.@angelo147

**Comment by wxzhou-gis** [comment]
I compiled an OSS version using the redisearch source code. Now I can find all the data. Thank you.@angelo147

**Comment by sazzad16** [comment]
https://github.com/redis/jedis/issues/3096#issuecomment-1207879812 

> ... Now I can find all the data. ...

**Comment by gszs1013** [comment]
> I compiled an OSS version using the redisearch source code. Now I can find all the data. Thank you.@angelo147

I have encountered a similar problem to yours. How did you operate this？

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！

**Comment by wxzhou-gis** [comment]
Recompile&nbsp;the redisearch source code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 中午1:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redis/jedis] jedisCluster.ftSearch cannot query all the data (Issue #3096)





  
I compiled an OSS version using the redisearch source code. Now I can find all the data. Thank ***@***.***
  
I have encountered a similar problem to yours. How did you operate this？
