### ISSUE TITLE
How to add password to JedisPooled

### ISSUE THREAD

**Issue by gulicheric** [redis/jedis#3101]
I have a hostname, port, and password with my Redis instance. How do I connect the passwords to the JedisPooled instance? 

I found this 

<br class="Apple-interchange-newline">[JedisPooled](https://javadoc.io/static/redis.clients/jedis/4.0.0/redis/clients/jedis/JedisPooled.html#JedisPooled-java.lang.String-int-java.lang.String-java.lang.String-)([String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true) host, int port, [String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true) user, [String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true) password)

But I do not know what the user part is.

**Comment by sazzad16** [comment]
This should be asked either in [Jedis Google Group](https://groups.google.com/g/jedis_redis) or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).

**Comment by sazzad16** [comment]
@gulicheric Just send `null` for user in JedisPooled(String host, int port, String user, String password).
