### ISSUE TITLE
 java.net.SocketTimeoutException: Read timed out on creating JedisCluster

### ISSUE THREAD

**Issue by srishtikeshari** [redis/jedis#3102]
### Expected behavior
JedisCluster being created.
not getting java.net.SocketTimeoutException: Read timed out while setting up JedisCluster

### Actual behavior

I have started redis server in cluster node on 6 ports and trying to create a JedisCluster with it. 
I get "java.net.SocketTimeoutException: Read timed out exception" on doing 
JedisCluster jedisCluster = new JedisCLuster(nodes);
![image](https://user-images.githubusercontent.com/41779515/183924302-7860d885-0954-491a-9b6f-c5d850afd1b9.png)

### Steps to reproduce:

Start redis-server on 6 ports in cluster mode. 
Conf file - 
port 7005
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 30000
protected-mode no

JedisCluster jedisCluster = new JedisCluster(nodes);

### Redis / Jedis Configuration
Cluster mode

#### Jedis version:
Jedis version - 4.2.0

#### Redis version:
Redis version v=7.0.0

#### Java version:
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode)

**Comment by sazzad16** [comment]
The information provided is not enough to inspect the issue. Provide the full stacktrace, including the 'Caused by' blocks. Also provide cluster status from redis-cli and how JedisCluster is being created.
