### ISSUE TITLE
JedisPool    SpringBoot    APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by bobo3306** [redis/jedis#3109]
> hello 

I had a problem using **jedispool**

When I set the properties for **jedispool** , my springboot application cannot start

this is my code

```java
@Configuration
public class JedisConfig
  {
    
    @Value( "${spring.redis.host}" )
    private String host;
    
    @Value( "${spring.redis.port}" )
    private int port;
    
    @Value( "${spring.redis.password}" )
    private String password;
    
    @Bean( "ThisJedisPool" )
    public JedisPool buildJedisPool()
      {
        JedisPool jedisPool = new JedisPool( host , port );
        JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setMaxTotal( 10 );
        jedisPoolConfig.setMaxIdle( 5 );
        jedisPoolConfig.setMinIdle( 2 );
        jedisPool.setConfig( jedisPoolConfig );
        return jedisPool;
      }
    
  }
```
then

![20220823085223](https://user-images.githubusercontent.com/93701868/186059150-76de8161-5f34-492c-ac40-333d231330f6.png)

This method has no problem during compilation

Please help me

>thank you

**Comment by bobo3306** [comment]
![image](https://user-images.githubusercontent.com/93701868/186061127-bff37bac-3d94-43aa-b889-4dc883ce8eb2.png)

I don't know where this dependence comes from

my SpringBoot version 2.5.14
jedis version 4.3.0-m1

**Comment by sazzad16** [comment]
Jedis 4 is supported in Spring 3. If you want use Spring 2.x, use Jedis 3.x with it.

**Comment by bobo3306** [comment]
thank you sir

**Comment by bobo3306** [comment]
thank you
