### ISSUE TITLE
JedisPubSub cannot support PING command

### ISSUE THREAD

**Issue by stillerrr** [redis/jedis#3114]
### Expected behavior

when I use the JedisPubSub to subscribe a channel, I use this JedisPubSub object to send a "ping" command, use the method ping() to make sure the cluster do not disconnect the connection after timeout.
![image](https://user-images.githubusercontent.com/35724820/186379688-79d6a6e8-641e-4b09-b571-2e80505fc384.png)

and then I can get the callback by onPong() method that I expected
### Actual behavior
I got a exception: java.lang.ClassCastException that byte[] cannot cast to List

this exception was thrown because redis return a byte[] of "PONG" as response, but JedisPubSub use client.getUnflushedObjectMultiBulkReply() to get response and this method would cast the response to List<Object>

![image](https://user-images.githubusercontent.com/35724820/186381160-2d7bac0a-a090-44be-abbe-95ca39d84198.png)

what reply by redis like this：
![image](https://user-images.githubusercontent.com/35724820/186381328-10ddeb71-d351-4216-9848-7130e7d2aad8.png)

This problem will also occur when I use the ping method: public void ping(String argument) 

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.  create a JedisPubSub object
2. subscribe a channel
3.  use this JedisPubSub object to send a "ping" command

**Comment by sazzad16** [comment]
@stillerrr 

I'd ask you to check thoroughly. In Publish-Subscribe (PubSub) mode, Redis replies with a two-elements array for each PING command. If the PING command is passed without an argument, the second element in the array is an empty string.

![image](https://user-images.githubusercontent.com/7600764/186393372-ecbf0538-fd0c-45c7-8781-b11dfff09a60.png)

---

I believe, the image you have provided is of general PING command which is different than PubSub PING command.

---

Most likely your Client/Connection is being used in multiple operations. While you're using a Client/Connection for `subscribe`, you must not use it elsewhere.

**Comment by sazzad16** [comment]
Closed due to inactivity.
