### ISSUE TITLE
jedis : 3.8.0 jedis.connection.getStatusCodeReply throwing Arraylist cannot be CAST to class

### ISSUE THREAD

**Issue by mamtananavati** [redis/jedis#3130]
### Expected behavior
Currently upgraded spring boot , spring-data-redis, jedis to latest libraries with jedis being at 3.8.0 and expected everything to work as before.

### Actual behavior

`redis.clients.jedis.JedisFactory - Error while validating pooled Jedis object.java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [B (java.util.ArrayList and [B are in module java.base of loader 'bootstrap')	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)	at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:384)	at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:214)	at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:745)`

### Steps to reproduce:

Upgraded libraries in our existing framework to use latest spring boot to 2.7.3 and spring-data-redis and jedis to below mentioned versions and started seeing the error above.

**Comment by mamtananavati** [comment]
Found a similar thread : https://github.com/spring-projects/spring-data-redis/issues/2382

**Comment by wangan0915** [comment]
hello,i meet this question too,How did you solve it。

**Comment by hesy007** [comment]
@sazzad16
