### ISSUE TITLE
How does jedis cluster use pipeline

### ISSUE THREAD

**Issue by huxiaofei658** [redis/jedis#3131]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by sazzad16** [comment]
JedisCluster does not use pipeline. This library has included ClusterPipeline class for that purpose.

**Comment by sazzad16** [comment]
@huxiaofei658 This post should have been created in Discussions.
