### ISSUE TITLE
redis.clients.jedis.BinaryJedisCluster#set(byte[], byte[], redis.clients.jedis.params.SetParams) does not return byte[]

### ISSUE THREAD

**Issue by maciejDun** [redis/jedis#3132]
### Expected behavior

redis.clients.jedis.BinaryJedisCluster#set(byte[], byte[], redis.clients.jedis.params.SetParams)
That method with SetParam GET should return byte[] instead of String.

### Actual behavior

redis.clients.jedis.BinaryJedisCluster#set(byte[], byte[], redis.clients.jedis.params.SetParams)
This method with SetParam GET returns String, which is previously encoded by redis.clients.jedis.util.SafeEncoder#encode(byte[]). There is no way to get original byte[] like from redis.clients.jedis.Connection#getBinaryBulkReply, hence we cannot decompress byte[], which was previously saved as compressed byte[] (String.getBytes("UTF-8") returns degradated byte[]).

### Steps to reproduce:

1. Set key with compressed value by GZIP.
2. Perform set with parameter GET: redis.clients.jedis.BinaryJedisCluster#set(byte[], byte[], redis.clients.jedis.params.SetParams).
3. Returned String contains degradated byte[] which doesn't match with byte[] that come from redis.clients.jedis.BinaryJedisCluster#get.

**Comment by sazzad16** [comment]
Mostly resolved by #3134.

We'd have to remove `SetParams#get()` for proper resolution.

**Comment by sazzad16** [comment]
`SetParams#get()` is deprecated, so it is targeted to be removed anyway.

https://github.com/redis/jedis/blob/ee012f8399bd61ebc9db8e76249408216756335f/src/main/java/redis/clients/jedis/params/SetParams.java#L92-L101 

We can take this issue as resolved by #3134
