### ISSUE TITLE
Pool resources not being killed - clients being kept active forever

### ISSUE THREAD

**Issue by z0mg** [redis/jedis#3146]
### Expected behavior

I'm expecting clients to be disconnected when closing a JedisPool (JedisPool#close).

### Actual behavior

Sometimes clients aren't disconnected. I make a new JedisPool instance, use a maxTotal config of 36, call **close** and repeat. 
After a while, redis logs report 38... 39... 45... 50... 300 clients. This keeps growing.

### Steps to reproduce:

Unfortunately I can't reproduce the issue. I've tried simplifying my mechanism and in synthetic tests it works. 

Was this a known problem at some point?

**Comment by sazzad16** [comment]
@z0mg Which Jedis version are you using?

Could you try a different version of commons-pool2?
