### ISSUE TITLE
Please close pipeline or multi block before calling this method

### ISSUE THREAD

**Issue by Valeronik** [redis/jedis#3163]
### Expected behavior

My simple code is here.

```
try (Jedis jedis = jedisPool.getResource()) {
    final Response<String> response;
            
    try (Transaction tx = jedis.multi()) {
        response = tx.hmset(key, hash);
        tx.pexpire(key, ttl);
        tx.exec();
    }
            
    responseValue = response.get();
}
```

If the connection to Redis is disconnected after multi(), then at the moment the response is received - response.get() - an exception is thrown: JedisDataException: Please close pipeline or multi block before calling this method.

I'm expecting a Redis connection error. Example:

> WARN  redis.clients.jedis.JedisFactory - Error while close
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer: socket write error

**Comment by sazzad16** [comment]
@Valeronik Your provided code is not reproducible. If what you are claiming were true, `tx.exec();` would throw JedisConnectionException. And as you are not catching the exception, your code is supposed not to reach `response.get()`.

---

BTW, according to current design of Jedis Transaction, the decision/action of what to do with the Response object(s) after an exception is for the users.

**Comment by Valeronik** [comment]
@sazzad16, The problem is with response.get(). If there are any problems with Redis, there is no data in the answer and is not set:
```
    public T get() {
        if (this.dependency != null && this.dependency.set && !this.dependency.built) {
            this.dependency.build();
        }

        if (!this.set) {
            throw new JedisDataException("Please close pipeline or multi block before calling this method.");
        }
        ...
```
That is, if for some reason, in exec() one of the responses is executed with an error, then this exception will be called in response.get()

**Comment by sazzad16** [comment]
@Valeronik Firstly, the code you provided is not part of Jedis 4.3.0 but Jedis 3.x.

Anyways, as I have already said,

> according to current design of Jedis Transaction, the decision/action of what to do with the Response object(s) after an exception is for the users.

So, it should be you (the user) who would handle Response objects and/or calling response.get().

This is the current design and if you have a better approach, feel free to [discuss](https://github.com/redis/jedis/discussions/new) or even create a [PR](https://github.com/redis/jedis/compare). Thanks!
