### ISSUE TITLE
Json set can't query by ftsearch

### ISSUE THREAD

**Issue by YOoOzi233** [redis/jedis#3171]
### Expected behavior

I want query a document in by ft.search

### Actual behavior

It seem dosen't working...,I only can query it by json.get

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.I create an searchIdx like
![image](https://user-images.githubusercontent.com/116061192/196359901-ac0ca503-bc33-4ada-a9de-8130ca0a3f1c.png)
2. And then I insert a data by
`JSON.SET am_eqp_mst_search:38fc5332c182487db2574eff222e5970 '$' '{"workflowMap":{},"mgrusrId":"null","tagCod":"null","searchIdx":"未打印,否,company,202200000007,test234,145757845,PC,件,IT,闲置,B1-1F,IT  R&D,user1,admin,固定资产,","addressId":"null","modistamp":1665988599000,"typeIdName":"IT","vhrCod":"null","eqpQty":1,"id":"38fc5332c182487db2574eff222e5970","alarmFlg":"null","rfidCod":"null","amousrIdName":"null","creastampName":1665224023000,"deptId":"cbaffdc75dd44e3091f15513a0c3fb95","eqpNot":"asdgas","secondTyp":"f2f5376fa3934589aa16b5dd48976ff2","serialCod":"null","unitIdName":"件","warehouseId":"null","logusrId":"null","origeqpId":"null","typeId":"9e2002bd95e04e4dacedd16f4e34f36b","status":"XZ","positionCod":"null","useusrIdName":"user1","shelfId":"null","shareFlgName":"否","creatorName":"admin","eqpmgrId":"null","printSta":"N","secondTypName":"PC","contCod":"null","ftypeId":"null","eqpCod":"202200000007","deptIdName":"IT  R&D","statusName":"闲置","unitId":"01","yearCnt":12.0,"assetAttributeName":"固定资产","creator":"9b0a85a09d4341608708972b0fcd9323","mgrusrIdName":"null","mantmodeId":"null","loglotCod":"null","printStaName":"未打印","rsNeedSave":false,"areaId":"2ff0e1cbf6594adcbe6a7b6e06a23cdd","isdelete":"N","amousrId":"null","groupId":"null","modifier":"9b0a85a09d4341608708972b0fcd9323","potypeId":"null","groupIdName":"null","barCod":"202200000007","poCod":"null","shareFlg":"N","areaIdName":"B1-1F","postId":"null","identityTyp":"PF","packboxId":"null","eqpuseDsc":"asgsd","deprFlg":"null","vendId":"null","projId":"null","propDsc":"null","brandSht":"null","addressDsc":"null","mnemCod":"null","organid":"1bcbb55c03d64ef4befe3325f60be8f6","mgrdeptIdName":"null","cityCod":"null","businessStateMap":{},"assetAttribute":"GDZC","gradeId":"null","organidName":"company","alarmFlgName":"null","eqpNam":"test234","mgrdeptId":"","lotCod":"145757845","creastamp":1665224023000,"amorgId":"null","useusrId":"49a00949d73b49b5b5bb5963206dbcc5","syseqpCod":"null"}'`
3.Then I try query it by 
`FT.SEARCH am_eqp_mst_search *`
It dosen't working.

4.But,when I query it by 
`JSON.GET am_eqp_mst_search:38fc5332c182487db2574eff222e5970`
I can get this data.

#### Jedis version:
4.3.0-m1
#### Redis version:
6.2.7 
redisearch version is 2.6.x,I compile by source code
#### Java version:
jdk 1.8

I want to know where it's wrong，tks

**Comment by sazzad16** [comment]
> 1.I create an searchIdx like
> [image]

- It seems you chose JSON and a prefix but it doesn't clarify whether you have other optional parameters.

> 3.Then I try query it by
> `FT.SEARCH am_eqp_mst_search *`
> It dosen't working.

- Where are you querying from? Jedis or other clients like redis-cli?
- How are is it not working? Is it giving any error? Are you just getting an empty list?

- Are you using Redis cluster?

**Comment by YOoOzi233** [comment]
**It seems you chose JSON and a prefix but it doesn't clarify whether you have other optional parameters.**
I create searchIdx by jedispooled client :
`Schema schema = new Schema().addSortableTextField("$.id", 1.0)
                    .addSortableTextField("$.eqpNam", 1.0)
                    .addSortableTextField("$" + ".eqpCod", 1.0)
                    .addSortableTextField("$" + ".typeId", 1.0)
                    .addSortableTextField("$" + ".typeIdName", 1.0)
                    .addSortableTextField("$" + ".secondTyp", 1.0)
                    .addSortableTextField("$" + ".secondTypName", 1.0)
                    .addSortableTextField("$" + ".status", 1.0)
                    .addSortableTextField("$" + ".statusName", 1.0)
                    .addSortableTextField("$" + ".lotCod", 1.0)
                    .addSortableTextField("$" + ".addressId", 1.0)
                    .addSortableTextField("$" + ".addressDsc", 1.0)
                    .addSortableTextField("$" + ".areaId", 1.0)
                    .addSortableTextField("$" + ".areaIdName", 1.0)
                    .addSortableTextField("$" + ".deptId", 1.0)
                    .addSortableTextField("$" + ".deptIdName", 1.0)
                    .addSortableTextField("$" + ".amorgId", 1.0)
                    .addSortableTextField("$" + ".amousrId", 1.0)
                    .addSortableTextField("$" + ".amousrIdName", 1.0)
                    .addSortableTextField("$" + ".mgrusrId", 1.0)
                    .addSortableTextField("$" + ".mgrusrIdName", 1.0)
                    .addSortableTextField("$" + ".useusrId", 1.0)
                    .addSortableTextField("$" + ".useusrIdName", 1.0)
                    .addSortableTextField("$" + ".creatorName", 1.0)
                    .addSortableTextField("$" + ".identityTyp", 1.0)
                    .addSortableTextField("$" + ".tagCod", 1.0)
                    .addSortableTextField("$" + ".printSta", 1.0)
                    .addSortableTextField("$" + ".printStaName", 1.0)
                    .addSortableTextField("$" + ".assetAttribute", 1.0)
                    .addSortableTextField("$" + ".assetAttributeName", 1.0)
                    .addSortableTextField("$" + ".shareFlg", 1.0)
                    .addSortableTextField("$" + ".shareFlgName", 1.0)
                    .addSortableTextField("$" + ".organid", 1.0)
                    .addSortableTextField("$" + ".organidName", 1.0)
                    .addSortableTextField("$" + ".creastamp", 1.0)
                    .addSortableTextField("$" + ".searchIdx", 1.0)
                    .addSortableTextField("$" + ".mgrdeptId", 1.0)
                    .addSortableTextField("$" + ".mgrdeptIdName", 1.0);
            IndexDefinition rule = new IndexDefinition(IndexDefinition.Type.JSON)
                    .setPrefixes(new String[]{"am_eqp_mst_search:"});
            getClient().ftCreate("am_eqp_mst_search", IndexOptions.defaultOptions().setDefinition(rule), schema);
`
2. insert data by lua script 
`JedisPool client = new JedisPool();
            Jedis jedis = client.getResource();
            String sha = jedis.scriptLoad("local keys = KEYS\n" +
                    "local argv = ARGV\n" +
                    "local result_1\n" +
                    "for i=1,#keys,1 do\n" +
                    "    print(i)\n" +
                    "    result_1 = redis.call('JSON.SET',keys[i],'$',argv[i])\n" +
                    "end\n" +
                    "return result_1");

            Boolean aBoolean = jedis.scriptExists(sha);
            ArrayList<String> keys = new ArrayList<>();
            ArrayList<String> values = new ArrayList<>();
            keys.add("am_eqp_mst_search:" + entity.getId());
            values.add(JSONObject.toJSON(amEqpMstSearch).toString());
            Object result = client.getResource().evalsha(sha, keys, values);`
3.but I can't query it by ft.search  ,so I insert by json.set syntax, want to check the data was inserted or not , it return ok.
then I query it by ft.search syntax,I haven't got the data , so I try query by json.get syntax ,I got the data .

**Where are you querying from? Jedis or other clients like redis-cli?**
I query data both redis-cli and RedisInsight-v2 client

**How are is it not working? Is it giving any error? Are you just getting an empty list?**
It doesn't give me any error ,just empty list
![image](https://user-images.githubusercontent.com/116061192/196373887-caad844f-95fc-467d-be83-ea218fd897b4.png)
![image](https://user-images.githubusercontent.com/116061192/196373962-5a675eec-078e-4f87-9e70-c12eee178875.png)

**Are you using Redis cluster?**
No,

**Comment by sazzad16** [comment]
Did you try querying (both jsonGet and ftSearch) from JedisPooled?

**Comment by YOoOzi233** [comment]
Thankyou for your suggestion，
I try it in java code ,I got this return:
![image](https://user-images.githubusercontent.com/116061192/196403284-c2e8849f-bc92-4ae4-8ec0-19fda9c99e84.png)
Then I try it by JedisPooled jsonGet method,I got :
![image](https://user-images.githubusercontent.com/116061192/196403590-6dad9074-fc7a-428e-96e5-f77f10187d59.png)
It working. 
But I want to query some data through fields，this function doesn't meet my need.

**Comment by sazzad16** [comment]
I am closing this issue, because:
1. This should have been created in discussion.
2. This is not Jedis specific issue - you are not getting data from other clients as well.
3. The scenario is covered in our test base and working fine.
