### ISSUE TITLE
connect using Managed Identity

### ISSUE THREAD

**Issue by annapusai** [redis/jedis#3172]
Is there a way to connect to Redis cache using Managed Identity rather than directly using connection string details.
TokenCredential tokenCredential = new DefaultAzureCredentialBuilder().build();
this is generally used to get the connection details and connect to Azure Service Bus. Recently Redis cache also got support to connect using Managed Identity.

**Comment by sazzad16** [comment]
@annapusai Not sure what do you exactly mean, but

- You can create `UnifiedJedis` object by providing a `ConnectionProvider`. You can implement the ConnectionProvider the way you want.
- You can even use `ManagedConnectionProvider` where you can provide your managed connection through `setConnection()` method.

**Comment by sazzad16** [comment]
Closing this issue as this more suitable as a discussion.
