### ISSUE TITLE
Not able to connect to redis-sentinel within EKS cluster

### ISSUE THREAD

**Issue by madhushreegc** [redis/jedis#3181]
### Expected behavior

JedisSentinelPool should connect to sentinels running in EKS K8s environment.
### Actual behavior

Write here what happens instead ...
Throwing error

>  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: All sentinels down, cannot determine where is mymaster master is running..."}}

### Steps to reproduce:

1. Install redis-sentinel 3 nodes in K8s environment using bitnami/redis helm
2. Try connecting to Senitnel using below code
    
Maven dependency added
```
<dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
    <version>4.3.0</version>
</dependency>
```

 ```
public class App
{
    public static void main( String[] args )
    {
        try {
            String sentinels = "redis-node-0:26379, redis-node-1:26379,redis-node-2:26379";
            String masterName = "mymaster";
            String password = "password";
            System.out.println("Inside main");
            Set<String> sentinelURIs = new HashSet<String>();
            sentinelURIs.addAll(Arrays.asList(sentinels.split(",")));
            Pool<Jedis> pool =  new JedisSentinelPool(masterName, sentinelURIs, password);
            
            String timerProfilekey = "test";
            try (Jedis jedis = pool.getResource()) {
                jedis.set(timerProfilekey, "abcd");
            }
            
            try (Jedis jedis = pool.getResource()) {
                String abcd = jedis.get(timerProfilekey);
                System.out.println(abcd);
            }
            
        } catch (Exception e) {
            System.out.println(e);
            
        }
    }
}

```

#### Java version: 8

Please let us know when we get this issue and how to resolve this?

**Comment by sazzad16** [comment]
It was not able to connect with any of the sentinel nodes. First try to connect with the sentinel nodes individually (i.e. `new Jedis(...)`) and check if these are running and working properly.

**Comment by madhushreegc** [comment]
Yes, we are able to connect to each seninel nodes individually .

**Comment by sazzad16** [comment]
That's odd :slightly_frowning_face: 

Look for silly mistakes. For example, in your given code, the chosen constructor uses the password only for master node. If your sentinel nodes are password protected, use a proper constructor.

**Comment by madhushreegc** [comment]
Thank you so much Sazzad, it is working, sentinel port were enabled and it was autogenerated.
