### ISSUE TITLE
Wrong handling for Read Timeout

### ISSUE THREAD

**Issue by stillerrr** [redis/jedis#3187]
### Expected behavior

when jedis get read timeout exception, it would throw the expcetion directly, not retry 5 time by default

read timeout means that client send command but do not get response in time, but the command would be executed by redis

so if jedis reties 5 times by default, this command would be execute 5 times, the result would be not right for the command: incr or decr

### Actual behavior

jedis would retry 5 times by default when getting read timeout

**Comment by sazzad16** [comment]
First of all, you are describing JedisCluster class, not Jedis class.

The pin-point solution of your scenario is to set command execution strategy for _each individual command_ which is not practically feasible.

You can maintain separate JedisCluster object with `maxAttempts=1` for such commands; i.e. incr or decr.

**Comment by stillerrr** [comment]
> First of all, you are describing JedisCluster class, not Jedis class.
> 
> The pin-point solution of your scenario is to set command execution strategy for _each individual command_ which is not practically feasible.
> 
> You can maintain separate JedisCluster object with `maxAttempts=1` for such commands; i.e. incr or decr.

maybe we can do something special for read timeout, for example，don't retry for this exception, throw it directly

**Comment by kimmking** [comment]
> > First of all, you are describing JedisCluster class, not Jedis class.
> > The pin-point solution of your scenario is to set command execution strategy for _each individual command_ which is not practically feasible.
> > You can maintain separate JedisCluster object with `maxAttempts=1` for such commands; i.e. incr or decr.
> 
> maybe we can do something special for read timeout, for example，don't retry for this exception, throw it directly

redis have no guarantee acknowledgement for anycommand, so if there is a timeout exception thrown, the commands with side-effect like incr/decr still be uncertain result, maybe put value++ or not.

**Comment by stillerrr** [comment]
> redis have no guarantee acknowledgement for anycommand, so if there is a timeout exception thrown, the commands with side-effect like incr/decr still be uncertain result, maybe put value++ or not.

yes，but it would be better than 5 times for value++

**Comment by kimmking** [comment]
> > redis have no guarantee acknowledgement for anycommand, so if there is a timeout exception thrown, the commands with side-effect like incr/decr still be uncertain result, maybe put value++ or not.
> 
> yes，but it would be better than 5 times for value++

IMO, once and only once strategy for commands such as incr/decr is one of these:
- optimistic lock: use lua to incr/decr for a versioned value, compare the current value and set value++
- distributed lock: or use a global distributed lock for the redis int value to keep it idempotent
