### ISSUE TITLE
Every ten minutes I got "Unexpected end of stream".

### ISSUE THREAD

**Issue by nadcpp** [redis/jedis#3192]
1. Every ten minutes I got "Unexpected end of stream". Same problem with JedisPool.

### Redis / Jedis Configuration
        timeout 0
        tcp-keepalive 300
        client-output-buffer-limit normal 0 0 0
        client-output-buffer-limit replica 256mb 64mb 60
        client-output-buffer-limit slave 0 0 0
        client-output-buffer-limit pubsub 0 0 0

#### Java version: 1.8

       
        //This is my testing code.
        Jedis jedis = new Jedis("127.0.0.1", 6379, 2000);
        JedisPubSub listener = new JedisPubSub() {
            @Override
            public void onMessage(String channel, String message) {
                System.out.println("onMessage: "+ channel);
            }
        };

        jedis.subscribe(listener, "test");

**Comment by zeekling** [comment]
You can eliminate the cause of the network first.

**Comment by minLaoGe** [comment]
Me too....., m|y project is  on local
