### ISSUE TITLE
When the business node is disconnected from the sentry, the latest masterName is not refreshed after the connection is restored

### ISSUE THREAD

**Issue by qinqin111** [redis/jedis#3222]
The business node subscribes to the sentinel, and then disconnects the business node and the sentinel from the network. At this time, the masterName used by the business node undergoes a master-slave switch. After the switch is completed, when the network of the business node and the sentinel node is restored, the business node will continue to connect with the previous master node (now the slave node), and then read and write to the previous master node. At present, this is verified in both versions 2.9.0 and 3.7.0. This may be a problem, Or did I verify it wrong?

**Comment by yangbodong22011** [comment]
@qinqin111 Can you provide your code to describe your problem more clearly?

**Comment by qinqin111** [comment]
@yangbodong22011 正常的启动就行，我的复现场景是这样的
前提
业务节点IP1,  哨兵节点IP21,IP22,IP23， 哨兵下面存储节点，IP31
代码配置：
在配置哨兵连接时候，只配置IP21，其他的都按正常来就行

复现步骤：
1.启动IP1上面的服务
2.观察：在IP21上面执行client list指令可以看到和IP1是有连接的
3.使用iptables 禁用网络：在IP1上禁用IP21，在Ip21上禁用IP1
4.我的服务器大概5分钟左右，在IP21上面执行client list指令，会发现和P1网络是断开的(5分钟主要是通过抓包发现了，哨兵主动断开了)
5.分别在IP1和IP21上执行 sudo iptables -F (清除之前防火墙)
6.在IP21上执行 sentinel failover [mastername](发起一次主动切换)
7.在观察业务节点，会发现业务节点的连接无法刷新到最新的masterName上面去

在上面第4步时，IP1和哨兵IP21的TCP连接是未断开的，但是IP21上显示和IP1上是断开的
