### ISSUE TITLE
JedisCluster read/write node behaviour 

### ISSUE THREAD

**Issue by bytearchive** [redis/jedis#3255]
how does JedisCluster handle the  read/write nodes on Elasticache, or slave nodes on master?

does it have separate pools for read and write? does it automatically routes read operations to slaves or replicas?

is there any documentation on this somewhere?

**Comment by yangbodong22011** [comment]
@bytearchive JedisCluster will only connect to the main node and read/write, and will not access the replicas (even if it is available)

**Comment by yangbodong22011** [comment]
@bytearchive JedisCluster will only connect to the main node and read/write, and will not access the replicas (even if it is available).

**Comment by yangbodong22011** [comment]
@bytearchive JedisCluster will only connect to the main node and read/write, and will not access the replicas (even if it is available).

**Comment by sazzad16** [comment]
Closed due to inactivity.
