### ISSUE TITLE
JedisConnectionFactory error: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required

### ISSUE THREAD

**Issue by nitinware** [redis/jedis#3281]
### Expected behavior

I am expecting the establish the connection with AWS ElasticCache Redis cluster successfully and JedisConnectionFactory object initialized successfully

### Actual behavior

On application startup, I am seeing below error on throw when initializing JedisConnectionFactory: 

`
Failed to instantiate [org.springframework.data.redis.connection.jedis.JedisConnectionFactory]: Factory method 'clusterModeJedisConnectionFactory' threw exception; nested exception is redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)\n\tat 
`

### Redis / Jedis Configuration

```
 @Bean
    @Conditional(RedisClusterModeCondition.class)
    public JedisConnectionFactory clusterModeJedisConnectionFactory() {
        RedisClusterConfiguration configuration = new RedisClusterConfiguration()
                .clusterNode(redisHostName, redisPort);
        configuration.setMaxRedirects(5);
        JedisClientConfiguration clientConfiguration = sslEnabled?
                JedisClientConfiguration.builder().useSsl().and().usePooling().build() :
                JedisClientConfiguration.builder().build();
        JedisConnectionFactory factory = new JedisConnectionFactory(configuration, clientConfiguration);
        factory.afterPropertiesSet();
        logger.info(String.format("Configuring Redis ClusterMode with host: %s and port: %d", redisHostName, redisPort));
        return factory;
    }
```

The Redis cluster have a default user with no password configured: 

![Screenshot 2023-01-17 at 9 54 30 AM](https://user-images.githubusercontent.com/8107038/212946742-f14e4369-db95-4a03-8ff5-59d130abd674.png)

![Screenshot 2023-01-17 at 9 58 19 AM](https://user-images.githubusercontent.com/8107038/212947277-1d68f0fc-b794-4b82-8cd7-0de3e1b780bf.png)

#### Jedis version:
3.6.3
#### Redis version:
5.0.6
#### Java version:
openjdk1.8.0.342_8.64.0.16_x64

**Comment by sazzad16** [comment]
`NOAUTH Authentication required.` error comes from Redis server. Jedis doesn't generate it on its own.

We can't learn how `aws` manages things at this moment. Please consult with them (or, maybe Spring). Thanks
