### ISSUE TITLE
Feat: Suggested migration from deprecated use of new Long(long)

### ISSUE THREAD

**Issue by SoulPancake** [redis/jedis#3287]
We should migrate this to Long.valueOf(long) syntax instead everywhere in the repo

![image](https://user-images.githubusercontent.com/70265851/217541364-3db12348-c084-4bf6-9dfe-e8c293296afb.png)

**Comment by SoulPancake** [comment]
I can write a PR with this change if required

**Comment by sazzad16** [comment]
Sure! A PR would be a great help.

**Comment by SoulPancake** [comment]
@sazzad16 I've raised a PR, Can you review it?
