### ISSUE TITLE
JedisPooled connection is thread safety? Why does my program report this error？

### ISSUE THREAD

**Issue by sabenuse** [redis/jedis#3294]
### Expected behavior
This error is not inevitable, but will not occur until a certain time.

It seems to be the result of the wrong command.
For example, the del command must return Long, but byte[]

### Actual behavior
2023-02-15 20:34:59,201 [http-nio-80-exec-16] ERROR java.lang.ClassCastException: class [B cannot be cast to class java.lang.Long ([B and java.lang.Long are in module java.base of loader 'bootstrap')
	at redis.clients.jedis.BuilderFactory$6.build(BuilderFactory.java:91)
	at redis.clients.jedis.BuilderFactory$6.build(BuilderFactory.java:88)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167)
	at redis.clients.jedis.UnifiedJedis.del(UnifiedJedis.java:433)

2023-02-15 20:35:00,009 [http-nio-80-exec-100] ERROR java.lang.ClassCastException: class java.lang.Long cannot be cast to class [B (java.lang.Long and [B are in module java.base of loader 'bootstrap')
	at redis.clients.jedis.BuilderFactory$19.build(BuilderFactory.java:308)
	at redis.clients.jedis.BuilderFactory$19.build(BuilderFactory.java:305)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167)
	at redis.clients.jedis.UnifiedJedis.set(UnifiedJedis.java:584)

2023-02-15 20:35:02,151 [http-nio-80-exec-49] ERROR java.lang.ClassCastException: class java.lang.Long cannot be cast to class [B (java.lang.Long and [B are in module java.base of loader 'bootstrap')
	at redis.clients.jedis.BuilderFactory$19.build(BuilderFactory.java:308)
	at redis.clients.jedis.BuilderFactory$19.build(BuilderFactory.java:305)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167)
	at redis.clients.jedis.UnifiedJedis.get(UnifiedJedis.java:589)
### Steps to reproduce:
Code has been reorganized
val jedisPooled = JedisPooled(ip, 6379);
val redisKey="redis-lock";
val param = SetParams.setParams();
param.nx();
param.ex(60);
Optional<String> optionalS =Optional.ofNullable(jedisPooled.set(redisKey, redisKey, param);
        if (optionalS.isPresent()) {
            if (optionalS.get().equalsIgnoreCase("OK")) {
                try {
                    try {
                        return callable.call();
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                } finally {
                    jedisPooled.del(redisKey);
                }
            } else {
                try {
                    Thread.sleep(0);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
                return sync(redisKey, callable);
            }
        } else {
            try {
                Thread.sleep(0);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            return sync(redisKey, callable);
        }
### Redis / Jedis Configuration
timeout=3000
maxTotal=50
maxIdle=20
minIdle=10
maxWaitMillis=6000
#### Jedis version:
4.3.0
#### Redis version:
6.0
#### Java version:
17.0

**Comment by kimmking** [comment]
You should use jedisPool as the following:
```
try (Jedis jedis = jedisPool.getResource()) {
      String value = jedis.get(key);
 }
```
getResource method pick a connection from pool, and in finally block, returnResource method will be invoked and return the borrowed connection to pool.

**Comment by sazzad16** [comment]
`Optional optionalS = jedisPooled.set(redisKey, redisKey, RedisParams.getParam());`

Which library is this? Here in Jedis `set` doesn't return `Optional` but a `String`. We don't have anything named `RedisParams`.

**Comment by sabenuse** [comment]
> You should use jedisPool as the following:
> 
> ```
> try (Jedis jedis = jedisPool.getResource()) {
>       String value = jedis.get(key);
>  }
> ```
> 
> getResource method pick a connection from pool, and in finally block, returnResource method will be invoked and return the borrowed connection to pool.

We use JedisPooled not  of JedisPool

**Comment by sabenuse** [comment]
> 

Code has been reorganized
val jedisPooled = JedisPooled(ip, 6379);
val redisKey="redis-lock";
val param = SetParams.setParams();
param.nx();
param.ex(60);
Optional optionalS =Optional.ofNullable(jedisPooled.set(redisKey, redisKey, param);

**Comment by sabenuse** [comment]
> `Optional optionalS = jedisPooled.set(redisKey, redisKey, RedisParams.getParam());`
> 
> Which library is this? Here in Jedis `set` doesn't return `Optional` but a `String`. We don't have anything named `RedisParams`.

Code has been reorganized
val jedisPooled = JedisPooled(ip, 6379);
val redisKey="redis-lock";
val param = SetParams.setParams();
param.nx();
param.ex(60);
Optional optionalS =Optional.ofNullable(jedisPooled.set(redisKey, redisKey, param);

**Comment by sazzad16** [comment]
Did the code reorganization help?

---

Use commons pool 2.11.1 if you're not already using it.

Use Jedis 4.3.1; this shouldn't matter in this case but still.

---

If you're calling `JedisPooled(ip, 6379)`, then it should use the default pool configuration internally. So how are you setting mentioned ones?

> timeout=3000
> maxTotal=50
> maxIdle=20
> minIdle=10
> maxWaitMillis=6000

---

The information that are provided and evolved, it is hard to dig into and harder to help. Wish you would get your problem fixed (in case I can't help further).

**Comment by sabenuse** [comment]
> Did the code reorganization help?
> 
> Use commons pool 2.11.1 if you're not already using it.
> 
> Use Jedis 4.3.1; this shouldn't matter in this case but still.
> 
> If you're calling `JedisPooled(ip, 6379)`, then it should use the default pool configuration internally. So how are you setting mentioned ones?
> 
> > timeout=3000
> > maxTotal=50
> > maxIdle=20
> > minIdle=10
> > maxWaitMillis=6000
> 
> The information that are provided and evolved, it is hard to dig into and harder to help. Wish you would get your problem fixed (in case I can't help further).

I just simplified the code and wrote it 
val jedisPooled = JedisPooled(ip, 6379);

In fact, our code is as follows：

private static JedisPooled pool = null;
config.setMaxTotal(appConfig.getInt("redis.pool.maxTotal"));
          config.setMaxIdle(appConfig.getInt("redis.pool.maxIdle"));
          config.setMinIdle(appConfig.getInt("redis.pool.minIdle"));
          config.setMaxWait(Duration.ofSeconds(appConfig.getInt("redis.pool.maxWaitMillis")));
          //config.setTestOnBorrow(appConfig.getBoolean("redis.pool.testOnBorrow"));  
          //config.setTestOnReturn(appConfig.getBoolean("redis.pool.testOnReturn")); 
          //config.setTestWhileIdle(appConfig.getBoolean("redis.pool.TestWhileIdle"));
          String[] hostPort = appConfig.getString("redis.server").split(":");
          String host = hostPort[0];
          int port = Integer.parseInt(hostPort[1]);
          //db = appConfig.getInt("redis.db");

          config.setTimeBetweenEvictionRuns(Duration.ofSeconds(3));
          String passwd = appConfig.getString("redis.password");
          if (passwd != null && passwd.length() > 0) {
              pool = new JedisPooled(config, host, port, appConfig.getInt("redis.timeout"), passwd, appConfig.getInt("redis.db"));
          } else {
              pool = new JedisPooled(config, host, port, appConfig.getInt("redis.timeout"), null, appConfig.getInt("redis.db"));
          }
