### ISSUE TITLE
`Pipeline#select(index)` doesn't pass through the index parameter

### ISSUE THREAD

**Issue by LoonyRules** [redis/jedis#3299]
### Expected behavior

The `Pipeline.select(index)` method should pass through the index parameter into the command object that is being created.

### Actual behavior

The `index` parameter isn't actually being used once passed through by the user.

### Steps to reproduce:

1. Create a standard JedisPool that connects to a database with more than 1 dbIndex configured but by default connects to dbIndex 0.
2. Execute the following code:
```java
try (final Pipeline pipeline = jedis.pipelined()) {
    pipeline.select(1);
    pipeline.set("foo", "bar");
    
    final List<Object> objects = pipeline.syncAndReturnAll();
    System.out.println("Objects: " + objects);
}
```
3. You will see that the printed `objects` mentions: `redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'select' command`.
4. This error still lets the `.set("foo", "bar")` method be called, resulting in the key being set into dbIndex 0 instead of dbIndex 1.

Code at the time of this issue creation can be found over at https://github.com/redis/jedis/blob/d4644dae94e4769a589026a759746cfa061af413/src/main/java/redis/clients/jedis/Pipeline.java#L4292-L4294

### Redis / Jedis Configuration
Standalone, standard JedisPool instance.

#### Jedis version:
4.4.0-m2

#### Redis version:
7.0.7 (old but works fine for this).

#### Java version:
17

**Comment by sazzad16** [comment]
Acknowledged and fixed. Thank you @LoonyRules for your contribution!

**Comment by LoonyRules** [comment]
@sazzad16 no problem, when's the next scheduled release?
