### ISSUE TITLE
Reduce the number of constructors of Jedis and JedisPool

### ISSUE THREAD

**Issue by needmorecode** [redis/jedis#3300]
I find now there are 27 constructors for Jedis and 55 constructors for JedisPool. As so many constructors exist, I often feel confused about choosing which one to use. Also two many constructors increase the possibility of using the wrong one.

My suggestion is to use the **builder design pattern** to minimize the number of constructors, as suggested in the book _Effective Java_.

Then the new construction method would look like this: 
`Jedis jedis = new Jedis().Builder("localhost", 6379).password("xxx").timeout(2000)...`

We can put the key arguments in Builder constructor and other arguments in the following setter methods.

**Comment by sazzad16** [comment]
There's some legacy things that we have to maintain. No doubt most of the constructors would be removed as some point in time but we don't know when that would happen.

May I suggest you following constructors?

```
public Jedis(final HostAndPort hostPort, final JedisClientConfig config)
public JedisPool(final HostAndPort hostAndPort, final JedisClientConfig clientConfig)
public JedisPooled(final HostAndPort hostAndPort, final JedisClientConfig clientConfig)
```

Hope these would fulfill your requirements.

**Comment by needmorecode** [comment]
> There's some legacy things that we have to maintain. No doubt most of the constructors would be removed as some point in time but we don't know when that would happen.
> 
> 
> 
> May I suggest you following constructors?
> 
> 
> 
> ```
> 
> public Jedis(final HostAndPort hostPort, final JedisClientConfig config)
> 
> public JedisPool(final HostAndPort hostAndPort, final JedisClientConfig clientConfig)
> 
> public JedisPooled(final HostAndPort hostAndPort, final JedisClientConfig clientConfig)
> 
> ```
> 
> 
> 
> Hope these would fulfill your requirements.

Thank you for quick reply. Your opinion is helpful and reasonable.
