### ISSUE TITLE
How to detect disconnect?

### ISSUE THREAD

**Issue by jjz921024** [redis/jedis#3308]
How to detect a connection which in the pool has been broken,  so that the user can trigger a reconnect

### Expected behavior
For example, add a hooks to callback when the connection is broken

**Comment by sazzad16** [comment]
If you mean `Connection` class object, you may use `Connection#isBroken()`. You may even consider `Connection#ping()` to be absolutely sure.

However, if the Connection is part of Pool, the pool should handle (re)creating connection when necessary.

**Comment by sazzad16** [comment]
Following message is part of our [contribution guideline](https://github.com/redis/jedis/blob/master/.github/CONTRIBUTING.md) and issue template. Please respect that.

Github issues should be used to report bugs and for detailed feature requests. 
Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).

Please post general questions to Google Groups or Github discussions. 
These can be closed without response when posted to Github issues.
