### ISSUE TITLE
How do i use multi/exec with JedisPooled

### ISSUE THREAD

**Issue by GithubUser8080** [redis/jedis#3324]
Hi, sorry for making this an issue but I didn't manage to find a solution via the wiki. Using JedisPooled, how can i do a multi/exec command? The single Jedis client has this functionality, but i also need RediSearch so I am using JedisPooled. Thanks

**Comment by sazzad16** [comment]
> sorry for making this an issue

You could create a [discussion](https://github.com/redis/jedis/discussions/new/choose).

> Using JedisPooled, how can i do a multi/exec command?

There is no direct multi() method ATM. A possible way can be:
```
Connection c = jedisPooled.getPool().getResource();
Transaction t = new Transaction(c);
...
...
t.exec();
c.close();
```

**Comment by GithubUser8080** [comment]
> > sorry for making this an issue
> 
> You could create a [discussion](https://github.com/redis/jedis/discussions/new/choose).
> 
> > Using JedisPooled, how can i do a multi/exec command?
> 
> There is no direct multi() method ATM. A possible way can be:
> 
> ```
> Connection c = jedisPooled.getPool().getResource();
> Transaction t = new Transaction(c);
> ...
> ...
> t.exec();
> c.close();
> ```

I used your method, works fine, but thank you for adding an easier api with #3361.
