### ISSUE TITLE
No other place I could mention this

### ISSUE THREAD

**Issue by ItzSkyy** [redis/jedis#3340]
### Expected behavior

Clicked the link to go to discord the "chat" - and got "invite expired"

### Actual behavior

Allow me to join Discord

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. click "Chat - xxxx online"
2. see expired invite

**Comment by sazzad16** [comment]
@ItzSkyy Does [this link](http://discord.gg/redis) work for you?

**Comment by sazzad16** [comment]
Closed due to inactivity.
