### ISSUE TITLE
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection

### ISSUE THREAD

**Issue by palak1708** [redis/jedis#3363]
### Expected behavior

API Should return some data or a null object.

### Actual behavior
Getting- status": 500,
  "error": "Internal Server Error",
  "trace": "org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection\r\n\tat org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:271)\r\n\tat org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:454)\r\n\tat org.springframework.data.redis.cache.DefaultRedisCacheWriter.execute(DefaultRedisCacheWriter.java:272)\r\n\tat org.springframework.data.redis.cache.DefaultRedisCacheWriter.get(DefaultRedisCacheWriter.java:122)\r\n\tat org.springframework.data.redis.cache.RedisCache.lookup(RedisCache.java:86)\
	Suppressed: java.net.ConnectException: Connection refused: no further information
		at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
		at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
		at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
		at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
		at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73) ~[jedis-4.3.1.jar:na]
		... 175 common frames omitted

Response headers:

 cache-control: no-cache,no-store,max-age=0,must-revalidate 
 connection: close 
 content-type: application/hal+json 
 date: Mon,10 Apr 2023 05:07:15 GMT 
 expires: 0 
 pragma: no-cache 
 transfer-encoding: chunked 
 vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
 x-xss-protection: 0 

### Steps to reproduce:

start spring boot main class and open swagger UI in local, hit the get API method for testing.

### Redis / Jedis Configuration
@Configuration
@EnableCaching
public class CacheConfig {

	@Bean
	public JedisConnectionFactory redisConnectionFactory() {
	    JedisConnectionFactory factory = new JedisConnectionFactory();
	    factory.setHostName("localhost");
	    factory.setPort(6379);
	    factory.setUsePool(true);
	    factory.getPoolConfig().setMaxIdle(30);
	    factory.getPoolConfig().setMinIdle(10);
	    return factory;
	}

	@Bean
	public RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory cf) {
	    RedisTemplate<Object, Object> redisTemplate = new RedisTemplate<Object, Object>();
	    redisTemplate.setDefaultSerializer(new StringRedisSerializer());
	    redisTemplate.setConnectionFactory(cf);

	    return redisTemplate;
	}

#### Jedis version:
tried with 2.9.0, 3.8.0 and 4.3.1
#### Redis version:
spring data redis 3.0.2

#### Java version:
Java 17

**Comment by sazzad16** [comment]
Work on:

```
java.net.ConnectException: Connection refused: no further information
at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
```

For example: https://stackoverflow.com/a/6876306/4021802 from https://stackoverflow.com/questions/6876266/java-net-connectexception-connection-refused

**Comment by palak1708** [comment]
> Work on:
> 
> ```
> java.net.ConnectException: Connection refused: no further information
> at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
> at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
> at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
> at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
> at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
> at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
> ```
> 
> For example: https://stackoverflow.com/a/6876306/4021802 from https://stackoverflow.com/questions/6876266/java-net-connectexception-connection-refused

Root cause that is thrown in stack trace is  "org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection. Its not a socket/TCP or HTTP client issue.
