### ISSUE TITLE
Jedis latest (4.3.2) jar compatibility issues with sping-data-redis latest (3.0.4) jar

### ISSUE THREAD

**Issue by iav20** [redis/jedis#3365]
Hello , 

We are trying to upgrade Jedis jar from the current (3.9.0) version to latest (4.3.2) version in order to utilize the complete and enhanced features provided for ACLs.  As part of this the codebase also needs to be refreshed with the latest spring-data-redis (3.0.4) jar to avoid compilation issues.  But upgrading spring-data-redis jar along with jedis jar is giving the following error - 

Could not resolve org.springframework:spring-beans:6.0.7.
     Required by:
         project : > org.springframework.data:spring-data-redis:3.0.4 > org.springframework.data:spring-data-keyvalue:3.0.4 > org.springframework.data:spring-data-commons:3.0.4
> No matching variant of org.springframework:spring-beans:6.0.7 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability org.springframework:spring-beans:6.0.7 declares an API of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 8
          - Variant 'runtimeElements' capability org.springframework:spring-beans:6.0.7 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally:
              - **Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 8**

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights

It seems that the latest Jedis (4.3.2) jar and spring-data-redis (3.0.4) are incompatible since the classes referred are compiled with different Java versions (Java 8 and Java 17 ) . Also our code base is built with Java 8 

Please suggest

**Comment by sazzad16** [comment]
Closed due to inactivity.
