### ISSUE TITLE
bzpopmin

### ISSUE THREAD

**Issue by yuyang807** [redis/jedis#3368]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by yangbodong22011** [comment]
we already supported [bzpopmin](https://github.com/redis/jedis/blob/master/src/main/java/redis/clients/jedis/Jedis.java#L2612)?
