### ISSUE TITLE
How to give Transction support with UnifiedJedis

### ISSUE THREAD

**Issue by Datta19** [redis/jedis#3383]
I have used UnifiedJedis client to develop the java application. I am using **jedis-4.2.3.jar**  and **java 1.8** for this application development. UnifiedJedis provides easy to use api for JSON data manipulation. We required transaction support as well, but we don't seen transaction support for UnifiedJedis. Please help us here, How can we tackle with this issue now?  Is there any way so that we can use UnifiedJedis and also give transaction support. I am worried becuse 70% of development is alredy done with UnifiedJedis so please help us here.

**Comment by sazzad16** [comment]
From Jedis version 4.4.0, UnifiedJedis will have a `multi()`.

**Comment by sazzad16** [comment]
Please respect our guidelines:

> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
