### ISSUE TITLE
How to add null value fields into redis using UnifiedJedisClient.jsonSetLegacy(key, pojo)

### ISSUE THREAD

**Issue by hemangi225** [redis/jedis#3385]
I am using jedis version 4.2.3 and java1.8, While inserting pojo object into redis using UnifiedJedisClient.jsonSetLegacy(String key, Object pojo) null values are getting ignored in json object. but I want nulll values should be in json created object. I tried with Gson/json but it is not working.
e.g.
class myClass
{
String name;
int age =10;
}

public void insertObjectIntoRedis()
{
String key = "myKey";
myClass  m1 = new myClass(); // where name is null and age is 10
  String jsonString = getJsonString(m1);
  ObjectMapper objMapper = new ObjectMapper();
 Object pojo = objMapper.readValue(jsonString, Object.class);
 getJedisClient().jsonSetLegacy(key, pojo);
}

This writes myclass json object into redis with only field of age and it ignores name as it is null.

I want null values field should not be ignored while inserting java object as json into redis using UnifiedJedisClient.jsonSetLegacy().

**Comment by sazzad16** [comment]
**First of all, write the class name properly; it's `UnifiedJedis`, not UnifiedJedisClient.**

---

Scondly, respect our guidelines:

> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.

---

Lastly, to answer your question, use any serializer that can handle `null`. Here, I'm showing an example with Gson but you can use any other.

```java
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import redis.clients.jedis.json.JsonObjectMapper;

class MyGsonObjectMapper implements JsonObjectMapper {

  private static final Gson GSON = new GsonBuilder().serializeNulls().create();

  @Override
  public <T> T fromJson(String string, Class<T> type) {
    return GSON.fromJson(string, type);
  }

  @Override
  public String toJson(Object o) {
    return GSON.toJson(o);
  }
}
```

Pass that serialzier to UnifiedJedis.
```java
UnifiedJedis jedis = ...;
jedis.setJsonObjectMapper(new MyGsonObjectMapper());
```

Then simply do your operations.

```java
jedis.jsonSetLegacy(key, m1);
```

In server we can see that null is saved.

```bash
> JSON.GET myKey
"{\"name\":null,\"age\":10}"
```

**Comment by hemangi225** [comment]
First of all Thank you for your feedback. Adding question in this forum is my mistake, Sorry for that, next time onward i will take care about it.
I found that this solution is working in jedis-4.4.0-rc1 but for not in jedis-4.2.3, setJsonObjectMapper() is not supported in jedis-4.2.3
