### ISSUE TITLE
multi is much slower on 3.2.0 compared to 2.9.3

### ISSUE THREAD

**Issue by eliassona** [redis/jedis#3390]
### Expected behavior
Jedis 3.2.0 should at least be equally fast as 2.9.3.

### Actual behavior
Jedis 2.9.3 is about twice as fast as 3.2.0. 

### Steps to reproduce:
Run this program with 2.9.3 and then 3.2.0, and compare the result it displays.

import redis.clients.jedis.Jedis;
import redis.clients.jedis.Transaction;

public class Test {
	public static void main(final String[] args) {
		final Jedis j = new Jedis("localhost");
//		final Jedis j = new Jedis(new HostAndPort("localhost", 6379));
		j.flushAll();
		if (j.keys("*").size() != 0) throw new IllegalStateException();
		final long st = System.currentTimeMillis();
		for (int i = 0; i < 1e5; i++) {
			final Transaction tx = j.multi();
			final String key = "key" + i;
			tx.get(key);
			tx.set(key, "some text");
			tx.exec();
		}
		System.out.println("Duration: " + (System.currentTimeMillis() - st));
		if (j.keys("*").size() != 1e5) throw new IllegalStateException();
		j.close();
	}
}

### Redis / Jedis Configuration
Just one redis server running, no cluster.
#### Jedis version:
2.9.3 and 3.2.0
#### Redis version:
Tested with redis server 7.0.1 and 5
#### Java version:
Java 17 on Macbook Pro.

**Comment by sazzad16** [comment]
It is expected behavior. To avoid Transaction starting with a invalid/broken connection, Jedis 3.x executes the very first command, MULTI, separately outside pipeline.

You may try Jedis 4.x as it gives option to include and exclude MULTI from pipeline.

**Comment by eliassona** [comment]
Thanks for the quick reply. I did run it repeatedly and I have tried 4.0.0, it was faster than 3.2.0 but slower than 2.9.3.
What I want to achieve is optimistic locking. Is there is a better way of doing that than MULTI/EXEC?

**Comment by sazzad16** [comment]
LUA scripting

**Comment by sazzad16** [comment]
https://redis.io/docs/manual/programmability/eval-intro/
