### ISSUE TITLE
When the Redis cluster is not available, how can Jedis quickly return timeout?

### ISSUE THREAD

**Issue by 1209233066** [redis/jedis#3432]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
