### ISSUE TITLE
Add support for triggered functions

### ISSUE THREAD

**Issue by uglide** [redis/jedis#3435]
Add support for [triggered functions](https://github.com/RedisGears/RedisGears/blob/master/docs/commands.md)

- [ ] RG.FUNCTION LOAD. API for this command should support loading the function content from the file.
- [ ] RG.FUNCTION DEL
- [ ] RG.FUNCTION LIST
- [ ] RG.FCALL
- [ ] RG.FCALLASYNC

**Comment by sazzad16** [comment]
Mostly resolved by #3531
