### ISSUE TITLE
Jedis 4.4.1 fails on CLIENT SETINFO for Redis 6.x if the user does not have all +CLIENT permissions

### ISSUE THREAD

**Issue by XA21X** [redis/jedis#3438]
### Expected behavior

Jedis should successfully connect to Redis 6.x clusters using a user without _all_ `+CLIENT` permissions.

### Actual behavior

Jedis fails to perform slots renewal on connection due to a `NOPERM` error. 

```
...
Caused by: redis.clients.jedis.exceptions.JedisClusterOperationException: Could not initialize cluster slots cache.
...
Suppressed: redis.clients.jedis.exceptions.JedisAccessControlException: NOPERM this user has no permissions to run the 'client' command or its subcommand
```

### Steps to reproduce:

1. Setup a Redis 6.2.11 server.
2. Create a Redis user without _the_ `+client` permission, e.g. `+@all -@dangerous`, or more specifically:
  ```
  ACL SETUSER test +@all allkeys -@dangerous +client|id +client|getname +client|setname +config|get +cluster|info +cluster|keyslot +cluster|myid +cluster|nodes +cluster|slots >test on
  ```
4. Connect to Redis using Jedis 4.4.1 with the limited user - which does not work.

This error can be reproduced using `redis-cli` by running `CLIENT SETINFO LIB-NAME test`.

Adding specific `client` subpermissions to the user does not affect the result unless it's `+client|setinfo`. The command doesn't exist in Redis 6.x, but its permission can still be added. Having `+client|setinfo` is a sufficient workaround, because after passing the permissions check, the command correctly fails with `ERR Unknown` instead of `NOPERM`.

#### Jedis version:

Jedis **4.4.1** introduced the "fire and forget" `CLIENT SETINFO` on connection: redis/jedis#3356 but does not ignore `NOPERM` errors.

#### Redis version:

Redis **6.2.11**, but it is likely that any 6.x is affected.

Redis 7.x seems to have fixed this as part of wider work surrounding redis/redis#9504.

Most of the `CLIENT` commands are no longer in the `@dangerous` group, so my example above _includes_ the required permission. It also makes the command existence check able to detect the missing command before evaluating permissions.

#### Java version:

```
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-11.0.19.7.1 (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.19.7.1 (build 11.0.19+7-LTS, mixed mode)
```

**Comment by sazzad16** [comment]
@XA21X Thank you for reporting the bug.

**Comment by yangbodong22011** [comment]
@XA21X You did not configure a password when connecting to Redis, and used the default user, right?

**Comment by XA21X** [comment]
@yangbodong22011 it was with a password, using another user.
Note: My reproduction steps above creates a `test:test` user. :)

The actual `default` user would work _by default_, as it has all permissions. But Jedis should ideally also work for users where the principle of least privilege has been applied - only granting specific commands instead of command groups.

**Comment by yangbodong22011** [comment]
We have two ways to fix this issue:

1. Ignore `NOPERM` errors in fire-and-forgot results.

2. Add a document to remind users to add `+client|setinfo` when using `acl` to create a user.

Personally I'd prefer `1`, which fixes it quietly. This is different from the [fix](https://github.com/redis/jedis/pull/3411) of Redis4.0. This problem requires specific trigger conditions (users use acl to add users themselves but do not grant `client` permissions). What do you think @sazzad16

**Comment by yangbodong22011** [comment]
> So, if we take literally, the ideal way would be to ignore any error for CLIENT SETINFO.

@sazzad16 What do you think about moving the [select](https://github.com/redis/jedis/pull/3356#discussion_r1158361052) command out of the fire-and-forget message, and completely ignoring any errors from `client setname|setinfo` (including [invalid characters](https://github.com/redis/jedis/pull/3356#discussion_r1158368124), etc.)?

**Comment by sazzad16** [comment]
@yangbodong22011 

> moving the [select](https://github.com/redis/jedis/pull/3356#discussion_r1158361052) command out of the fire-and-forget message

I'm okay with that.
> completely ignoring any errors from `client setname|setinfo` (including [invalid characters](https://github.com/redis/jedis/pull/3356#discussion_r1158368124), etc.)

That'd be a risky one. Users won't be able to address such fixable issues if we hide exceptions. We should at least log such situations. But in this case I think logging is even worse solution because if there is really an issue, there would be too many logs. If we can limit the number of same log (i.e. once), it would be a good trade-off.

**Comment by yangbodong22011** [comment]
> That'd be a risky one. Users won't be able to address such fixable issues if we hide exceptions. We should at least log such situations. But in this case I think logging is even worse solution because if there is really an issue, there would be too many logs. If we can limit the number of same log (i.e. once), it would be a good trade-off.

In fact, in `Connection.java`, we don't get errors for illegal characters, because `JedisMetaInfo.getArtifactId()` always gets legal strings. (The remaining errors, NOAUTH, UNKNOWN command, SYNTAX error, NOPREM should be ignored)

If the user actively sets it externally through `Jedis.clientSetInfo()`, then the user will need to care about returning the result and perceive the error.
