### ISSUE TITLE
Does jedis supprt find hotkeys and bigkeys？

### ISSUE THREAD

**Issue by lvmengtian** [redis/jedis#3468]
Does jedis supprt find hotkeys and bigkeys？

**Comment by sazzad16** [comment]
No.

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
