### ISSUE TITLE
Clients should identify themselves on connect

### ISSUE THREAD

**Issue by chayim** [redis/jedis#3482]
[CLIENT SETINFO](https://redis.io/commands/client-setinfo/) is a new fire-and-forget command that is available as part of redis 7.2. Clients should send the lowercased version of the client name (i.e redis-py, jedis, go-redis) as part of the initial connect, after authenticating to the server.

**Comment by yangbodong22011** [comment]
@chayim you means this? https://github.com/redis/jedis/pull/3356

**Comment by sazzad16** [comment]
Released on Jedis versions 4.4.5 and 5.0.1
