### ISSUE TITLE
jedis compatibility with redis

### ISSUE THREAD

**Issue by jimchen1009** [redis/jedis#3483]
I want to known the summary of jedis versions and corresponding compatible redis versions. 

one possible situation:
I'm using the version 2.x（cannot change），and I wanna upgrade redis as high as possible.

**Comment by sazzad16** [comment]
@jimchen1009 Thank you for your interest in Jedis.

Firstly, check the [README](https://github.com/redis/jedis/blob/master/README.md). There's already a compatibility matrix.

Secondly, search the repo for relevant issues/discussions. There are already a few related to this topic. You may participate there by commenting.

If you still find your topic requires a separate post, please respect our [guidelines](https://github.com/redis/jedis/blob/master/.github/CONTRIBUTING.md).

> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
