### ISSUE TITLE
Support Read from replicas node

### ISSUE THREAD

**Issue by jjz921024** [redis/jedis#3484]
### Expected behavior
Add sendCommandToReplicas() method for JedisCluster, it will make users to send read-only commands to replicas nodes, to reduce main nodes pressure

**Comment by Ranjeet0611** [comment]
Hi @sazzad16  How can we start with this issue?

**Comment by sazzad16** [comment]
@Ranjeet0611 Please use your imagination. I can only help in smaller scale.

If you want to discuss with community, you may ask in [Discussions](https://github.com/redis/jedis/discussions) or [Google group](https://groups.google.com/g/jedis_redis).

**Comment by Ranjeet0611** [comment]
Sure @sazzad16  I will try to figure it out.
