### ISSUE TITLE
does jedis support unix-domain-socket ?

### ISSUE THREAD

**Issue by caojiajun** [redis/jedis#3493]
does jedis support unix-domain-socket ?

or any plan

**Comment by sazzad16** [comment]
There isn't direct way but can be done with a simple JedisSocketFactory implementation like following: https://github.com/redis/jedis/blob/2cd2601623857a37f641d369e53625625538ea76/src/test/java/redis/clients/jedis/UdsTest.java#L45-L59 

[Here](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/UdsTest.java) is full test file.

**Comment by caojiajun** [comment]
thank you very much~

is this code production available? and any plan to merge it mainlines, such as provide 'UdsJedisPool.java'?

**Comment by sazzad16** [comment]
> is this code production available?

Yes (if you want to do some works).

> any plan to merge it mainlines

Not at this moment.
