### ISSUE TITLE
are JedisSharding and JedisCluster Thread-safe ?

### ISSUE THREAD

**Issue by mrafsan-socotra** [redis/jedis#3498]
Is UnifiedJedis expected to be in general as well ?

**Comment by sazzad16** [comment]
> JedisSharding

Yes.

> JedisCluster

Yes.

> UnifiedJedis expected to be in general

"in general"? Yes.

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
