### ISSUE TITLE
Do I need to manually close the pipeline?

### ISSUE THREAD

**Issue by dbkand** [redis/jedis#3508]
Hello, in Jedis 4.4.3, do the pipelines obtained through JedisPool, JedisPooled, JedisCluster and JedisSentinel need to be manually shut down after they are used?

**Comment by sazzad16** [comment]
@dbkand Please provide small code examples of how you're obtaining pipelines through each of those individual classes [in Discussions](https://github.com/redis/jedis/discussions/new/choose) preferably [in Q&A](https://github.com/redis/jedis/discussions/new?category=q-a).

Also, please maintain our following request from now on:

> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.

Thank you.
