### ISSUE TITLE
Does Jedis support ReadFromSlave feature

### ISSUE THREAD

**Issue by luger1990** [redis/jedis#3515]
Lettuce has a feature [ReadFromSlave](https://www.baeldung.com/java-redis-lettuce#master_slave), Does Jedis support this feature?
we use Sentinel model to connect redis, all the write and read command send to master,it makes master with high load, so i want to seperate write and read command to different node.

**Comment by yangbodong22011** [comment]
@luger1990 Hello, currently Jedis does not have the ReadFromSlave feature, and this feature has not yet been planned, but I have received your request.

**Comment by luger1990** [comment]
> @luger1990 Hello, currently Jedis does not have the ReadFromSlave feature, and this feature has not yet been planned, but I have received your request.

thanks, i hope we can have this feature later.
