### ISSUE TITLE
GeoRadiusResponse.java no has getHash() method 

### ISSUE THREAD

**Issue by startjava** [redis/jedis#3527]
redis command use "withhash" param.

but jedis GeoRadiusResponse.java no this method.

**Comment by startjava** [comment]
public class GeoRadiusResponse {
  private byte[] member;
  private double distance;
  private GeoCoordinate coordinate;
  private long rawScore;


no hash .

**Comment by startjava** [comment]
@sazzad16

**Comment by Harsh4902** [comment]
Can I work on this issue?

**Comment by sazzad16** [comment]
> Can I work on this issue?

@Harsh4902 Sure!

**Comment by Harsh4902** [comment]
@sazzad16 can you please review my code in this PR. I Just want to know that whether I am in right direction or not.

**Comment by sazzad16** [comment]
`rawScore` is the one you want. It's not apparent from first look but it has come from shortening `raw geohash-encoded sorted set score`.

JavaDoc will be added to clarify this by #3542.
