### ISSUE TITLE
java.lang.ClassCastException: [B cannot be cast to java.util.List

### ISSUE THREAD

**Issue by meetshah15** [redis/jedis#3534]
### Expected behavior

jedis.scan(cursor, params) should return a List of results & cursor as part of the ScanResult<String> Object

### Actual behavior

Getting this error on Linux environment after code is packaged into a jar file

```
java.lang.ClassCastException: [B cannot be cast to java.util.List
        at redis.clients.jedis.BuilderFactory$37.build(BuilderFactory.java:583)
        at redis.clients.jedis.BuilderFactory$37.build(BuilderFactory.java:580)
        at redis.clients.jedis.Connection.executeCommand(Connection.java:137)
        at redis.clients.jedis.Jedis.scan(Jedis.java:8576)

``` 
Note here that BuilderFactory.java:583 is actually code for ZSCAN and not just SCAN. Why would it go to ZSCAN?

The code works on local environment when running unit tests. But gives the above error when packaged into a jar file and run on a Linux env

```
        Jedis jedis = pool.getResource();
        jedis.select(DB_INDEX);
        Pipeline pipeline = jedis.pipelined();
        ScanParams params = new ScanParams().match(key + "*").count(100);
        String cursor = "0";
        do {
            ScanResult<String> fetch = jedis.scan(cursor, params);
            
            # ... application code... using pipeline

            cursor = fetch.getCursor();
        } while (!"0".equals(cursor));
        pipeline.sync();
        jedis.close();

```

#### Java version: "1.8.0_351"

Its pretty weird that code doesn't work after packaging into the jar.

**Comment by meetshah15** [comment]
Seems to be because I opened jedis.pipelined(). Deferring pipeline operation solves the issue.

**Comment by sazzad16** [comment]
👍 on figuring out yourself.

**Comment by shaoyongqu** [comment]
I have the same issue like this, but I don't use pipeline operation. Code  works on local environment when running unit tests. But gives the above error when packaged into a jar file and run on a Linux env
throw java.lang.ClassCastException: [B cannot be cast to java.util.List when run jedis.scan
