### ISSUE TITLE
Does jedis(5.0.0) support tracking?

### ISSUE THREAD

**Issue by wp973** [redis/jedis#3546]

**Comment by wplvlwc** [comment]
In addition, I don’t seem to see the definition of **push** data.

**Comment by wplvlwc** [comment]
@sazzad16

**Comment by wplvlwc** [comment]
How can jedis client listen the "push" messages? 🧐

[lettuce](https://github.com/lettuce-io/lettuce-core/issues/1284)

**Comment by wplvlwc** [comment]
@sazzad16

**Comment by wplvlwc** [comment]
How can jedis client listen the "push" messages? 🧐 @sazzad16 

lettuce push messages: https://github.com/lettuce-io/lettuce-core/issues/1284

**Comment by wplvlwc** [comment]
RESP3

https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md

![image](https://github.com/redis/jedis/assets/65935888/78c88974-121a-4ee7-b0db-dca99ca38fb1)

**Comment by sazzad16** [comment]
Resolved by #3757 and released in [5.2.0 GA](https://github.com/redis/jedis/releases/tag/v5.2.0).
