### ISSUE TITLE
SSUBSCRIBE failover

### ISSUE THREAD

**Issue by adamsau** [redis/jedis#3548]
in cluster mode, what is the correct way to resubscribe to new node when a switch in master happens? when the master becomes slave, we receive SUNSUBSCRIBE message. When we try to reconnect, it reconnect to the old node which is no longer in the cluster and does not receive message.

**Comment by adamsau** [comment]
@sazzad16

**Comment by sazzad16** [comment]
> When we try to reconnect, it reconnect to the old node

@adamsau We can't do much at this moment until we get `-MOVED` like error from Redis.

You can try to trigger it by executing a command on same hash slot; i.e.

```java
exists("CHANNEL_NAME");
```

even better a write command; i.e.

```java
set("{CHANNEL_NAME}_any_suffix", "any_value");
```

**Comment by adamsau** [comment]
thanks, i agree redis should send MOVED when the master becomes slave
