### ISSUE TITLE
Namespace `pom.properties`

### ISSUE THREAD

**Issue by ccjernigan** [redis/jedis#3556]
### Expected behavior
Jedis JAR contents should be namespaced to avoid conflicts when compiled together with other JARs in an application.

I think the more conventional namespace would be `META-INF/maven/redis.clients/jedis/pom.properties`

### Actual behavior
Jedis JAR contains pom.properties at the root which could conflict with other libraries at compile time.

### Steps to reproduce:
1. Unzip the Jedis 5.0 JAR 
2. See pom.properties in the root

### Redis / Jedis Configuration
5.0

**Comment by sazzad16** [comment]
@yangbodong22011 fyi
