### ISSUE TITLE
Unable to subscribe to multiple channels through the same jedisPooled

### ISSUE THREAD

**Issue by JacobZheng0927** [redis/jedis#3563]
### Expected behavior

I expect to be able to subscribe to multiple channels in sequence using the same jedisPooled.

### Actual behavior

When I execute the following code

```
subJedis.subscribe(new JedisPubSub { ...} , "channel A")
subJedis.subscribe(new JedisPubSub { ...} , "channel B")
```

In fact channel B is not subscribed.
When I look at the thread stack via jstack, I only see one thread blocked by the jedis operation. I understand that subscription is a blocking operation, but when I subscribe multiple times using the thread pool shouldn't more than one thread be blocked instead of the second subscription being blocked by the first?

### Steps to reproduce:
As shown in the code above.

**Comment by sazzad16** [comment]
Are you executing these in separate threads? If not, like it is shown in your post, means that the second `subscribe` command is not even executed because the first one is blocking the thread.

**Comment by JacobZheng0927** [comment]
Close issue. There is a problem with our test scenario. JedisPooled and subscription operations are working fine.
