### ISSUE TITLE
JSON Path.of

### ISSUE THREAD

**Issue by NelminDev** [redis/jedis#3572]
Hello! I wanted to know if I need to use "$.xy" when using Path.of in jedis.jsonSet

**Comment by sazzad16** [comment]
`$.xy` actually indicates RedisJSON v2. So you should use `Path2`.

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
