### ISSUE TITLE
Json List

### ISSUE THREAD

**Issue by NelminDev** [redis/jedis#3574]
Hey mates!
I am using RedisJSON v2 and wanted to ask how I should get a json list. Should I us jsonGet or get?

```java
pipeline.get("a", Path2.of("$.b"))

// or

pipeline.jsonGet("a", Path2.of("$.b"))
```

**Comment by sazzad16** [comment]
@NelminDev First of all, please respect our guideline:

> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.

**Comment by sazzad16** [comment]
@NelminDev Did you even try `pipeline.get("a", Path2.of("$.b"))`? This is not possible.

**Comment by NelminDev** [comment]
No, I can't try it because I am currently not able to so I just wanted to ask to make sure if I did it right.

**Comment by sazzad16** [comment]
`pipeline.get("a", Path2.of("$.b"))` is not possible.

`pipeline.jsonGet("a", Path2.of("$.b"))` is possible.
There are other over-loaded variants of `jsonGet` available.
