### ISSUE TITLE
Redis connections is very high

### ISSUE THREAD

**Issue by GuoWR** [redis/jedis#3582]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:
In the project, Jedis 2.9.0 client was used to operate Redis, which includes both regular operations (set, get) and pipeline operations. After using pipeline operations, the number of Redis connections is very high. A project has 12 instances and multiple projects use this redis. Without pipeline, the number of individual Redis connections is about 0.8K. After using pipeline batch operations, the number of connections is about 3.5k; May I ask where the problem is?

### Redis / Jedis Configuration
```yaml
redis:
  maxTotal: 1024
  maxIdle: 1024
  minIdle: 32
```
#### Jedis version:
 2.9.0
#### Redis version:
3.2
#### Java version:
jdk1.8

**Comment by sazzad16** [comment]
First of all, Jedis 2.9.0 is quite old... more than 7 years old.

However, the basic idea of pipeline is about same. But only from description I can't even guess the probable reasons.
