### ISSUE TITLE
Can you please release #3586 version

### ISSUE THREAD

**Issue by jalajarora** [redis/jedis#3588]
### Expected behavior

Hi, Can you please release this [https://github.com/redis/jedis/pull/3586](https://github.com/redis/jedis/pull/3586) PR as it is failing the security checks on our end due to 
`org.json:json` not being on the `org.json:json@20231013` version.

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by sazzad16** [comment]
Each of [4.4.6](https://github.com/redis/jedis/releases/tag/v4.4.6) and [5.0.2](https://github.com/redis/jedis/releases/tag/v5.0.2) has addressed this.
