### ISSUE TITLE
JedisCluster is broken after a few requests?

### ISSUE THREAD

**Issue by Gandalf1783** [redis/jedis#3599]
### Expected behavior

JedisCluster should continue working, but locks up after just ~3 requests?

### Actual behavior

JedisCluster.set or .get locks up the whole thread.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Create a connection to a 3 node cluster via JedisCluster class:
```
ArrayList<HostAndPort> redisHosts = new ArrayList<>();

//'redisHosts' is getting pushed some HostAndPort instances here...

cluster = new JedisCluster(redisHosts, DefaultJedisClientConfig.builder()
                    .build(), DEFAULT_REDIRECTIONS, DEFAULT_POOL_CONFIG);
```
2. In my case, run a testConnection method 3 times:
```
public boolean testConnection() {
        if(cluster == null)
            return false;

        try {
            Map<String, ConnectionPool> nodes = cluster.getClusterNodes();
            Iterator<Map.Entry<String, ConnectionPool>> it = nodes.entrySet().stream().iterator();
            System.out.println("### REDIS CLUSTER CONNECTION POOL ###\n");
            while(it.hasNext()) {
                Map.Entry<String, ConnectionPool> entry = it.next();
                ConnectionPool pool = entry.getValue();
                if(pool != null) {
                    System.out.println("Key: "+entry.getKey());
                    System.out.println("Closed? "+pool.isClosed());
                    System.out.println("Resource.isConnected? "+pool.getResource().isConnected());
                    System.out.println("Resource.isBroken? "+pool.getResource().isBroken());
                }
            }
            System.out.println("Writing random UUID to Redis to test:");
            UUID testConnectionRandomUUID = UUID.randomUUID();
            System.out.println("Writing "+testConnectionRandomUUID);
            String ackSet = cluster.set("testConnection"+testConnectionRandomUUID, testConnectionRandomUUID.toString());
            boolean result = cluster.get("testConnection"+testConnectionRandomUUID).equalsIgnoreCase(testConnectionRandomUUID.toString());
            System.out.println("Redis Ack: "+ackSet);
            System.out.println((result ? "Random UUID works!" : cluster.get("testConnection"+testConnectionRandomUUID)+ " did not match "+testConnectionRandomUUID));
            cluster.del("testConnection"+testConnectionRandomUUID);
            return result && ackSet.equalsIgnoreCase("OK");
        } catch (Exception e) {
            System.out.println("### REDIS CLUSTER EXCEPTION ###");
            System.out.println(e.getMessage());
            System.out.println(e.getCause());
            return false;
        }
    }
```
3. Locks up on cluster.set or .get.

### Redis / Jedis Configuration
(See creation above)

#### Jedis version:
5.0.1 (via maven - mvnrepository.com)

#### Redis version: (redis-server --version)
6.0.16 (64 Bits, Build: 6d95e1af3a2c082a)

#### Java version: (java --version)
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Debian-1deb11u1, mixed mode, sharing)

# HINT:
I may have something wrong with my setup, and the issue may not lie in jedis at all.
I currently have no idea why it would block.
JedisCluster is used in a library of mine that I use in some other projects:

Application.jar
| -- My Library.jar
|     |--- Jedis
|     |--- MariaDB, etc...

My Library.jar is used in other Applications aswell and does NOT crash there.
All other Applications currently run on the same vm (not in any docker containers, all connections have the same firewall rules applied (currently none), etc.).

REDIS reports an increase of around 10 connections when its blocking. -> Could be a hint to the 8 connections from the pool issue mentioned in the docs?
REDIS has a baseline of around 15-17 concurrent connections (reported via telegraf/grafana) -> Shouldnt be a max connections issue.

**Comment by Gandalf1783** [comment]
I have just confirmed this happens after exactly 3 calls of the testConnection(); method.

The calls are multiple seconds apart and therefore shouldnt hit any "max queries per sec" limits.

**Comment by Gandalf1783** [comment]
Using a debugger, I was able to confirm it halts on cluster.set

**Comment by Gandalf1783** [comment]
I also just found out that the issue is not connected to the JedisCluster arguments, just providing a HashSet (e.g. new JedisCluster(redisClusterNodes);) does not change the situation.

**Comment by sazzad16** [comment]
You are not returning the resources received by calling `pool.getResource()`, so those pools are getting exhausted.

**Comment by Gandalf1783** [comment]
Ahhh that makes sense.
I am fixing this later today, but I think this can be closed already :)
