### ISSUE TITLE
Creating new StreamEntityID with >=3 "-"

### ISSUE THREAD

**Issue by 1BAH** [redis/jedis#3601]
Let's consider addind an entry to the stream with key "3-2-0" :

```java
jedis.xadd("stream", new StreamEntryID("3-2-0"),
        Map.of("a", "b")
);
```

### Expected behavior

Exception is thrown when adding key to stream.

### Actual behavior

Everything works.. The entry is added to the stream and its key is "3-2"

It happens because of such an implementation of the creating new StreamEntryID:

```java
public StreamEntryID(String id) {
    String[] split = id.split("-");
    this.time = Long.parseLong(split[0]);
    this.sequence = Long.parseLong(split[1]);
}
```

Split string size may be 3 or more.

### Steps to reproduce:

Run this one:
```java
jedis.xadd("stream", new StreamEntryID("3-2-0"),
        Map.of("a", "b")
);
```

#### Jedis version:
4.3.1

#### Redis version:
7.2.1

#### Java version:
11

**Comment by sazzad16** [comment]
We usually assume that it user's duty to send proper data.

For example, following is another possible variant where we do not check the validity of ID and leave it to the user to send properly.

```java
jedis.xadd("stream",
        XAddParams.xAddParams().id("3-2-0"),
        Map.of("a", "b")
);
```
