### ISSUE TITLE
Create Java code snippet for sorted sets

### ISSUE THREAD

**Issue by sav-norem** [redis/jedis#3624]
The redis.io webpage for [sorted sets](https://redis.io/docs/data-types/sorted-sets/) needs the Java example as well. The python equivalent can be used to copy the setup and can be found [here](https://github.com/redis/redis-py/pull/3002/files#diff-196240727c71b03fd8fc6bda16e52eaf85b85838c246d8874d4bd10ea05ce184)

The first line of the file needs to be the ID for the example - # EXAMPLE: ss_tutorial

Each separate section is delimited with a tag that you will need to copy exactly for it to appear in the correct place, ie.
```
# STEP_START zadd 
{code}                                    
# STEP_END

# HIDE_START, # HIDE_END, # REMOVE_START, and # REMOVE_END can be used for debugging and deleting keys. Hide will hide until a user expands the example, remove will only be seen in the source code and will never appear on the webpage.
```

@dwdougherty and I will be reviewing and tracking these issues - feel free to tag us with any questions

**Comment by sazzad16** [comment]
Resolved by #3680
