### ISSUE TITLE
Create Java code snippets for Bloom

### ISSUE THREAD

**Issue by sav-norem** [redis/jedis#3630]
The redis.io webpage for [Bloom](https://redis.io/docs/data-types/probabilistic/bloom-filter/) needs the Java example as well. The python equivalent can be used to copy the setup and can be found [here](https://github.com/redis/redis-py/blob/emb-examples/doctests/dt_bloom.py)

The first line of the file needs to be the ID for the example - # EXAMPLE: bf_tutorial

Each separate section is delimited with a tag that you will need to copy exactly for it to appear in the correct place, ie.
```
# STEP_START bloom
{code}                                    
# STEP_END

# HIDE_START, # HIDE_END, # REMOVE_START, and # REMOVE_END can be used for debugging and deleting keys. Hide will hide until a user expands the example, remove will only be seen in the source code and will never appear on the webpage.
```

@dwdougherty and I will be reviewing and tracking these issues - feel free to tag us with any questions

**Comment by sazzad16** [comment]
Resolved by #3671
