### ISSUE TITLE
Create Java code snippets for top-k

### ISSUE THREAD

**Issue by sav-norem** [redis/jedis#3634]
The redis.io webpage for [top-k](https://redis.io/docs/data-types/probabilistic/top-k/) needs the Java example as well. The python equivalent can be used to copy the setup and can be found [here](https://github.com/redis/redis-py/blob/emb-examples/doctests/dt_topk.py)

The first line of the file needs to be the ID for the example - # EXAMPLE: topk_tutorial

Each separate section is delimited with a tag that you will need to copy exactly for it to appear in the correct place, ie.
```
# STEP_START topk
{code}                                    
# STEP_END

# HIDE_START, # HIDE_END, # REMOVE_START, and # REMOVE_END can be used for debugging and deleting keys. Hide will hide until a user expands the example, remove will only be seen in the source code and will never appear on the webpage.
```

@dwdougherty and I will be reviewing and tracking these issues - feel free to tag us with any questions

**Comment by Ranjeet0611** [comment]
Hi @sav-norem do we have to create doctests package and create sample java file for top-k?

**Comment by dwdougherty** [comment]
Hi Ranjeet. Yes, we're asking the community to provide examples for Redis base commands, including Top-K. As @sav-norem wrote above, look at the equivalent Python example for guidance. Also check out the emb-samples branch of this repo and look at how other examples (src/test/java/io/redis/examples) are constructed.

**Comment by Ranjeet0611** [comment]
Sure Thank you @dwdougherty
