### ISSUE TITLE
How do I invoke commands provided by external modules?

### ISSUE THREAD

**Issue by fasnow** [redis/jedis#3667]
Use jedis.moduleLoad("/module/path/file.so") to add module,but how do I invoke commands provided by external modules?

**Comment by sazzad16** [comment]
You can use `executeCommand` (or `sendCommand`) methods.

From [the tests](https://github.com/redis/jedis/blob/77d52ab04fa333a3c2c50d0150c09300b1c92161/src/test/java/redis/clients/jedis/commands/jedis/ModuleTest.java).

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
