### ISSUE TITLE
UnifiedJedis.ftAggregate always returning only 10 rows

### ISSUE THREAD

**Issue by dsinghal-nice** [redis/jedis#3678]
#### Expected Behavior
Performing sort by aggregation using .ftAggregate should return all the results and cursor as per the provided count.

#### Actual Behavior
I am trying to run Aggregation on my Redis Stack server using UnifiedJedis Bean. When I execute the command using .ftAggregate it returns me only 10 rows with cursor 0, which means end of results where as my server contains ~7000 JSON objects stored in it.

### Steps to reproduce:
1. Created UnifiedJedis bean and autowired in my service, 
2. Build Aggregation Builder and pass it to .ftAggregate method of unifiedJedis
3. In Aggregation Builder passed fields that needs to be sorted by and applied cursor count as 1000
4. Kept MAX_IDLE_TIME as 3000

```
@Bean
    public UnifiedJedis unifiedJedis(JedisConnectionFactory jedisConnectionFactory) {
        HostAndPort hostAndPort = new HostAndPort(
                jedisConnectionFactory.getHostName(),
                jedisConnectionFactory.getPort());
        return new UnifiedJedis(hostAndPort);
    }

```
Implementation in my service

```
AggregationBuilder aggregationBuilder = createAggregationBuilder(request, chunkSize);

AggregationResult result = unifiedJedis.ftAggregate(indexName, aggregationBuilder);
        LOGGER.info("result 1 size :: " + result.getRows().size());
        LOGGER.info("Cursor returned 1:: " + result.getCursorId());
```

//Response of above Logs
result 1 size :: 10
Cursor returned 1:: 0

// my method for creating the Aggregation Builder, chunkSize passed as 1000
```
public AggregationBuilder createAggregationBuilder(BaseRequest request, int chunkSize) {
        SortedField[] sortedFields = prepareSortFields(request);
        return new AggregationBuilder("*")
                .loadAll()
                .sortBy(sortedFields)
                .cursor(chunkSize, MAX_IDLE_TIME);
    }

    private SortedField[] prepareSortFields(BaseRequest request) {
        List<SortedField> sortedFieldList = new ArrayList<>();
        if(!request.getOrderByFields().isEmpty()) {
            request.getOrderByFields().forEach(sort -> {
                SortedField.SortOrder order = sort.getSortBy().equalsIgnoreCase("asc") ? SortedField.SortOrder.ASC
                        : SortedField.SortOrder.DESC;
                SortedField sortedField = new SortedField("@" + sort.getFieldName(), order);
                sortedFieldList.add(sortedField);
            });
        }
        return sortedFieldList.toArray(new SortedField[sortedFieldList.size()]);
    }
```

#### redis-om-spring version: 0.8.7

I am using an older version of Jedis library, since redis-om-spring is not compatible to work with latest version of it.

Can you please check and let me know why this query is not working properly, same query is working fine on RedisInsight.

Query prepared by above code:

`"FT.AGGREGATE" "myIndex" "*" "LOAD" "*" "SORTBY" "4" "@state" "ASC" "@empId" "DESC" "WITHCURSOR" "COUNT" "1000" "MAXIDLE" "3000"`

Apologies if this is not the right forum.

**Comment by sazzad16** [comment]
> same query is working fine on RedisInsight.

Could you check the query prepared by RedisInsight?

**Comment by dsinghal-nice** [comment]
I just re-checked with RedisInsight, if I apply WITHCURSOR it is always returning me 10 rows with the cursor ending at 0, meaning no more rows available. But if I apply only limit it is returning me the rows with that limit. Not sure if this is some issue from Redis itself.

**Comment by GuyAv46** [comment]
I think the problem might be that you are using a sortBy. The sorter of redisearch is actually a sorter+limiter, and it returns the top-k results of the value/s you sort by. The default limit of SORTBY is 10, so if you add a SORTBY without supplying `MAX n` or `LIMIT n m` you are expected to get only 10 results.
Notice that sorting the entire results has its memory and performance costs, and that’s why the default limit exists

**Comment by sazzad16** [comment]
@dsinghal-nice To address above suggestion, you may replace `.sortBy(sortedFields)` with:
- `.sortBy(1000, sortedFields)`
- `.sortBy(sortedFields).sortByMax(1000)`

**Comment by dsinghal-nice** [comment]
@sazzad16 @GuyAv46 Any limit for sortBy query, I mean like 1000 rows at once or 10k rows ?

**Comment by dsinghal-nice** [comment]
@GuyAv46 @sazzad16 Your suggestion for `.sortBy(1000, sortedFields)` is working for me.

**Comment by GuyAv46** [comment]
The limit for the sorter will also determine the limit for the entire query.
If you want to get 10k results overall, with cursor chunks of 1k, you need to pass 10k to the sorter
