### ISSUE TITLE
Did pipelined.sync() really close the pipeline and release the resource?

### ISSUE THREAD

**Issue by derecknowayback** [redis/jedis#3701]
I didn't see some thing like `client close` in the source code which is quite confusing:
```java
  /**
   * Synchronize pipeline by reading all responses. This operation close the pipeline. In order to
   * get return values from pipelined commands, capture the different Response&lt;?&gt; of the
   * commands you execute.
   */
  public void sync() {
    if (getPipelinedResponseLength() > 0) {
      List<Object> unformatted = client.getAll();
      for (Object o : unformatted) {
        generateResponse(o);
      }
    }
  }
```

**Comment by sazzad16** [comment]
_"This operation close the pipeline."_ means that it completes a set of [Redis pipelining](https://redis.io/docs/manual/pipelining/) commands. It didn't claim to release _the resources_.

**Comment by sazzad16** [comment]
BTW, the code snapshot that you shared was committed on May 30, 2011 and was valid till August 5, 2013. This is quite old comparing today's January 31, 2024. So closing.
