### ISSUE TITLE
[question]Does jedis support jdk21?

### ISSUE THREAD

**Issue by polaris-alioth** [redis/jedis#3735]
Does jedis4.0 or later support jdk21? thanks.

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
