### ISSUE TITLE
How to use RedisTimeSeriesCommands with jedis 

### ISSUE THREAD

**Issue by DmtPytn** [redis/jedis#3739]
I am currently utilizing jedis version 4.3.0 in my Java Spring Boot project. I am interested in utilizing the Redis time series commands interface to store time series data in Redis. However, I am unsure whether I can directly employ Redis time series commands to interact with the time series data without the need for additional dependencies such as JRedisTimeSeries. If direct utilization is possible, how should I establish a connection and implement methods from that interface?

**Comment by sazzad16** [comment]
To use RedisTimeSeries in a Spring project, check [redis-om-spring](https://github.com/redis/redis-om-spring).
