### ISSUE TITLE
Add support for configuring connection pool to MultiClusterPooledConnectionProvider

### ISSUE THREAD

**Issue by jarkus4** [redis/jedis#3753]
Currently MultiClusterPooledConnectionProvider (redis.clients.jedis.providers.MultiClusterPooledConnectionProvider) creates new instance of ConnectionPool for each of configured clusters (MultiClusterClientConfig.GetClusterConfig()). This pool is created without providing any pool specific configuration (using constructor without JedisPoolConfig param), making it impossible to specify a number of pool specific settings eg maximum number of connections.

Please add possibility of passing JedisPoolConfig to be used during construction of those pools, preferably on the per cluster basis (ClusterConfig seems like a fitting place to pass it, but Im not sure)

**Comment by traitsisgiorgos** [comment]
hi, I am a new contributor. Can you give same more info about the request?

**Comment by jarkus4** [comment]
What kind of info do you need?

I would like to be able to set optional JedisPoolConfig member in ClusterConfig object (just as I set HostAndPort and JedisClientConfig). Then if its set it should be passed on when creating ConnectionPool for this cluster (as an additional constructor parameter compared to current one).

If you are asking about how to use MultiClusterPooledConnectionProvider in general its basic documentation is here: https://github.com/redis/jedis/blob/master/docs/failover.md

**Comment by thachlp** [comment]
Hi, I am also a new contributor 🤩
@sazzad16 @jarkus4 @traitsisgiorgos please help review my pr 🙇

**Comment by sazzad16** [comment]
Resolved by #3801
