### ISSUE TITLE
"ERR unknown command 'memory', with args beginning with: USAGE" with Jedis and AWS ElastiCache

### ISSUE THREAD

**Issue by pratik-patil-polestar** [redis/jedis#3766]
While using `**memoryUsage(key)**` method of Jedis i am getting this following error
"errorMessage": "ERR unknown command 'memory', with args beginning with: USAGE"
is it possible that this method is not allowed on AWS ElastiCache

### Expected behavior
I should retrieve the memory used by key-value in cache

### Actual behavior
getting this error : **_"ERR unknown command 'memory', with args beginning with: USAGE"_**

### Steps to reproduce:

  ```
public Long getValueSize(String hashKey, Jedis jedis) {
    log.info("Request received to get memory usage from redis for key {}", hashKey);
    byte[] serializeKey = kryo.serialize(hashKey);
    return jedis.memoryUsage(serializeKey);
  }
  
```
and i am using JedisPool from which i am taking a Jedis instance.

**Comment by sazzad16** [comment]
> is it possible that this method is not allowed on AWS ElastiCache

@pratik-patil-polestar ask AWS ElastiCache.

thank you for using Jedis
