### ISSUE TITLE
Redis 4.4.7 MultiNodePipeline binary command version of zrevrangeByScore is broken

### ISSUE THREAD

**Issue by keeferrourke** [redis/jedis#3783]
### Expected behavior

Pipelining using Jedis in cluster mode should return non-empty results when calling zrevrangeByScore on a key.

### Actual behavior

An empty list is always returned because the min / max arguments are flipped. 
https://github.com/redis/jedis/blob/3577f93f91229e6ab30719a5a11be4603848c088/src/main/java/redis/clients/jedis/MultiNodePipelineBase.java#L2866

This is similar to https://github.com/redis/jedis/issues/827.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random.

In a pipeline:

1. zadd("key", 1.0, "a")
2. zrevrangeByScore("key".getBytes(), "-10.0".getBytes(), "10.0".getBytes())

The command that is supposed to be sent is `ZREVRANGEBYSCORE key -10.0 10.0`.

What is actually sent is `ZREVRANGEBYSCORE key 10.0 -10.0`.

**Comment by sazzad16** [comment]
Fixed by #3784.

Thanks @keeferrourke for reporting.
