### ISSUE TITLE
readOnlyForReplica flag question

### ISSUE THREAD

**Issue by ruispereira** [redis/jedis#3929]
Checking master branch, in the class https://github.com/redis/jedis/blob/master/src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java there's a new flag to allow reading from replica nodes. This can be used with sentinels? Or in a master-slave configuration?

Another question is when a new release will be shipped with this feature?

**Comment by sazzad16** [comment]
It is meant for [READONLY](https://redis.io/commands/readonly/) command which is dedicated for Redis Cluster.

Thank you for asking this. I guess we'd have to rename+document it further.

**Comment by ruispereira** [comment]
Thank you for your quick response!
So, my team is using redis sentinels, for high availability, and using Spring Redis OM, we are reaching always master node for read and writes and we are getting 100% CPU most of the time for master node. 
Is there any way to force reads to go to replica nodes instead of reaching always master node?
Thanks in advance.

**Comment by sazzad16** [comment]
@ruispereira Not readily.

You may extend `SentineledConnectionProvider` and override `getConnection(CommandArguments` method achieve that.

**Comment by ruispereira** [comment]
Thank you!
And is there any way to known if the current operation is a read or write operation?

**Comment by sazzad16** [comment]
Using `CommandArguments.getCommand()` you would have recognize.
In your case it's enough to recognize only your HOT READ commands.

**Comment by ruispereira** [comment]
Ok, understand! 
One more question, how can i get the replicas? I see that jedis class have a **sentinelReplicas** method to get the list of replicas, i need to use this right? Do i have to have a thread, like the sentinel have, to known if a given replica die or something, so we will always have the list of replicas fresh..

**Comment by sazzad16** [comment]
It's up to you.

Your suggestion is of course a solution.

Someone else may consider maintaining list on their own and/or communicating with the replicas by executing a command (i.e. `ping`).

In either of the ways, separate thread could be needed.
