### ISSUE TITLE
5.2.0 release plan

### ISSUE THREAD

**Issue by linking12** [redis/jedis#3938]
I found that 5.2.0-beta4 has been out for a while, what is the plan for the release version?

Thank you

**Comment by sazzad16** [comment]
Duplicate #3814

**Comment by sazzad16** [comment]
> Github issues should be used to report bugs and for detailed feature requests. 
> Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
> or [Jedis Github Discussions](https://github.com/redis/jedis/discussions).
> 
> Please post general questions to Google Groups or Github discussions. 
> These can be closed without response when posted to Github issues.
