### ISSUE TITLE
Constructors that accept a URI and a JedisClientConfig pull elements from both without documentation

### ISSUE THREAD

**Issue by joshrotenberg** [redis/jedis#3982]
UnifiedJedis and possibly other type constructors that accept a `URI` and a `JedisClientConfig` instantiate themselves with a mix of elements from both. This isn't unreasonable given that the URI can contain more than just host and port, but it isn't documented.

Options to fix it:

* Document the current behavior
* Update the constructors to let, for example, any config options win if both are specified, and document the behavior.

For example:

```java
// works
UnifiedJedis jedis = new UnifiedJedis(new HostAndPort("localhost", 6379), DefaultJedisClientConfig.builder().user("username").password("password").build());

// also works
UnifiedJedis jedis2 = new UnifiedJedis(URI.create("redis://username:password@localhost:6379"));

// doesn't set auth correctly
UnifiedJedis ohNo = new UnifiedJedis(URI.create("redis://localhost:6379"), DefaultJedisClientConfig.builder().user("username").password("password").build());
```

See https://github.com/redis/jedis/blob/54426424a21070bba3b12454e48aa692efc3a9fa/src/main/java/redis/clients/jedis/UnifiedJedis.java#L90

**Comment by sazzad16** [comment]
@joshrotenberg Thank you for sharing. Our URI support is not so dynamic yet. In the current design, when you're using URI you should put all parameters that our URI processor supports.

I agree that stronger documentation would be helpful.

**Comment by kachida** [comment]
Hi @sazzad16 , @joshrotenberg , please assign this to me, Thanks

**Comment by sazzad16** [comment]
@kachida You can craft a PR. No 'assign'ment necessary.
