### ISSUE TITLE
Add Client Side Caching Example in `src/test/java/redis/clients/jedis/examples`

### ISSUE THREAD

**Issue by atharva29** [redis/jedis#3986]
### Expected behavior

Add example of Client Side Caching in `src/test/java/redis/clients/jedis/examples`

Write here what you're expecting ...

This example will help developers to write code with ease. 
It should include
- Redis Key SET GET
- Redis HASH SET GET
 

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by mamatthew** [comment]
Hi @atharva29, I noticed there are already examples of client-side cache usage in `src/test/java/redis/clients/jedis/csc`. Could you clarify how adding an example here would differ from those, or what specific aspect you had in mind?
