### ISSUE TITLE
Support for HASH Eviction on basis of Keys & fields, Not only on KEY basis (for Client side caching)

### ISSUE THREAD

**Issue by atharva29** [redis/jedis#3987]
### Expected behavior
Whenver there is a change in hash key. In client side caching, only the hash field should be changed and should not update the whole client key(with other fields). This will reduce the data transfer between client-side applications & redis.

### Actual behavior

Currently whole Redis hash is cleared per hash field change. eg. If my key is `user` with fields `id` , `address`, `designation`.  If I change only one field, the whole Redis hash shouldn't get cleared on the client side cache.
We also need to add field name in the keyspace notification.

**Comment by sazzad16** [comment]
@atharva29 First of all, thank you for using Jedis and sharing your idea.

It doesn't match the Redis [client-side caching documentation](https://redis.io/docs/latest/develop/reference/client-side-caching/). If you think this is a worthy change **considering all other factors**, please ask in the [Redis repo](https://github.com/redis/redis).

Furthermore, there would be several new issues while supporting the proposed feature, **especially without support from server**.

**Comment by atharva29** [comment]
@sazzad16  thanks for the reply, I understood
