### ISSUE TITLE
setTimeoutInfinite() method still in eval()

### ISSUE THREAD

**Issue by Feng-yi-da** [redis/jedis#4004]
I noticed that [issue1147](https://github.com/redis/jedis/issues/1147) and [pull2408](https://github.com/redis/jedis/pull/2408) mentioned '[Remove usage of infinite timeout from EVAL commands](https://github.com/redis/jedis/pull/2408)'.

However, I found that the EVAL method in the 3.x branch code still uses setTimeoutInfinite(). Can you tell me why the setTimeoutInfinite() method is not removed?

https://github.com/redis/jedis/blob/358e1271cd676dce73042448ad19215575b84036/src/main/java/redis/clients/jedis/BinaryJedis.java#L3955

https://github.com/redis/jedis/blob/358e1271cd676dce73042448ad19215575b84036/src/main/java/redis/clients/jedis/Jedis.java#L3307

At the same time, I found that the Jedis object instantiated using the makeObject()method of JedisFactory.java did not get the value of the BlockingSocketTimeoutMillis parameter.  

https://github.com/redis/jedis/blob/358e1271cd676dce73042448ad19215575b84036/src/main/java/redis/clients/jedis/JedisFactory.java#L166

The problem occurred in the BinaryJedis,java constructor. The infiniteSoTimeout parameter is not set for the client.

https://github.com/redis/jedis/blob/358e1271cd676dce73042448ad19215575b84036/src/main/java/redis/clients/jedis/BinaryJedis.java#L292

#### Jedis version:
3.10.0

**Comment by sazzad16** [comment]
#2408 was targeted for Jedis 4.0.0 release.
The source codes that you're referencing are from branch 3.x. Some changes/updates available in version 4+ cannot be found in version lower than 4. Hope you understand.
