### ISSUE TITLE
NPE thrown when invoking  Jedis#commandInfo against Redis server 6.2.16

### ISSUE THREAD

**Issue by ggivo** [redis/jedis#4017]
### Expected behavior
NPE is not thrown 

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:
```
try ( Jedis jedis = new Jedis ("localhost", 6379) { 
   Map<String, CommandInfo> infos = jedis.commandInfo("GET", "foo", "SET");
}
```

or  run ControlCommandsTest#commandInfo test

### Redis / Jedis Configuration
default
#### Jedis version:
5.2.0
#### Redis version:
6.2.16 (or Redis server 7.0.0< ) 
#### Java version:
1.8

**Comment by sazzad16** [comment]
Resolved by #4031
