### ISSUE TITLE
jediscluster 4.2，Use MSET command problem:  Keys must belong to same hashslot. at redis.clients.jedis.ClusterCommandArguments.processKey(ClusterCommandArguments.java:36)

### ISSUE THREAD

**Issue by killgodaa** [redis/jedis#4036]
### Expected behavior

When I was using the jedis-4.2.2.jar is used normally, Use jedisiCluster API and using the meset method to set multiple keys at once, an error occurred

`redis.clients.jedis.exceptions.JedisClusterOperationException: Keys must belong to same hashslot.
	at redis.clients.jedis.ClusterCommandArguments.processKey(ClusterCommandArguments.java:36)
	at redis.clients.jedis.CommandArguments.key(CommandArguments.java:80)
	at redis.clients.jedis.CommandArguments.keys(CommandArguments.java:90)
	at redis.clients.jedis.CommandObjects.mget(CommandObjects.java:484)
	at redis.clients.jedis.UnifiedJedis.mget(UnifiedJedis.java:740)`

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:
I wrote a mock test code to reproduce the error.

`

import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.JedisCluster;

import java.util.HashSet;
import java.util.Set;

public class JedisClusterMSetExample {

    public static void main(String[] args) {

        Set<HostAndPort> clusterNodes = new HashSet<>();
        clusterNodes.add(new HostAndPort("127.0.0.1", 6379));
        JedisCluster jedisCluster = new JedisCluster(clusterNodes);

        String[] keysValues = new String[]{
            "name", "Alice",
            "age", "30",
            "city", "New York"
        };

        try {

            jedisCluster.mset(keysValues);
        } finally {
          
            try {
                jedisCluster.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}`

### Redis / Jedis Configuration

Jedis version: 4.2.2

Redis version:6.2.0

Java version: java11

**Comment by sazzad16** [comment]
@killgodaa It is by design and part of [Redis cluster specification](https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/).

> Commands performing complex multi-key operations like set unions and intersections are implemented for cases where all of the keys involved in the operation hash to the same slot.

**Comment by killgodaa** [comment]
How do I use batch set for multiple keys

**Comment by killgodaa** [comment]
I want to execute a batch of arbitrary keys in jedisiCluster, which are not in the same hash slot, nor do I want to execute for loops multiple times. I just want to send multiple instructions at once like a pipeline, without worrying about which hash slot the keys are in

**Comment by sazzad16** [comment]
The best way would be grouping the keys by their hashslots and executing MSET command for each group of keys. You can use `JedisClusterCRC16.getSlot(key)` method to calculate the individual hashslot.

> I just want to send multiple instructions at once like a pipeline

You may consider `ClusterPipeline` and SET command.
