### ISSUE TITLE
jedisCluster4.2.2,Jediscluster provides the MSET method,why can't we execute a batch of arbitrary keys? 

### ISSUE THREAD

**Issue by killgodaa** [redis/jedis#4037]
### Expected behavior

`Jediscluster provides the MSET method, why can't we execute a batch of arbitrary keys? The official documentation records executing a batch of identical hash slot keys during the MSET process, which I don't think is user-friendly. Actually, it should be easy to implement. Why hasn't Jediscluster achieved this?`

### Actual behavior

I want to execute a batch of arbitrary keys in jedisiCluster, which are not in the same hash slot

### Steps to reproduce:

`public static void main(String[] args) {

    Set<HostAndPort> clusterNodes = new HashSet<>();
    clusterNodes.add(new HostAndPort("127.0.0.1", 6379));
    JedisCluster jedisCluster = new JedisCluster(clusterNodes);

    String[] keysValues = new String[]{
        "name", "Alice",
        "age", "30",
        "city", "New York"
    };

    try {

        jedisCluster.mset(keysValues);
    } finally {
      
        try {
            jedisCluster.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}`

### Redis / Jedis Configuration

Jedis version: 4.2.2

Redis version:6.2.0

Java version: java11

**Comment by sazzad16** [comment]
Duplicate #4036

**Comment by sazzad16** [comment]
@killgodaa Please don't create duplicate issues.
We have responded and are still responding in #4036.
Thank you for understanding.
