### ISSUE TITLE
Implement sdiff, sunion, smove and other set redis commands for ShardedJedis and update the JedisCommands interface

### ISSUE THREAD

**Issue by bpraveen** [redis/jedis#471]

**Comment by marcosnils** [comment]
As keys might eventually be in different shards we'll need to discuss the proper implementation for this

**Comment by HeartSaVioR** [comment]
Do we need to implement multi-key operations on ShardedJedis?
For now we don't have to do it, since we agree ShardedJedis is not the core of Jedis, and it could be extracted to other module/project.

**Comment by marcosnils** [comment]
@HeartSaVioR I guess you're right. Let's leave this issue open so we can move it once we separate ShardedJedis from Jedis core.

**Comment by sazzad16** [comment]
Resolved in [Jedis 4](https://github.com/redis/jedis/releases/tag/v4.0.0)
